"""Lasīšana text catalog.

Generated by scripts/generate_reading_texts.py and later polished by
scripts/expand_reading_texts.py (+10-15% length) and
scripts/review_reading_texts.py (native-editor pass). Two seed texts
(PUTNI ZIEMĀ and CITRONS) are official PMLP paraugi for the
«Latvieši un līvi» category; the rest are Grok-authored in the same
mold (~140 words, 3-4 paragraphs, informative-publicistic style)
across the 11 official PMLP topics.

Format per entry:
- id: short slug
- title_lv: uppercase heading
- topic: one of READING_TOPICS keys
- source: "PMLP paraugs …" for seeds, otherwise absent
- body: 3-4 paragraphs separated by "\n\n"
- questions: exactly 5 Latvian questions of varying types
"""

from __future__ import annotations

READING_TOPICS: dict[str, str] = {
    "gimene": "es un mani tuvinieki (ģimene, radi, draugi)",
    "dzivesvieta": "dzīves apstākļi un vide (māja, dzīvoklis, lauki, pilsēta)",
    "darbs": "izglītība, darbs, intereses",
    "attiecibas": "attiecības ar citiem cilvēkiem, pieklājība, kaimiņi",
    "kultura": "kultūra un sociālās lietas (tradīcijas, mūzika, teātris, kino)",
    "brivais_laiks": "brīvais laiks un sabiedriskā dzīve",
    "sports": "sports, vaļasprieks",
    "iepirksanas": "iepirkšanās, veikali, tirgus",
    "edieni": "ēdieni un dzērieni",
    "celosana": "ceļošana, Latvijas vietas, transports",
    "laiks": "laika apstākļi, gadalaiki, daba"
}

READING_TEXTS: list[dict] = [
    {
        "id": "putni_ziema",
        "title_lv": "PUTNI ZIEMĀ",
        "topic": "laiks",
        "source": "PMLP paraugs (Latvieši un līvi)",
        "body": "Kad pienāk ziema un kļūst auksti, cilvēki sāk barot putnus. Vieniem liekas, ka putniem nav ko ēst, citiem patīk tos vērot, vēl citi grib saviem bērniem parādīt dažādus putnus. Ja tos baro ziemā, putni labprāt pie mājām dzīvos arī vasarā, kad gaisā būs daudz mušu un kukaiņu.\n\nMūsdienās var nopirkt gatavas barotavas, barības maisījumus, dažādus interjera priekšmetus putniem. Latvijā “modē” ir paštaisītās barotavas: no koka, piena pakām, plastmasas un stikla pudelēm, pat no konservu kārbām.\n\nPutnus barot ir jāsāk jau oktobrī, jo tad viņi sāk meklēt vietas, kur ziemā būs ēdiens. Cilvēkam jāatceras: ja viņš sāk barot putnus, tas ir jādara regulāri katru dienu. Putniem nedrīkst dot sālītu ēdienu un baltmaizi, vislabāk – dažādas sēklas, graudus, speķi.\n\nOrnitologi uzskata, ka nav pareizi barot putnus citos gadalaikos. Labāk ir radīt vidi, lai putni gribētu uzturēties tuvāk cilvēku mājām, piemēram, stādīt augļu kokus un ogu krūmus, būvēt putnu būrus.",
        "questions": [
            "Kāpēc cilvēki ziemā baro putnus?",
            "No kāda materiāla izgatavo barotavas putniem Latvijā?",
            "Cik bieži ir jābaro putni ziemā?",
            "Kurš ēdiens ziemā ir vislabākais putniem?",
            "Ko vēl vajadzētu darīt, lai putni gribētu dzīvot tuvāk cilvēku mājām?"
        ]
    },
    {
        "id": "citrons",
        "title_lv": "CITRONS",
        "topic": "edieni",
        "source": "PMLP paraugs (Latvieši un līvi)",
        "body": "Citrons vienlīdz labi iederas atspirdzinošā limonādē ar ledu un karstā tējā ar medu. Īstā limonāde: izspiež vienu ēdamkaroti citronu sulas, pievieno ēdamkaroti cukura, glāzi ūdens un sajauc.\n\nPar citronkoku dzimteni pētnieki vienbalsīgi atzīst Āziju. Reģionos, kur citroni aug, tos plaši lieto gan tautas medicīnā, gan pārtikā. Iespējams, ka pirmie svešzemnieki, kas novērtēja citronu labās īpašības, bija jūrasbraucēji – viņi ievēroja, ka citronu sula glābj no cingas, kas rodas ilgā kuģojumā, kad jāiztiek ar stipri vienveidīgu pārtiku.\n\nCitrons joprojām ir tāds kā etalons, ar kuru salīdzina citus C vitamīna avotus. Lai kur citroni nonāca, tie tika novērtēti un iecienīti. Tropu un subtropu zemēs cilvēki tos sāka audzēt dārzos, bet vēsākā klimatā centās padarīt par telpaugiem.",
        "questions": [
            "Kā citronus izmanto vietas, kur tie aug?",
            "Kas jāpievieno ūdenim, lai pagatavotu īstu limonādi?",
            "Kādiem dzērieniem var pievienot citronu?",
            "No kurienes citrons izplatījās visā pasaulē?",
            "Kur cilvēki audzē citronkokus?"
        ]
    },
    {
        "id": "gimenes_janu_svinešana",
        "title_lv": "ĢIMENISKIE JĀŅI",
        "topic": "gimene",
        "body": "Jāņu svētki ir nozīmīgi latviešu gadskārtu svētki, ko ģimenes svin kopā vasaras saulgriežu laikā. Tie notiek 23. un 24. jūnijā, pulcējot tuviniekus un draugus. Daudziem tas ir laiks, kad stiprināt ģimenes saites, baudīt dabu un atpūsties no ikdienas steigas. Latvijā šie svētki veicina kopīgu prieku un tradīciju saglabāšanu.\n\nPēdējos desmit gados aptuveni 80 procentu Latvijas iedzīvotāju svin Jāņus ģimenes lokā, īpaši laukos un Rīgas apkārtnē. Populāras vietas ir Mežaparks, Jūrmalas pludmales un lauku sētas pie Daugavas. Bērni un mazbērni kopā vāc zāles un ziedus vainagiem jau jūnijā.\n\nĢimenēs cep Jāņu sieru no rūgtmaizes, gatavo pīrāgus ar jaunajiem kartupeļiem un svaigiem zaļumiem. Sievietes pīš puķu vainagus, vīrieši zārina mājas durvis. Iesaka sākt sagatavošanos maijā, nedrīkst aizmirst ugunsdrošību un alkoholisko dzērienu mēru.\n\nFolkloristi uzsver, ka ģimenes Jāņu svinēšana stiprina tuvinieku saites un saglabā latviešu paražas. Tā ir iespēja mācīt bērniem senās tradīcijas un baudīt kopīgu prieku dabā.",
        "questions": [
            "Kad Latvijā svin Jāņu svētkus?",
            "Kāpēc ģimenes svin Jāņus kopā?",
            "Kā ģimenēs gatavo Jāņu sieru?",
            "Kas kopā vāc zāles un ziedus vainagiem?",
            "Ko nedrīkst aizmirst Jāņu svinēšanā?"
        ]
    },
    {
        "id": "vecvecaku_loma_gimenes",
        "title_lv": "VECVECĀKI ĢIMENĒ",
        "topic": "gimene",
        "body": "Latvijā vecvecāki spēlē svarīgu lomu mūsdienu ģimenēs. Straujas dzīves temps, vecāku darba pienākumi un emigrācijas sekas padara viņu palīdzību neaizstājamo. Viņi auklē mazbērnus, māca senas tradīcijas un sniedz emocionālo atbalstu starp paaudzēm. Tas stiprina ģimenes saites un saglabā kultūras vērtības.\n\nPēdējos desmit gados aptuveni 65 procenti Latvijas ģimeņu saņem regulāru palīdzību no vecvecākiem. Rīgā un citās lielpilsētās tas ir īpaši izplatīts, jo vecāki strādā garas stundas. Vasarās bērni bieži pavada laiku pie vecvecākiem laukos, piemēram, Vidzemē vai Kurzemē.\n\nPraksē vecvecāki katru darba dienu ved mazbērnus uz skolu vai bērnudārzu, gatavo siltu ēdienu un palīdz ar mājasdarbiem. Ieteicams viņus iesaistīt ģimenes lēmumos, bet nedrīkst uzlikt pārāk lielu nastu, lai nepārslogotu viņu veselību. Tipiska situācija ir, kad māte strādā maiņās, bet vecmāmiņa pieskata bērnu.\n\nSociologi uzskata, ka vecvecāku iesaiste stiprina ģimenes vienotību un palīdz bērniem labāk iepazīt savas saknes. Tāpēc jānovērtē viņu ieguldījums un regulāri pateikties par palīdzību.",
        "questions": [
            "1. Cik procenti Latvijas ģimeņu pēdējos desmit gados saņem palīdzību no vecvecākiem?",
            "2. Kāpēc vecvecāku palīdzība ir neaizstājama Latvijas ģimenēs?",
            "3. Ko vecvecāki dara katru darba dienu mazbērniem?",
            "4. Kur tas ir īpaši izplatīts?",
            "5. Ko nedrīkst darīt ar vecvecākiem?"
        ]
    },
    {
        "id": "bernu_dzimsanas_dienas",
        "title_lv": "BĒRNU DZIMŠANAS DIENAS",
        "topic": "gimene",
        "body": "Latvijā bērnu dzimšanas dienas kļūst par nozīmīgiem ģimenes notikumiem, kas pulcē vecākus, radi un draugus. Šie svētki stiprina emocionālās saites un sagādā prieku bērniem, kuri gaida dāvanas un uzmanību. Pēdējos gados arvien vairāk ģimeņu velta tiem laiku, jo tie palīdz saglabāt tradīcijas un radīt siltas atmiņas jaunajai paaudzei.\n\nPēdējos desmit gados Latvijā katru gadu dzimst aptuveni 18 000 bērnu, un to dzimšanas dienas svin ap 90 procentiem ģimeņu. Rīgā populāras ir svinības Centrāltirgū netā esošajos parkos vai batutu centros. Piemēram, oktobrī un novembrī vecāki bieži izvēlas iekštelpu vietas, lai izvairītos no aukstuma.\n\nSvinībās cep tortes ar krēmu un augļiem, dāvina rotaļlietas un rīko spēles. Nedrīkst aizmirst par veselīgu uzkodu klātbūtni, piemēram, augļiem nevis tikai saldumiem. Tipiska situācija ir kopīga dziesma \"Laimīgo dzimšanas dienu\" un svecīšu pūšana uz tortes.\n\nBērnu psihologi iesaka iekļaut radošas aktivitātes, lai bērni justos iesaistīti un ģimene pavadītu kvalitatīvu laiku. Tādējādi dzimšanas dienas veicina harmoniskas attiecības starp tuviniekiem un sagādā ilgstošu prieku.",
        "questions": [
            "1. Cik bērnu Latvijā dzimst katru gadu?",
            "2. Kāpēc Latvijā svin bērnu dzimšanas dienas?",
            "3. Kā svin bērnu dzimšanas dienas Latvijā?",
            "4. No kā gatavo tortes svinībās?",
            "5. Ko iesaka bērnu psihologi dzimšanas dienu rīkošanā?"
        ]
    },
    {
        "id": "gimenes_vakarinjas",
        "title_lv": "ĢIMENES VAKARIŅAS",
        "topic": "gimene",
        "body": "Nedēļas nogalēs daudzas Latvijas ģimenes pulcējas uz kopīgām vakariņām. Šī tradīcija stiprina saites starp tuviniekiem un ļauj dalīties ar ikdienas pieredzi. Straujā mūsdienu dzīves ritmā tas kļūst īpaši aktuāli, jo palīdz atpūsties un just piederību. Latvijā tas saistās ar senām paražām, kad visa ģimene ēda pie viena galda.\n\nPēdējos desmit gados aptaujas rāda, ka aptuveni 70 % ģimeņu Rīgā vismaz reizi nedēļā ēd vakariņas kopā. Svētdienu vakaros tas ir īpaši izplatīts, jo bērni atgriežas no pulciņiem, bet vecāki – no darba. Centrāltirgū iegādājas svaigus dārzeņus un gaļu šīm maltītēm.\n\nVakariņu sagatavošanā iesaistās visi: māte vāra zupu, tēvs cep kartupeļus, bērni klāj galdu un pilda sulas. Pie galda runā par nedēļas notikumiem un smejas. Nedrīkst izmantot viedtālruni, lai nezaudētu uzmanību sarunām. Ieteicams gatavot tradicionālos ēdienus kā auksto zupu vai pelēkos zirņus.\n\nSociologi uzsver, ka regulāras ģimenes vakariņas uzlabo emocionālo saiti un palīdz bērniem labāk mācīties. Tās ir vienkāršs veids, kā saglabāt ģimenes vienotību un tradīcijas mūsdienu straujajā pasaulē.",
        "questions": [
            "1. Cik procentu ģimeņu Rīgā ēd vakariņas kopā vismaz reizi nedēļā?",
            "2. Kāpēc vakariņas nedēļas nogalē ir īpaši aktuālas mūsdienās?",
            "3. Kā ģimenes locekļi iesaistās vakariņu sagatavošanā?",
            "4. Kādus ēdienus ieteicams gatavot vakariņām?",
            "5. Ko nedrīkst darīt pie galda vakariņu laikā?"
        ]
    },
    {
        "id": "kazu_tradicijas",
        "title_lv": "KĀZU TRADĪČIJAS",
        "topic": "gimene",
        "body": "Kāzu tradīcijas Latvijā ir svarīgas ģimenes dzīves sastāvdaļa, kas apvieno senās paražas ar mūsdienu svinībām. Tās stiprina saites starp radiem, draugiem un pēcnācējiem. Mūsdienās, kad daudzi pāri reģistrē laulību dzimtsarakstu nodaļās, tradīcijas kļūst aktuālas, lai saglabātu kultūras mantojumu un radītu prieka pilnus mirkļus visai ģimenei.\n\nPēdējos desmit gados Latvijā katru gadu noslēgtas aptuveni 8000 laulību. Biežāk tās svin vasarā, jūlijā un augustā. Vidzemē un Latgalē saglabājušās senākās tradīcijas, piemēram, Rīgā un Daugavpilī pērk kāzu maizi un ziedus tirgos. 2022. gadā tradicionālās kāzas izvēlējās 40 procenti jauno pāru.\n\nPraksē kāzas sākas ar līgavas izpirkšanu, kur draugi uzdod uzdevumus un prasa izpirkuma naudu. Līgava nēsā ziedu vainagu, kas simbolizē tīrību. Viesi mielojas ar tradicionāliem ēdieniem, piemēram, pelēkajiem zirņiem un kūkām. Nedrīkst lauzt traukus, bet jādod vecāku svētība jaunlaulātajiem.\n\nFolkloristi iesaka saglabāt kāzu tradīcijas, lai stiprinātu ģimenes pamatus un izprastu savas saknes. Tās veido ciešākas attiecības starp paaudzēm un saglabā latviešu kultūras identitāti.",
        "questions": [
            "1. Cik daudz laulību Latvijā noslēdz katru gadu pēdējos desmit gados?",
            "2. Kāpēc kāzu tradīcijas kļūst aktuālas mūsdienās?",
            "3. Kā praksē sākas kāzas ar līgavas izpirkšanu?",
            "4. Ko simbolizē ziedu vainags līgavas galvā?",
            "5. Ko iesaka folkloristi par kāzu tradīcijām?"
        ]
    },
    {
        "id": "dzive_dazdzivoklu_nama",
        "title_lv": "DAUDZSTĀVU NAMS",
        "topic": "dzivesvieta",
        "body": "Daudzdzīvokļu namos Latvijā dzīvo liela daļa iedzīvotāju, īpaši pilsētās kā Rīga un Daugavpils. Šis dzīvesveids kļuvis aktuāls urbanizācijas dēļ, kas mainījis tradicionālo lauku dzīvi. Cilvēki meklē tuvu darbu, skolas un veikalus, bet saskaras ar jauniem izaicinājumiem – kaimiņu attiecībām un kopīgu telpu uzturēšanu.\n\nPēdējos 20 gados Rīgā uzceltas tūkstošiem jaunu dzīvokļu, un aptuveni 65 procenti Latvijas iedzīvotāju dzīvo daudzdzīvokļu namos. Centrālajos rajonos, piemēram, Ķīpsalā un Purvciemā, mājas ir vecākas, būvētas padomju laikā 1960.–1980. gados. Tās bieži prasa remontu.\n\nIedzīvotāji kopīgi uztur kāpnes, liftus un pagalmus, tīrot tos regulāri. Ieteicams neizplatīt troksni vakaros pēc pulksten 22 un šķirot atkritumus. Tipiska situācija ir strīdi par autostāvvietām vai aizslēgtām kopējām durvīm, ko nedrīkst darīt bez saskaņošanas.\n\nSociologi uzskata, ka laba komunikācija ar kaimiņiem uzlabo dzīves kvalitāti daudzdzīvokļu namos. Galvenais ir piedalīties mājas sapulcēs un ievērot kopējos noteikumus, lai radītu draudzīgu un kārtīgu vidi.",
        "questions": [
            "Cik procentu Latvijas iedzīvotāju dzīvo daudzdzīvokļu namos?",
            "Kāpēc cilvēki izvēlas dzīvot daudzdzīvokļu namos?",
            "Kā iedzīvotāji uztur koplietošanas telpas?",
            "Kādos rajonos Rīgā ir vecākas mājas?",
            "Ko sociologi iesaka, lai uzlabotu dzīves kvalitāti?"
        ]
    },
    {
        "id": "lauku_maja_piemajas_darzs",
        "title_lv": "LAUKU MĀJA",
        "topic": "dzivesvieta",
        "body": "Latvijā arvien vairāk cilvēku izvēlas dzīvot lauku mājā ar piemājas dārzu. Pilsētu steiga un piesārņojums liek meklēt mieru un svaigu gaisu laukos. Īpaši tas aktuāli ģimenēm ar bērniem, kas tur iegūst pašaudzētus produktus un ir tuvāk dabai. Pēdējos gados šāda dzīve kļūst populāra visā valstī.\n\nPēdējos desmit gados aptuveni 15 procentu Latvijas iedzīvotāju pārvākušies no pilsētām uz laukiem. Populārākās vietas ir Vidzemē – piemēram, pie Siguldas – un Kurzemē, Ventspils novadā. Tur celtnes bieži būvētas no koka ar lieliem logiem dabas skatam un plašiem pagalmiem dārzam.\n\nPiemājas dārzā iedzīvotāji pavasarī sēj dārzeņus un stāda augļu kokus. Vasarā ravē nezāles, laista un novāc ražu. Speciālisti iesaka izmantot organiskos mēslojumus un kompostu, nedrīkst pārāk daudz lietot ķīmiskos līdzekļus. Ražu aizsargā ar žogiem pret meža zvēriem.\n\nLauksaimniecības eksperti uzskata, ka lauku mājas dzīve veicina veselīgu uzturu un pašpietiekamību. Tā stiprina saikni ar tradīcijām un dabu, kas Latvijā ir īpaši svarīga ikdienas labsajūtai.",
        "questions": [
            "Cik procentu iedzīvotāju pārvākušies uz laukiem pēdējos desmit gados?",
            "Kāpēc cilvēki izvēlas dzīvot lauku mājās?",
            "Kā rūpējas par piemājas dārzu vasarā?",
            "No kāda materiāla bieži būvē lauku mājas?",
            "Ko iesaka izmantot dārza mēslojumam?"
        ]
    },
    {
        "id": "dzivokla_ire_riga",
        "title_lv": "DZĪVOKĻA ĪRE RĪGĀ",
        "topic": "dzivesvieta",
        "body": "Rīgā, Latvijas lielākajā pilsētā, daudzi jaunieši, studenti un ģimenes izvēlas īrēt dzīvokļus, jo tas ļauj ātri iekārtoties darba vai mācību dēļ. Tas aktuāli tiem, kas pārvākjas no reģioniem, kur dzīvokļu pirkšana ir dārga un sarežģīta. Pareiza īres izvēle ietekmē ikdienas labsajūtu un ģimenes dzīvi.\n\nPēdējos piecos gados dzīvokļu īres cenas Rīgā pieaugušas par aptuveni 30 procentiem. Vidēji divistabu dzīvoklis Purvciema rajonā maksā 450–600 eiro mēnesī, bet Vecrīgā – līdz 900 eiro. Populāras vietas ir arī Ķengarags un Teika, kur pieejami gan jauni, gan vecāki mājokļi.\n\nĪrnieki meklē dzīvokļus sludinājumu vietnēs, piemēram, ss.lv, un vienmēr apskata tos klātienē. Jānoslēdz rakstisks līgums, jāpārbauda komunālo pakalpojumu skaitītāji un jāpieprasa nomnieka dati. Nedrīkst maksāt naudu bez čeka vai pārskaitījuma, lai izvairītos no krāpšanas.\n\nNekustamo īpašumu speciālisti iesaka salīdzināt vairākus variantus un konsultēties ar juristiem pirms līguma parakstīšanas. Tāpat ieteicams izvēlēties rajonus ar labu sabiedriskā transporta pieslēgumu, lai dzīve būtu ērta un droša.",
        "questions": [
            "Cik procentu pieaugušas īres cenas Rīgā pēdējos piecos gados?",
            "Kāpēc jaunieši Rīgā izvēlas īrēt dzīvokļus?",
            "Kā īrnieki meklē dzīvokļus Rīgā?",
            "Kurš rajons Rīgā ir populārs lētiem divistabu dzīvokļiem?",
            "Ko speciālisti iesaka darīt pirms līguma parakstīšanas?"
        ]
    },
    {
        "id": "vasarnicas_latvija",
        "title_lv": "VASARNĪCAS",
        "topic": "dzivesvieta",
        "body": "Latvijā vasarnīcas ir populāra atpūtas vieta pilsētniekiem. Vasarā daudzi Rīgas iedzīvotāji un citu pilsētu iedzīvotāji dodas uz lauku mājām, lai aizbēgtu no ikdienas steigas un sajustos tuvāk dabai. Tas stiprina ģimenes saites un palīdz atgūt spēkus. Vasarnīcu tradīcija ir sena, bet pēdējos gados kļūst arvien aktuālāka pandēmijas ietekmē.\n\nPēdējos 20 gados Latvijā ir būvētas aptuveni 40 tūkstoši jaunu vasarnīcu. Populārākās vietas ir Jūrmalā pie jūras, pie ezera Lubāna Viduslatvijā un Vidzemes mežos pie Siguldas. Rīgas iedzīvotāji bieži izvēlas vasarnīcas Mārupē vai Baltezera apkārtnē. Vidēji viena vienkārša vasarnīca maksā ap 30 tūkstošiem eiro.\n\nVasarnīcās cilvēki kopj dārzu, cep gaļu uz grila, peld ezerā vai jūrā un atpūšas svaigā gaisā. Iesaka izvēlēties vietu ar tīru ūdeni un mežu tuvumā, ierīkot saules paneļus elektrībai. Nedrīkst mest atkritumus dabā vai cirst kokus bez atļaujas. Tipiski svētkos visa ģimene pulcējas vasarnīcā.\n\nVides speciālisti iesaka būvēt ekoloģiskas vasarnīcas no koka un vietējiem materiāliem. Tādējādi saglabājam dabu un baudām veselīgu atpūtu. Vasarnīca uzlabo dzīves kvalitāti un palīdz atgūt enerģiju pilsētas ikdienai.",
        "questions": [
            "Cik daudz jaunu vasarnīcu ir būvētas Latvijā pēdējos 20 gados?",
            "Kāpēc pilsētnieki dodas uz vasarnīcām?",
            "Kā cilvēki pavada laiku vasarnīcās?",
            "Kādas vietas Latvijā ir populāras vasarnīcām?",
            "Ko iesaka vides speciālisti vasarnīcu būvēšanai?"
        ]
    },
    {
        "id": "dzivosana_mikrorajona",
        "title_lv": "MIKRORAJONI",
        "topic": "dzivesvieta",
        "body": "Daudzi Latvijas iedzīvotāji, īpaši Rīgā, izvēlas dzīvot mikrorajonos. Šāda dzīvesvieta ir aktuāla urbanizācijas laikā, jo piedāvā pieejamas cenas un ērtu infrastruktūru. Cilvēkiem patīk blakus esošie kaimiņi, kopīgās atpūtas vietas un drošības sajūta savā kopienā, kas stiprina sociālās saites.\n\nPēdējos 20 gados Rīgas mikrorajonos, piemēram, Imantā, Purvciemā un Zolitūdē, apmetušies aptuveni 500 tūkstoši iedzīvotāju. Lielākajos rajonos ir skolas, veikali un autobusu maršruti ik pēc 10–15 minūtēm. 2023. gadā Ziepniekkalna mikrorajonā uzsākta jaunu dzīvokļu būvniecība vairāk nekā 1000 vienībām.\n\nIkdienā iedzīvotāji izmanto kopīgos rotaļlaukumus, sporta laukumus un zaļās zonas atpūtai. Iedzīvotājiem iesaka apmeklēt mikrorajona sapulces, iesaistīties labiekārtošanā un sadarboties ar kaimiņiem. Nedrīkst traucēt citus ar troksni vakaros vai atstāt atkritumus nepareizās vietās, lai saglabātu kārtību.\n\nSociologi uzskata, ka aktīva līdzdalība mikrorajona dzīvē uzlabo dzīves kvalitāti un veido draudzīgu vidi. Tas palīdz risināt kopējās problēmas un stiprina kopienas garu ilgtermiņā.",
        "questions": [
            "Kuros Rīgas mikrorajonos dzīvo daudzi iedzīvotāji?",
            "Kāpēc cilvēki izvēlas dzīvot mikrorajonos?",
            "Kā iedzīvotāji izmanto kopīgās atpūtas vietas mikrorajonā?",
            "Ko nedrīkst darīt mikrorajona iedzīvotāji?",
            "Ko uzskata sociologi par aktīvu līdzdalību mikrorajona dzīvē?"
        ]
    },
    {
        "id": "atalinaty_darbs_latvija",
        "title_lv": "ATTĀLINĀTAIS DARBS",
        "topic": "darbs",
        "body": "Pēdējos gados attālinātais darbs Latvijā kļuvis arvien populārāks, īpaši pēc 2020. gada pandēmijas. Tas ļauj cilvēkiem ietaupīt laiku ceļā uz darbu, īpaši Rīgā, kur bieži ir sastrēgumi. Daudziem tas nozīmē lielāku līdzsvaru starp darbu un ģimenes dzīvi, kā arī iespēju dzīvot laukos.\n\nSaskaņā ar statistiku, aptuveni 40 procenti darbinieku Latvijā strādā attālināti vismaz daļu laika. IT nozarē Rīgā šis rādītājs sasniedz 70 procentus. 2022. gadā valdība atbalstīja šādu modeli ar nodokļu atvieglojumiem uzņēmumiem, kas ievieš attālināto darbu.\n\nPraksē darbinieki izmanto videozvanus, piemēram, Zoom vai Teams, un strādā no mājām. Jāizveido atsevišķs darba stūris ar labu gaismu un ergonomisku krēslu. Nedrīkst strādāt gultā vai virtuvē, lai saglabātu koncentrēšanos. Iesaka plānot darba dienu un ņemt īsus pārtraukumus.\n\nDarba psihologi uzskata, ka attālinātais darbs palielina produktivitāti, ja regulē komunikāciju ar kolēģiem. Speciālisti iesaka apvienot to ar reizēm klātienes sanāksmēm, lai stiprinātu komandas saites.",
        "questions": [
            "Cik procentus darbinieku Latvijā strādā attālināti vismaz daļu laika?",
            "Kāpēc attālinātais darbs kļuvis populārs Latvijā pēc 2020. gada?",
            "Kā darbinieki organizē darba vietu mājās?",
            "Kādā nozarē Rīgā attālinātais darbs ir visizplatītākais?",
            "Ko iesaka darba psihologi attālinātā darba sakarā?"
        ]
    },
    {
        "id": "skoleanu-vasaras-darbi",
        "title_lv": "SKOLĒNU VASARAS DARBI",
        "topic": "darbs",
        "body": "Vasarā daudzi skolēni Latvijā meklē darbu, lai nopelnītu kabatas naudu un iegūtu pirmo darba pieredzi. Tas palīdz jauniešiem justies neatkarīgākiem un māca atbildību. Vecāki atbalsta šādu praksi, jo bērni mācās plānot laiku un sadarboties ar citiem. Arvien vairāk ģimeņu uzskata vasaras darbu par labu sagatavošanos pieaugušo dzīvei.\n\nPēdējos desmit gados aptuveni 35 procenti vidusskolas skolēnu strādā vasaras mēnešos. Rīgā jaunieši bieži tirgo ogas Centrāltirgū vai strādā mazās kafejnīcās. Laukos Vidzemē un Latgalē lasa zemenes un avenes jūlijā un augustā. Darba devēji labprāt pieņem strādīgus skolēnus uz sezonas darbiem.\n\nSkolēni darbu meklē caur vecākiem, interneta sludinājumiem vai paziņu ieteikumiem. Tipiski darbi ir sētas kopšana, zāles pļaušana, preču izlikšana tirgū. Bērniem nedrīkst uzticēt bīstamus uzdevumus, piemēram, darbu ar smagām mašīnām. Vecākiem jāzina darba grafiks un vieta.\n\nNodarbinātības speciālisti iesaka sākt ar viegliem darbiem, lai skolēni mācītos komunikāciju un laika plānošanu. Tādējādi jaunieši iegūst prasmes nākotnei un attīsta pašpārliecinātību.",
        "questions": [
            "Cik procenti vidusskolas skolēnu strādā vasarā?",
            "Kāpēc skolēni meklē vasaras darbu?",
            "Kā skolēni meklē darbu?",
            "Kādus uzdevumus nedrīkst uzticēt bērniem?",
            "Ko iesaka nodarbinātības speciālisti skolēniem?"
        ]
    },
    {
        "id": "parkvalifikacija_pieaugusajiem",
        "title_lv": "PĀRKVALIFIKĀCIJA",
        "topic": "darbs",
        "body": "Mūsdienās Latvijā daudzi pieaugušie izvēlas pārkvalificēties, jo darba tirgus strauji mainās tehnoloģiju un ekonomikas attīstības dēļ. Tas palīdz saglabāt darbu vai atrast labāku amatu, nodrošinot ģimenei stabilitāti un labāku ienākumu. Pārkvalifikācija kļūst par ikdienas realitāti, īpaši tiem, kuri zaudējuši darbu krīžu laikā.\n\nPēdējos piecos gados aptuveni 25 procenti strādājošo Latvijā izgājuši pārkvalifikācijas kursus. Rīgā un Vidzemē šādu programmu ir visvairāk, piemēram, no pavāra uz IT speciālistu vai no šuvēja uz loģistikas darbinieku. Valsts finansē daļu kursu Nodarbinātības valsts aģentūrā.\n\nPārkvalifikācija notiek gan klātienē, gan attālināti caur akreditētām skolām. Cilvēkiem iesaka izvēlēties programmas ar prakses daļu un darba tirgus pieprasījumu. Nedrīkst izvēlēties ātrus kursus bez sertifikāta, jo tie nepalīdz atrast darbu. Tipiska situācija – māte pēc bērna kopšanas atvaļinājuma apgūst digitālās prasmes.\n\nKarjeras konsultanti uzskata, ka pārkvalifikācija ir ieguldījums nākotnē. Speciālisti iesaka sākt ar pašnovērtējumu un konsultāciju, lai izvēlētos piemērotu nozari. Tas veicina personisko izaugsmi un sabiedrības attīstību.",
        "questions": [
            "1. Cik procenti strādājošo Latvijā pēdējos piecos gados izgājuši pārkvalifikācijas kursus?",
            "2. Kāpēc pieaugušie Latvijā izvēlas pārkvalificēties?",
            "3. Kā notiek pārkvalifikācija praksē?",
            "4. Ko nedrīkst izvēlēties pārkvalifikācijai?",
            "5. Ko iesaka karjeras konsultanti, lai sāktu pārkvalifikāciju?"
        ]
    },
    {
        "id": "popular_jobs_youth",
        "title_lv": "JAUNIEŠU PROFESIJAS",
        "topic": "darbs",
        "body": "Latvijā jaunieši arvien biežāk izvēlas profesijas, kas saistītas ar tehnoloģijām, radošumu un veselības aprūpi. Tas ir aktuāli, jo darba tirgus strauji mainās, un tradicionālās profesijas vairs nenodrošina stabilu nākotni. Rīgā un citās lielpilsētās daudzi jaunieši domā par darbu, kurā var apvienot savas intereses ar labu atalgojumu un elastīgu grafiku.\n\nPēdējos pieciem gados veiktajos pētījumos konstatēts, ka aptuveni 40 procenti jauniešu Latvijā vēlas kļūt par programmētājiem vai grafiskajiem dizaineriem. Rīgā IT uzņēmumi katru gadu pieņem darbā vairāk nekā tūkstotis absolventu no tehniskajām universitātēm. Arī ārsta profesija ir populāra, īpaši meiteņu vidū, un to izvēlas ap 25 procentiem.\n\nLai apgūtu šīs profesijas, jaunieši mācās koledžās, universitātēs vai pašmācības ceļā, izmantojot tiešsaistes kursus. Karjeras centri iesaka sākt ar praksi skolā un vasaras stažēšanos uzņēmumos. Nedrīkst aizmirst svešvalodu apguvi, jo lielākā daļa darbu prasa labas angļu valodas zināšanas.\n\nKarjeras konsultanti uzsver, ka jāizvēlas profesija pēc savām interesēm un spējām, nevis tikai augstās algas dēļ. Tādējādi jaunieši būs motivēti, radoši un veiksmīgi ilgtermiņa karjerā.",
        "questions": [
            "1. Cik procenti jauniešu Latvijā vēlas kļūt par programmētājiem vai grafiskajiem dizaineriem?",
            "2. Kāpēc jaunieši izvēlas šīs profesijas?",
            "3. Kā jaunieši apgūst populārās profesijas?",
            "4. Cik daudz absolventu Rīgas IT uzņēmumi pieņem darbā katru gadu?",
            "5. Ko uzsver karjeras konsultanti par profesijas izvēli?"
        ]
    },
    {
        "id": "rokdarbi_hobijs",
        "title_lv": "ROKDARBI",
        "topic": "darbs",
        "body": "Latvijā rokdarbi kā hobijs kļūst arvien populārāks, jo ļauj cilvēkiem atpūsties pēc darba dienas un izpaust radošumu. Tas saistās ar senajām amatniecības tradīcijām, kas stiprina ģimenes saites un kultūras apziņu. Daudziem tas ir veids, kā aiziet no digitālās pasaules un radīt praktiskas, skaistas lietas savām mājām vai tuviniekiem.\n\nPēdējos desmit gados aptuveni 30 % Latvijas iedzīvotāju regulāri nodarbojas ar rokdarbjiem, saskaņā ar kultūras centra aptaujām. Rīgā populāri ir pulciņi kultūras namos, bet laukos – pašvaldību rīkotās nodarbības. Piemēram, 2023. gadā Cēsu novadā notika lielais rokdarbu festivāls ar vairāk nekā 500 dalībniekiem.\n\nRokdarbus sākt var mājās ar vienkāršiem materiāliem: dziju adīšanai, papīra ruļļiem pinumiem vai kokvilnu tamborēšanai. Iesaka izvēlēties soļos modeļus no grāmatām vai interneta, apmeklēt iesācēju kursus. Nedrīkst izmantot asus rīkus bez uzraudzības un steigties, lai izvairītos no traumām. Parasti cilvēki šuj somiņas vai aust lakatus.\n\nRokdarbu skolotāji uzskata, ka šis hobijs uzlabo garīgo veselību, mazina stresu un saglabā latviešu amatniecības prasmes. Tas ir labs veids, kā pavadīt laiku ar bērniem un ģimeni, radot unikālas dāvanas svētkos.",
        "questions": [
            "1. Kāpēc rokdarbi kā hobijs ir populāri Latvijā?",
            "2. Cik procentu Latvijas iedzīvotāju nodarbojas ar rokdarbjiem pēdējos desmit gados?",
            "3. No kādiem materiāliem var sākt rokdarbus mājās?",
            "4. Ko nedrīkst darīt, nodarbojoties ar rokdarbjiem?",
            "5. Ko uzskata rokdarbu skolotāji par šī hobija ieguvumiem?"
        ]
    },
    {
        "id": "kaiminattiecibas_daudzdzirovklu_maja",
        "title_lv": "KAIMĪŅATTIECĪBAS",
        "topic": "attiecibas",
        "body": "Daudzdzīvokļu mājās Latvijā, īpaši lielpilsētās kā Rīgā, kaimiņu attiecības ietekmē ikdienas labsajūtu. Blīva apdzīvotība rada gan draudzīgas saites, gan konfliktus par trokšņiem vai atkritumiem. Cilvēki vēlas justies droši un omulīgi savā mājā. Šī tēma kļūst aktuālāka, jo strauji augošā apdzīvotība veicina jaunas mājas celtniecību.\n\nPēdējos desmit gados Rīgā daudzdzīvokļu māju skaits palielinājies par 30 procentiem. Aptuveni 65 procenti iedzīvotāju saskārušies ar sūdzībām par trokšņiem vai autostāvvietām. Piemēram, Vecrīgā un Purvciemā bieži risināti strīdi par koplietošanas telpām un bērnu rotaļām pagalmos. Statistika liecina, ka sievietes sūdzas biežāk nekā vīrieši.\n\nPraksē kaimiņi satiekas kāpņu telpās un pagalmos. Iesaka sveicināt viens otru un palīdzēt vecākiem ļaudīm ar smagajiem iepirkumu maisiem. Nedrīkst trokšņot pēc plkst. 23.00 vai atstāt atkritumus nepareizā kārtā. Tipiska situācija ir strīds par pasta kastītēm vai velosipēdu novietošanu. Labāk risināt ar mierīgu sarunu.\n\nSociologi uzskata, ka regulāru kopīgu pasākumu rīkošana, piemēram, mājas svētki vai kopīga pagalma sakopšana, stiprina saites. Tas mazina konfliktus un rada harmonisku dzīves vidi. Galvenais ir savstarpēja cieņa un atklāta komunikācija.",
        "questions": [
            "Cik procenti iedzīvotāju Rīgā ir saskārušies ar sūdzībām?",
            "Kāpēc kaimiņu attiecības kļūst aktuālākas Latvijā?",
            "Kā kaimiņi var palīdzēt vecākiem ļaudīm?",
            "Ko nedrīkst darīt pēc plkst. 23.00?",
            "Ko iesaka sociologi saites stiprināšanai?"
        ]
    },
    {
        "id": "ka_latviesi_iepazistas",
        "title_lv": "IEPAZÍŠANĀS",
        "topic": "attiecibas",
        "body": "Latvijā iepazīšanās ar jauniem cilvēkiem ir svarīga ikdienas dzīves sastāvdaļa. Cilvēki vēlas veidot draudzīgas attiecības, jo tas palīdz justies labāk pilsētās, kur bieži valda steiga un vientulības sajūta. Tradicionāli latvieši iepazīstas personiski, nevis tikai virtuāli, lai radītu patiesas saites.\n\nPēdējos desmit gados aptuveni 65 procenti jauniešu Rīgā iepazīstas darba vietā vai caur kopīgiem draugiem. Bieži tas notiek Centrāltirgū, parkos vai Dziesmu svētku pasākumos. Oktobrī, kad sākas kultūras pasākumi, cilvēki pavada vairāk laika sabiedriskās vietās un tur satiekas.\n\nPraksē iepazīšanos sāk ar laipnu sveicienu „Labdien“ vai rokasspiedienu. Iesaka uzsākt sarunu ar neitrālu tēmu, piemēram, par laiku vai pasākumu. Nedrīkst uzreiz pāriet uz „tu“ formu, tas var šķist nepieklājīgi. Tipiska situācija ir kaimiņu tikšanās kāpņu telpā.\n\nSociologi uzskata, ka smaids un interese par otru palīdz ātri izveidot labas attiecības. Tādējādi latvieši saglabā pieklājību un tradīcijas, vienlaikus pielāgojoties mūsdienu ritmam.",
        "questions": [
            "Kur Rīgā bieži iepazīstas latvieši?",
            "Kāpēc iepazīšanās Latvijā ir svarīga?",
            "Kā iesaka uzsākt iepazīšanos?",
            "Ko nedrīkst darīt iepazīšanās sākumā?",
            "Ko sociologi iesaka, lai ātri izveidotu labas attiecības?"
        ]
    },
    {
        "id": "davanu_pasniegsana_kaiminjiem",
        "title_lv": "DĀVANAS KAIMIŅIEM",
        "topic": "attiecibas",
        "body": "Latvijā dāvanu pasniegšana ir svarīga tradīcija attiecību veidošanā ar kaimiņiem un paziņām. Tā palīdz uzturēt labas kaimiņu saites un stiprina kopienas sajūtu. Īpaši aktuāli tas ir svētkos, piemēram, Ziemassvētkos vai Jaungadā, kad cilvēki izrāda pieklājību un uzmanību viens pret otru. Tas veicina draudzīgu sadzīvošanu.\n\nPēdējos desmit gados aptuveni 70 % Latvijas iedzīvotāju, īpaši Rīgā un citās lielākajās pilsētās, dāvinājuši kaimiņiem mazas dāvanas. Populāras ir pašgatavotas cepijas vai Centrāltirgū iegādātas konfektes. Laukos jaunie kaimiņi svin pārvākšanos ar namniekiem vai ziediem.\n\nPraksē dāvanu rūpīgi iesaiņo krāsainā papīrā un pasniedz ar abām rokām, smaidot un izsakot labus vārdus. Nedrīkst dāvināt asus priekšmetus vai pulksteni, jo tas simbolizē šķiršanos. Tipiskas situācijas ir ciemošanās vai svētku apsveikums.\n\nSociologi un etnografi iesaka saglabāt šīs tradīcijas, jo tās stiprina savstarpējo cieņu un uzticēšanos. Tādējādi tiek veidotas noturīgas kaimiņu attiecības un saglabāts latviešu viesmīlības gars.",
        "questions": [
            "1. Kur Latvijā bieži dāvina kaimiņiem mazas dāvanas?",
            "2. Kāpēc nedrīkst dāvināt asus priekšmetus vai pulksteni?",
            "3. Kā pasniedz dāvanu?",
            "4. Ko dara ar dāvanu pirms pasniegšanas?",
            "5. Ko iesaka sociologi un etnografi par dāvanu tradīcijām?"
        ]
    },
    {
        "id": "palidziba_draugiem_gruta_bridi",
        "title_lv": "DRAUGU PALĪDZĪBA",
        "topic": "attiecibas",
        "body": "Latvijā draudzība palīdz pārvarēt dzīves grūtības, piemēram, slimības, darba zaudēšanu vai ģimenes krīzi. Tas ir aktuāli pēdējos gados, kad pandēmija un ekonomiskās problēmas palielināja stresu. Palīdzība draugiem stiprina emocionālās saites un mazina vientulības sajūtu sabiedrībā, kur ritms kļūst ātrāks.\n\nPēdējos desmit gados aptuveni 65 procenti Latvijas iedzīvotāju ir saņēmuši palīdzību no draugiem krīzes brīžos. Rīgā pēc 2020. gada pandēmijas draugi bieži piegādāja pārtiku vai auklēja bērnus. Oktobrī un novembrī, kad saaukstēšanās slimības pieaug, palīdzības zvanu skaits dubultojas.\n\nPraksē palīdzēt var zvanot, klausoties drauga rūpes, vai aizvedot uz ārstu. Var palīdzēt ar mājas darbiem vai meklēt darba vakances kopā. Nedrīkst solīt palīdzību un to nepildīt vai kritizēt drauga lēmumus. Tipiska situācija ir darba zaudēšana, kad draugi organizē atbalsta tikšanās.\n\nPsihologi uzskata, ka regulāra palīdzība veido uzticamas attiecības. Speciālisti iesaka sākt ar mazām darbībām, lai stiprinātu saites un mazinātu vientulību ilgtermiņā.",
        "questions": [
            "Cik procenti Latvijas iedzīvotāju saņēmuši palīdzību no draugiem pēdējos desmit gados?",
            "Kāpēc palīdzība draugiem stiprina emocionālās saites?",
            "Kā var palīdzēt draugam ar mājas darbiem vai darba meklēšanu?",
            "Ko nedrīkst darīt, solot palīdzību draugam?",
            "Ar ko speciālisti iesaka sākt palīdzību draugiem?"
        ]
    },
    {
        "id": "pieklajibas_frazes_ikdiena",
        "title_lv": "PIEKLĀJĪBAS FRĀZES",
        "topic": "attiecibas",
        "body": "Latvijā ikdienas saskarsmē ar citiem cilvēkiem pieklājības frāzes palīdz veidot un uzturēt labas attiecības. Kaimiņi, veikala pārdevēji un paziņas novērtē laipnus vārdus, kas rada siltumu. Pēdējos desmit gados, kad strauji attīstās digitālā komunikācija, tiešā saruna kļūst retāka, tāpēc šādas frāzes iegūst lielāku nozīmi sabiedrībā.\n\nRīgā un citās pilsētās aptuveni 70 % iedzīvotāju katru dienu lieto frāzes kā \"Labdien!\" un \"Paldies!\". Saskaņā ar sociologu pētījumu, pagājušajā gadā veikto, 85 % respondentu uzskata, ka pieklājība uzlabo kaimiņu attiecības. Centrāltirgū vai kāpņu telpās šīs frāzes dzird ikdienā, īpaši ziemas mēnešos.\n\nPraksē satiekot kaimiņu rītā, saki \"Labrīt!\" vai \"Labdien!\". Veikalā lūdzot palīdzību, lieto \"Lūdzu, vai varat parādīt?\". Nedrīkst aizmirst \"Atvainojiet!\", ja nejauši uzduries citam. Autobusā izejot, pateicies šoferim \"Paldies!\". Šīs frāzes padara komunikāciju gludu un patīkamu.\n\nSociologi iesaka regulāri lietot pieklājības frāzes, lai stiprinātu sociālās saites. Speciālisti uzsver, ka vecākiem jāmāca bērnus no mazotnes, tādējādi saglabājot Latvijas tradicionālo laipnību pret citiem.",
        "questions": [
            "1. Aptuveni cik procentu iedzīvotāju katru dienu lieto frāzes kā \"Labdien!\" un \"Paldies!\"?",
            "2. Kāpēc pēdējos desmit gados pieklājības frāzes iegūst lielāku nozīmi?",
            "3. Kā sveicināt kaimiņu rītā?",
            "4. Ko nedrīkst aizmirst, ja nejauši uzduries citam cilvēkam?",
            "5. Ko iesaka sociologi darīt ar bērniem attiecībā uz pieklājības frāzēm?"
        ]
    },
    {
        "id": "dziesmu_deju_svetki",
        "title_lv": "DZIESMU UN DEJU SVĒTKI",
        "topic": "kultura",
        "body": "Dziesmu un deju svētki ir lielākais latviešu kultūras notikums, kas notiek ik pēc pieciem gadiem. Tie apvieno desmitiem tūkstošu cilvēku no visas Latvijas un ārzemēm, radot spēcīgu nacionālo vienotības sajūtu. Šie svētki stiprina latviešu identitāti un saglabā gadsimtu vecas tradīcijas, kas iekļautas UNESCO sarakstā.\n\nPirmie Dziesmu svētki notika 1873. gadā Rīgā, un kopš tā laika tie kļuvuši par tradīciju. Pēdējoreiz, 2023. gadā, svētkos piedalījās aptuveni 43 tūkstoši dalībnieku. Koncerti un deju uzvedumi risinās Mežaparkā, Daugavas stadionā un VEF kultūras pilī.\n\nDalībnieki gadiem ilgi gatavojas, apmeklējot mēģinājumus kolektīvos. Cilvēki dzied koros, dejo folkloras ansamblos un ģimenēs māca dejas bērniem. Iesaka sākt gatavošanos laikus un piedalīties vietējos kolektīvos, bet nedrīkst aizmirst tradicionālos tērpus.\n\nKultūras vēsturnieki uzskata, ka šie svētki ir svarīgi, lai saglabātu latviešu valodu un kultūru mūsdienās. Tie veicina sabiedrības saliedētību un iedvesmo jauno paaudzi turpināt tradīcijas.",
        "questions": [
            "1. Kad notika pirmie Dziesmu svētki?",
            "2. Kāpēc kultūras vēsturnieki uzskata, ka šie svētki ir svarīgi?",
            "3. Kā dalībnieki gatavojas svētkiem?",
            "4. Kur 2023. gadā notika koncerti un deju uzvedumi?",
            "5. Ko iesaka darīt, lai piedalītos svētkos?"
        ]
    },
    {
        "id": "latvijas_muzikas_skatuve",
        "title_lv": "LATVIJAS MŪZIKAS SKATUVE",
        "topic": "kultura",
        "body": "Latvijā mūzika ir neatņemama kultūras dzīves sastāvdaļa. Tā apvieno dažādu paaudžu cilvēkus koncertos un festivālos, stiprina nacionālo identitāti un sniedz emocionālu pacēlumu. Pēdējos desmit gados jauniešu interese par vietējiem māksliniekiem ievērojami pieaugusi, jo dzīvā mūzika palīdz aizmirst ikdienas rūpes un baudīt kopīgu piedzīvojumu.\n\nRīgā katru gadu notiek vairāk nekā 1500 koncertu zālēs kā Arēna Rīga un Splendid Palace. Populārais festivāls Positivus Salacgrīvā kopš 2007. gada pulcē aptuveni 30 000 apmeklētāju. Liepājas pilsētas dzimšanas dienā uzstājas vairāki desmiti vietējo un ārzemju mūziķu, kas piesaista tūkstošiem iedzīvotāju.\n\nApmeklētāji biļetes iegādājas internetā vai kasēs iepriekš, lai izvairītos no rindām. Ierodas savlaicīgi, paņem ērtu apģērbu un ūdeni. Nedrīkst nest stikla taru vai aizliegtas vielas, pretējā gadījumā netiek iekšā. Ģimenēm iesaka izvēlēties dienas koncertus ar bērniem draudzīgiem repertuāriem.\n\nKultūras speciālisti uzskata, ka regulāra koncertu apmeklēšana bagātina emocionālo dzīvi. Viņi iesaka atbalstīt vietējos māksliniekus, iegādājoties ierakstus un apmeklējot mazākus klubus. Tas palīdz Latvijas mūzikas skatuvei attīstīties un stiprina sabiedrības saliedētību.",
        "questions": [
            "Cik koncertu gadā notiek Rīgā?",
            "Kāpēc jauniešu interese par vietējiem māksliniekiem pieaugusi?",
            "Kā iegādājas biļetes uz koncertiem?",
            "Ko nedrīkst nest uz koncertiem?",
            "Ko iesaka kultūras speciālisti, lai atbalstītu vietējos māksliniekus?"
        ]
    },
    {
        "id": "teatra_apmeklesana",
        "title_lv": "TEĀTRA APMEKLĒŠANA",
        "topic": "kultura",
        "body": "Latvijā teātra apmeklēšana ir iemīļota brīvā laika pavadīšana, īpaši aukstajos mēnešos. Cilvēki dodas uz izrādēm, lai baudītu mākslu, atpūstos no ikdienas un stiprinātu kultūras identitāti. Teātris savieno paaudzes – vecāki ved bērnus uz bērnu izrādēm, bet jaunieši interesējas par laikmetīgām lugām. Tas rada kopīgu pieredzi un emocionālu tuvumu.\n\nPēdējos desmit gados Rīgas teātros apmeklētāju skaits pieaudzis par aptuveni 25 procentiem. Populārākās vietas ir Dailes teātris, Jaunais Rīgas teātris un Latvijas Nacionālā opera. Sezona parasti sākas septembrī un ilgst līdz maijam. 2023. gadā Rīgā notika vairāk nekā 1200 izrāžu.\n\nBiļetes uz izrādēm iegādājas internetā vai kasēs iepriekš, lai izvairītos no rindām. Ierodies pusstundu pirms sākuma, lai atrastu vietu un noliktu somas. Izrādes laikā nedrīkst fotografēt, runāt vai ēst konfektes. Pēc izrādes var palikt aplausos un satikt aktierus.\n\nTeātra speciālisti iesaka regulāri apmeklēt izrādes, jo tas attīsta iztēli un empātiju. Tas bagātina dvēseli un stiprina sociālās saites ģimenē un draugu lokā.",
        "questions": [
            "1. Kurās Rīgas teātros notiek izrādes?",
            "2. Kāpēc cilvēki Latvijā apmeklē teātri?",
            "3. Kā iegādāties biļetes uz teātra izrādi?",
            "4. Cik ilgi pirms izrādes sākuma ierodies teātrī?",
            "5. Ko iesaka teātra speciālisti darīt regulāri?"
        ]
    },
    {
        "id": "latvijas_muzeji",
        "title_lv": "LATVIJAS MUZEJI",
        "topic": "kultura",
        "body": "Latvijā muzeji ir svarīga kultūras dzīves sastāvdaļa. Tie ļauj iepazīt valsts bagāto vēsturi, mākslu un etniskās tradīcijas. Arvien vairāk iedzīvotāju un tūristu apmeklē muzejus, lai stiprinātu nacionālo identitāti un lepnumu par mantojumu. Pandēmijas laikā apmeklējumi samazinājās, bet tagad tie strauji atjaunojušies.\n\nLatvijā darbojas vairāk nekā 120 muzeju un filiāļu. Rīgā atrodas Latvijas Nacionālais mākslas muzejs ar gleznām no 19. gadsimta, bet ārpus galvaspilsētas – Siguldas pils muzejs. Pēdējos piecos gados apmeklētāju skaits pieaudzis par 30 procentiem, īpaši vasarā un oktobrī.\n\nApmeklējot muzejus, cilvēki iegādājas biļetes pie ieejas vai tiešsaistē. Ieteicams izmantot audiogidus vai grupu ekskursijas. Nedrīkst fotografēt ar zibspulgu un nest ēdienu telpās. Ģimenēm un skolēniem ir atlaides, kas atvieglo apmeklējumus.\n\nMuzeju speciālisti un vēsturnieki uzskata, ka regulāri apmeklējumi veicina izglītību un patriotismu. Viņi iesaka vismaz reizi gadā izvēlēties kādu muzeju, lai labāk izprastu Latvijas pagātni un nākotnes iespējas.",
        "questions": [
            "Cik muzeju un filiāļu darbojas Latvijā?",
            "Kāpēc iedzīvotāji un tūristi apmeklē Latvijas muzejus?",
            "Kā iegādāties biļetes uz muzejiem?",
            "Kādas atlaides ir pieejamas muzejos?",
            "Ko iesaka muzeju speciālisti un vēsturnieki?"
        ]
    },
    {
        "id": "latviesu_kino_musdienas",
        "title_lv": "LATVIEŠU KINO",
        "topic": "kultura",
        "body": "Latviešu kino mūsdienās piedzīvo uzplaukumu, jo tas stāsta par mūsu dzīvi, vēsturi un sapņiem. Cilvēki to mīl, jo var redzēt savus stāstus uz ekrāna. Latvijā kino saista kopā dažādas paaudzes kinoteātros un festivālos. Tas stiprina nacionālo identitāti laikmetā, kad pieejams pasaules kino.\n\nPēdējos desmit gados Latvijā uzņemtas vairāk nekā 60 pilnmetrāžas spēlfilmas. Populāras ir filmas kā \"Dvēseļu putenis\" un \"Tēvs Nakts\". Rīgā, \"Splendid Palace\" kinoteātrī, katru gadu notiek starptautiskais kinofestivāls \"Riga IFF\". 2023. gadā latviešu filmas noskatījās aptuveni 400 tūkstoši skatītāju.\n\nSkatītāji var apmeklēt seansus kinoteātros Rīgā vai citās pilsētās, kā arī skatīties filmas tiešsaistē Nacionālā kino centra platformā. Iesaka iegādāties biļetes iepriekš, jo populāras filmas ātri izpārdodas. Nedrīkst izmantot pirātiskas kopijas, labāk atbalstīt radošos kolektīvus. Bērniem piemērotas animācijas no \"Baltijas animācijas studijas\".\n\nKinovēsturnieki uzskata, ka jāatbalsta vietējais kino, apmeklējot seansus un piedaloties diskusijās. Tas palīdz saglabāt latviešu kultūru un iedvesmo jaunos māksliniekus. Tādējādi kino kļūst par tilbu starp paaudzēm un pasauli.",
        "questions": [
            "1. Cik daudz pilnmetrāžas spēlfilmu uzņemtas Latvijā pēdējos desmit gados?",
            "2. Kāpēc latviešu kino stiprina nacionālo identitāti?",
            "3. Kā skatītāji var noskatīties latviešu filmas?",
            "4. Kāds kinoteātris Rīgā rīko starptautisko kinofestivālu \"Riga IFF\"?",
            "5. Ko iesaka kinovēsturnieki vietējā kino atbalstam?"
        ]
    },
    {
        "id": "pirts_tradicija_latvija",
        "title_lv": "PIRTS TRADĪCIJA",
        "topic": "brivais_laiks",
        "body": "Pirts Latvijā ir senākā brīvā laika pavadīšanas tradīcija, kas apvieno atpūtu, veselības uzlabošanu un sabiedrisko sazināšanos. Mūsdienās daudzi to izvēlas kā relaksācijas veidu pēc darba nedēļas. Īpaši ziemā pirts kļūst par mājīgu vietu ģimenēm un draugiem, stiprinot emocionālās saites.\n\nPēdējos desmit gados Latvijā būvēti vairāki tūkstoši jaunu privāto piršu, bet publisko piršu Rīgā un Jūrmalā apmeklē aptuveni 80 tūkstošus cilvēku gadā. Tradīcija cēlusies no senajiem latviešiem un līviem, un kopš 2018. gada tā oficiāli atzīta par nemateriālo kultūras mantojumu.\n\nPirtī cilvēki sasildās karstā tvaikā, berzējas ar ozola vai bērzu slotiņām, pēc tam atvelkas vēsā gaisā vai baseinā. Iesaka dzert daudz ūdens, pavadīt 10–15 minūtes vienā ciklā un ne vairāk kā trīs reizes. Nedrīkst iet pirtī tukšā dūšā vai slimojot.\n\nĀrsti iesaka regulāru pirts apmeklējumu imunitātes stiprināšanai un stresa mazināšanai. Vēsturnieki uzsver, ka šī tradīcija palīdz saglabāt latviešu kultūras identitāti un sociālās saites.",
        "questions": [
            "1. Cik tūkstošus cilvēku gadā apmeklē publisko piršu Rīgā un Jūrmalā?",
            "2. Kāpēc mūsdienās daudzi izvēlas pirti brīvā laika pavadīšanai?",
            "3. Kā notiek pirts procedūra Latvijā?",
            "4. Ar ko berzējas pirtī?",
            "5. Ko iesaka ārsti par pirts apmeklējumu?"
        ]
    },
    {
        "id": "makskeereshana_vasara",
        "title_lv": "MAKŠĶERĒŠANA VASARĀ",
        "topic": "brivais_laiks",
        "body": "Vasarā daudzi latvieši brīvo laiku pavada makšķerējot pie upēm un ezeriem. Tas ir populārs atpūtas veids, kas palīdz atpūsties svaigā gaisā, stiprina ģimenes saites un saglabā senas tradīcijas. Latvijā makšķerēšana kļūst arvien aktuālāka, jo cilvēki meklē mieru no ikdienas steigas un tuvāk iepazīst dabu.\n\nPēdējos desmit gados makšķernieku skaits Latvijā pieaudzis līdz aptuveni 200 tūkstošiem. Populārākās vietas ir Daugava Rīgā, Lubāns Vidzemē un Engure pie jūras. Sezona sākas maijā un ilgst līdz septembrim, visaktīvākais periods ir jūlijā un augustā, kad zivis barojas intensīvi.\n\nMakšķerēšanas praksē cilvēki izvēlas klusu vietu krastā, sagatavo makšķeri ar āķiem un ēsmu, piemēram, sliekām vai maizītēm. Iesaka ņemt līdzi makšķerēšanas atļauju, nelauzt krasta zarus un atlaist atpakaļ ūdenī mazās zivis. Rītausmā vai vakarā ezera malā pulcējas gan pieredzējuši, gan iesācēji.\n\nZivsaimniecības speciālisti iesaka ievērot noteikumus, lai saglabātu zivju populāciju un ūdeņu tīrību. Makšķerēšana veicina veselīgu dzīvesveidu, māca pacietību un palīdz justies sasaistītiem ar dabu.",
        "questions": [
            "Cik daudz makšķernieku ir Latvijā pēdējos desmit gados?",
            "Kāpēc vasarā daudzi latvieši izvēlas makšķerēšanu?",
            "Kā sagatavojas makšķerēšanai krastā?",
            "Kādu ēsmu izmanto makšķerēšanai?",
            "Ko iesaka zivsaimniecības speciālisti makšķerēšanas laikā?"
        ]
    },
    {
        "id": "pastaigas_mezā",
        "title_lv": "PASTAIGAS MEŽĀ",
        "topic": "brivais_laiks",
        "body": "Latvijā meži aizņem vairāk nekā pusi valsts teritorijas, tāpēc pastaigas tajos ir populārs brīvā laika pavadīšanas veids daudziem iedzīvotājiem. Cilvēki no pilsētas steigas meklē atpūtu, svaigo gaisu un tuvāku saskari ar dabu. Īpaši aktuālas šādas pastaigas kļuvušas pēdējos gados, kad pieaudzis interese par veselīgu dzīvesveidu.\n\nSaskaņā ar Vides aizsardzības un reģionālās attīstības ministrijas datiem, pēdējos 10 gados mežu apmeklētāju skaits Latvijā palielinājies par 40 procentiem. Populārākās vietas ir Gaujas nacionālais parks, kur katru gadu pastaigas dodas aptuveni 500 tūkstoši cilvēku, un Rīgas apkārtnes meži, piemēram, Mežaparks un Ķemeri.\n\nPastaigās mežā ieteicams vilkt ērtus apavus, paņemt līdzi ūdeni, karti un telefonu. Cilvēki novēro putnus, vāc ogas vai sēnes, elpo svaigo gaisu pa takām. Nedrīkst plūkt retās puķes, traucēt dzīvniekus vai novirzīties no maršrutiem, lai neapmaldītos.\n\nĀrsti iesaka regulāras pastaigas mežā vismaz 30 minūtes dienā, lai uzlabotu garīgo veselību un imunitāti. Ekologi uzsver, ka tas palīdz mācīt bērnus mīlēt dabu un saprast tās nozīmi ilgtspējīgā dzīvesveidā.",
        "questions": [
            "1. Par cik procentiem pieaudzis mežu apmeklētāju skaits Latvijā pēdējos 10 gados?",
            "2. Kāpēc cilvēki dodas pastaigās mežā?",
            "3. Ko ieteicams paņemt līdzi pastaigās mežā?",
            "4. Kuras ir populārākās vietas pastaigām Latvijā?",
            "5. Cik ilgi dienā ārsti iesaka pastaigas mežā?"
        ]
    },
    {
        "id": "brivpratigais_darbs",
        "title_lv": "BRĪVPRĀTĪGAIS DARBS",
        "topic": "brivais_laiks",
        "body": "Brīvprātīgais darbs Latvijā kļūst arvien populārāks, jo ļauj cilvēkiem pavadīt brīvo laiku noderīgi un palīdzēt sabiedrībai. Daudzi to izvēlas, lai justos noderīgi, satiktu jaunus cilvēkus un risinātu sociālās problēmas, piemēram, vientulību vai vides piesārņojumu. Tas stiprina kopības sajūtu valstī, kurā ik gadu notiek daudzi labdarības pasākumi.\n\nPēdējos piecos gados aptuveni 25 procenti Latvijas iedzīvotāju iesaistījušies brīvprātīgajā darbā. Rīgā populāras ir akcijas Centrāltirgū un parkos, savukārt Liepājā un Daugavpilī darbojas vietējās organizācijas. Oktobrī un novembrī bieži vāc ziedojumus bērnu slimnīcām, piemēram, Ziedot.lv kampaņu ietvaros.\n\nPraksē brīvprāti palīdz veciem ļaudīm pansionātos, vāc atkritumus mežos vai māca bērnus lasīt bibliotēkās. Iesaka sākt ar dažām stundām nedēļā un izvēlēties interesējošu jomu. Nedrīkst uzņemties pārāk daudz pienākumu, lai nepārguru.\n\nSociologi uzskata, ka brīvprātīgais darbs uzlabo garīgo veselību un veicina sabiedrības solidaritāti. Speciālisti iesaka ikvienam vismaz reizi gadā piedalīties kādā akcijā, lai stiprinātu kopienu.",
        "questions": [
            "1. Cik procenti Latvijas iedzīvotāju pēdējos piecos gados iesaistījušies brīvprātīgajā darbā?",
            "2. Kāpēc cilvēki Latvijā izvēlas brīvprātīgo darbu?",
            "3. Kā praksē darbojas brīvprāti Rīgā un citās pilsētās?",
            "4. Ko nedrīkst darīt, iesaistoties brīvprātīgajā darbā?",
            "5. Ko speciālisti iesaka ikvienam darīt vismaz reizi gadā?"
        ]
    },
    {
        "id": "gramatu_lasisana_vakos",
        "title_lv": "VAKARA LASĪŠANA",
        "topic": "brivais_laiks",
        "body": "Brīvajā laikā vakaros daudzi latvieši izvēlas lasīt grāmatas. Pēc garās darba dienas tas palīdz atpūsties, mazināt stresu un bagātināt zināšanas. Latvijā lasīšana kļuvusi par populāru hobiju, īpaši Rīgā un citās pilsētās, kur bibliotēkas piedāvā plašu grāmatu klāstu. Šī nodarbošanās stiprina ģimenes saites un veicina emocionālo labsajūtu.\n\nPēdējos desmit gados Latvijā grāmatu lasīšanas popularitāte pieaugusi par 25 procentiem. Rīgas Centrālajā bibliotēkā katru gadu reģistrējas aptuveni 120 000 lasītāju. Oktobrī un novembrī notiek akcija \"Lasām vakaros\", kurā piedalās tūkstošiem iedzīvotāju no visas valsts.\n\nVakara lasīšana parasti notiek mājās pie ērtas lampas vai dīvāna. Cilvēki iesaka sākt ar vieglām grāmatām un lasīt 20–30 minūtes pirms gulētiešanas. Nedrīkst lasīt mobilā telefona ekrānā, jo tas kaitē acīm un traucē iemigt. Tipiska situācija ir ģimenes locekļi, kas katrs lasa savu grāmatu.\n\nPsihologi uzskata, ka regulāra vakara lasīšana uzlabo miegu, mazina stresu un attīsta iztēli. Tā ir veselīga alternatīva sociālajiem tīkliem. Speciālisti iesaka katram atrast laiku grāmatām ikdienā, lai bagātinātu brīvo laiku.",
        "questions": [
            "Par cik procentiem pieaudzis grāmatu lasīšanas popularitāte Latvijā pēdējos desmit gados?",
            "Kāpēc latvieši vakaros izvēlas lasīt grāmatas?",
            "Kā notiek vakara lasīšana mājās?",
            "Ko nedrīkst darīt lasīšanas laikā vakaros?",
            "Ko uzskata psihologi par vakara lasīšanas ietekmi?"
        ]
    },
    {
        "id": "hokejs_latvija",
        "title_lv": "HOKEJS LATVIJĀ",
        "topic": "sports",
        "body": "Hokejs Latvijā ir populārs ziemas sports, kas apvieno ātrumu, spēku un komandas darbu. Tas kļūst īpaši aktuāls aukstajā sezonā, kad ledus laukumi piepilda ar spēlētājiem un skatītājiem. Daudziem tas ir vaļasprieks, kas stiprina draudzību, nacionālo lepnumu un prieku par Latvijas izlases panākumiem Pasaules čempionātos.\n\nLatvijā hokeja tradīcijas ir senas, un Rīgas Olimpiskajā sporta centrā notiek \"Dinamo Rīga\" spēles, kurās pēdējos 10 gados vidēji apmeklē 7000 skatītāju uz maču. Amatieru līgās piedalās aptuveni 5000 spēlētāju visā valstī. Oktobrī un novembrī uzsāk sezonu vairāk nekā 100 komandas.\n\nLai sāktu nodarboties ar hokeju, jāiegādājas slidas, nūja, ķivere un aizsarglīdzekji. Treniņi notiek ledus hallēs Rīgā, Jelgavā un Daugavpilī, bieži vakaros. Speciālisti iesaka pievienoties amatieru grupām un trenēties divas reizes nedēļā. Nedrīkst spēlēt bez pilna aprīkojuma.\n\nSporta treneri uzskata, ka hokejs veicina fizisko izturību un disciplīnu. Regulāra nodarbošanās ar to palīdz uzturēt veselību un stiprina kopienu. Ikviens var atrast sev piemērotu veidu, kā baudīt šo aizraujošo sportu.",
        "questions": [
            "1. Kur Latvijā notiek \"Dinamo Rīga\" spēles?",
            "2. Kāpēc hokejs Latvijā ir aktuāls ziemā?",
            "3. Ko nepieciešams iegādāties, lai sāktu nodarboties ar hokeju?",
            "4. Cik daudz spēlētāju piedalās amatieru līgās Latvijā?",
            "5. Ko iesaka sporta treneri par hokeja ieguvumiem?"
        ]
    },
    {
        "id": "skriesana_valasprieks",
        "title_lv": "SKRIEŠANA",
        "topic": "sports",
        "body": "Latvijā skriešana kļuvusi par vienu no populārākajiem vaļaspriekiem. Tā palīdz uzturēt fizisko formu, mazina stresu un stiprina veselību ikdienas steigā. Daudzi to izvēlas kā vienkāršu veidu aktīvai atpūtai parkos vai mežos. Pilsētas iedzīvotāji novērtē iespēju skriet rītos vai vakaros, baudot svaigu gaisu un dabas skatus.\n\nPēdējos desmit gados skriešanas dalībnieku skaits Latvijā dubultojies. Rīgas maratonā 2023. gadā startēja vairāk nekā 12 tūkstoši cilvēku. Aptuveni 35 procenti rīdzinieku skrien vismaz divas reizes nedēļā. Populāras trases ir Mežaparks, Antakalns un Jūrmalas pludmales.\n\nPraksē skrējēji sāk ar lēnu tempu, izvēloties ērtus apavus un elpojošas drēbes. Svarīgi iesildīties piec minūtes un izstaipīties pēc treniņa. Nedrīkst skriet tukšā dūšā vai uz cietā asfalta katru dienu, lai nesabojātu ceļgalus. Daudzi klausās mūziku motivācijai.\n\nSporta ārsti iesaka skriešanu kā pieejamu veidu sirds un plaušu stiprināšanai. Tā uzlabo garastāvokli un veicina veselīgu dzīvesveidu bez lieliem izdevumiem. Regulāra prakse nes labumu ikvienā vecumā.",
        "questions": [
            "Cik dalībnieku startēja Rīgas maratonā 2023. gadā?",
            "Kāpēc iedzīvotāji izvēlas skriešanu kā vaļasprieku?",
            "Kā sagatavoties skrējienam praksē?",
            "Uz kādas virsmas nedrīkst skriet katru dienu?",
            "Ko iesaka sporta ārsti par skriešanas ieguvumiem?"
        ]
    },
    {
        "id": "senu_lasisana_rudeni",
        "title_lv": "SĒŅU LASEŠANA",
        "topic": "sports",
        "body": "---\nRudens Latvijā ir īstais laiks sēņu lasīšanai. Daudzi iedzīvotāji, īpaši no pilsētām, dodas uz mežiem, lai savāktu ēdamās sēnes. Šis vaļasprieks apvieno fizisko aktivitāti svaigā gaisā, atpūtu ar ģimeni un senās tradīcijas. Tas palīdz atjaunot spēkus un stiprina saites ar dabu.\n\nSēņu sezona kulminē septembrī un oktobrī, kad pēc lietus mežos parādās baravikas, gailenes un eversis. Populārākās vietas ir meži ap Rīgu, Vidzemē un Latgalē. Pēdējos desmit gados lasītāju skaits pieaudzis par aptuveni 30 procentiem. Centrāltirgū katru rudeni pārdod tūkstošiem kilogramu svaigu sēņu.\n\nSēņu lasīšanā izmanto grozu, nazi un noteicēju grāmatu. Meklē sēnes saulainos meža stūros pēc lietus. Nekad nelasi nezināmas sugas, īpaši indīgās dzeltenās dubultnieces, kas izskatās līdzīgas vaivarkām. Labāk lasīt grupās un konsultēties ar pieredzējušiem.\n\nMikologi iesaka apmeklēt sēņu izstādes un kursus, lai iemācītos pareizi atpazīt sugas. Sēņu lasīšana veicina veselīgu uzturu un izpratni par meža ekosistēmu, bet prasa zināšanas un piesardzību.\n---",
        "questions": [
            "1. Kad kulminē sēņu sezona?",
            "2. Kāpēc sēņu lasīšana stiprina saites ar dabu?",
            "3. Kādus priekšmetus izmanto sēņu lasīšanā?",
            "4. No kurām sēnēm jāuzmanās lasot?",
            "5. Ko iesaka mikologi, lai pareizi atpazītu sēnes?"
        ]
    },
    {
        "id": "darzkopiba_kak_atputa",
        "title_lv": "DĀRZKOPĪBA",
        "topic": "sports",
        "body": "Dārzkopība kļuvusi par populāru atpūtas veidu Latvijā. Pilsētnieki, kuri ikdienā strādā birojos, meklē iespēju atpūsties svaigā gaisā un aizmirst par ikdienas stresu. Pēdējos gados daudzi atklājuši prieku strādāt savos mazajos dārziņos vai pat uz balkoniem. Tas palīdz savienoties ar dabu un gūt gandarījumu par pašu audzēto ražu.\n\nPēdējos desmit gados aptuveni 60 % Latvijas iedzīvotāju nodarbojušies ar dārzkopību. Rīgā populāri ir kopdārzi Uzvaras parkā un pie Centrāltirgus. Jau aprīlī cilvēki pērk sēklas un stādus tirgos, lai vasarā iegūtu svaigus dārzeņus un zaļumus no savas zemes.\n\nPraksē dārzkopība ietver regulāru ravēšanu, laistīšanu un vieglu mēslošanu. Iesaka sākt ar viegli audzējamām kultūrām, piemēram, redīsiem, salātiem un dillēm. Nedrīkst izmantot ķīmiskos līdzekļus, labāk izvēlēties dabiskus aizsardzības veidus pret kaitēkļiem. Ģimenes brīvdienās kopīgi strādā dārzā.\n\nĀrsti un dārzkopības speciālisti uzskata, ka dārzkopība ir lieliska fiziska aktivitāte un stresa mazinātājs. Tā uzlabo gan garīgo, gan fizisko veselību un dod iespēju iegūt svaigu pārtiku. Visi var to pamēģināt pat mazā mērogā.",
        "questions": [
            "Cik procentu Latvijas iedzīvotāju pēdējos desmit gados nodarbojušies ar dārzkopību?",
            "Kāpēc pilsētnieki nodarbojas ar dārzkopību?",
            "Ar kādām kultūrām iesaka sākt dārzkopību?",
            "Kur Rīgā ir populāri kopdārzi?",
            "Ko uzskata ārsti un dārzkopības speciālisti par dārzkopību?"
        ]
    },
    {
        "id": "dabas_fotografesana",
        "title_lv": "DABAS FOTOGRAFĒŠANA",
        "topic": "sports",
        "body": "NOSAUKUMS: DABAS FOTOGRAFĒŠANA\n\nTEKSTS:\n---\nDabas fotografēšana ir populārs vaļasprieks un sportiska nodarbe Latvijā, kas apvieno fizisko aktivitāti ar māksliniecisko izpausmi. Tā kļūst aktuāla, jo cilvēki meklē veidus, kā atpūsties svaigā gaisā un iemūžināt Latvijas krāšņo dabu. Daudzi ģimenes locekļi kopīgi dodas pārgājienos ar kamerām, stiprinot saites un baudot emocijas no dabas skatiem.\n\nPēdējos desmit gados dalībnieku skaits dabas fotogrāfiju konkursos Latvijā pieaudzis par 60 procentiem. Populāras vietas ir Gaujas nacionālais parks, Ķemeru purvs un Rīgas jūrmala. Piemēram, katru oktobri Jūrmalā notiek fotofestivāls, kur piedalās aptuveni 500 fotogrāfu no visas valsts.\n\nPraksē fotogrāfi agri no rīta dodas ekspedīcijās, izmantojot tripodus un teleobjektīvus, lai noķertu īsto gaismu. Viņi gaida dzīvnieku parādīšanos vai ziedu rūsu. Nedrīkst traucēt savvaļas dzīvniekus, tuvojoties tiem pārāk tuvu, un ieteicams valkāt klusinātus apavus un kamuflāžas apģērbu.\n\nFotogrāfijas speciālisti iesaka iesācējiem sākt ar viedtālruni un regulāri piedalīties konkursos. Šis vaļasprieks ne tikai attīsta prasmes, bet arī veicina izpratni par dabas aizsardzību Latvijā.\n---",
        "questions": [
            "1. Kur Latvijā notiek fotofestivāls katru oktobri?",
            "2. Kāpēc dabas fotografēšana kļūst aktuāla Latvijā?",
            "3. Kā fotogrāfi noķer īsto gaismu?",
            "4. Ko nedrīkst darīt, fotografējot savvaļas dzīvniekus?",
            "5. Ko iesaka fotogrāfijas speciālisti iesācējiem?"
        ]
    },
    {
        "id": "centraltirgus_riga",
        "title_lv": "CENTRĀLTIRGUS",
        "topic": "iepirksanas",
        "body": "Centrāltirgus Rīgā ir viena no populārākajām iepirkšanās vietām Latvijā. Te rīdzinieki un pilsētas viesi katru dienu iegādājas svaigus produktus, ogas un dārzeņus. Tas ir sociālais centrs, kur satiekas dažādu paaudžu ļaudis, apmainās ziņas un bauda tirgus rosīgo gaisotni. Tirgus saglabā vecas iepirkšanās tradīcijas mūsdienu steidzīgajā dzīvē.\n\nCentrāltirgus darbojas jau kopš 1924. gada un aizņem piecu lielu paviljonu teritoriju pie Daugavas. Katru dienu to apmeklē aptuveni 30 tūkstoši cilvēku. Pēdējos desmit gados tirgū pārdod vairāk nekā 60 procentus no Rīgas svaigajiem dārzeņiem un augļiem, īpaši vasarā un rudenī.\n\nIepirkšanās notiek paviljonos un āra letēs: pircēji izvēlas preces, mēģina ogas, tirgojas ar pārdevējiem. Ieteicams ierasties agri no rīta, kad ir vissvaigākie produkti un mazāks pūlis. Jāņem līdzi grozs vai maisiņš, nedrīkst aizmirst skaidro naudu, jo daudzi tirgotāji pieņem tikai to.\n\nTirgotāji un vēsturnieki uzskata, ka Centrāltirgus ir Rīgas kultūras mantojums. Viņi iesaka apmeklēt tirgu regulāri, lai nobaudītu īstus vietējos produktus un atbalstītu mazos ražotājus.",
        "questions": [
            "1. Kad Rīgā atvērās Centrāltirgus?",
            "2. Kāpēc Centrāltirgus ir sociālais centrs?",
            "3. Kā notiek iepirkšanās Centrāltirgū?",
            "4. Ko ieteicams paņemt līdzi uz tirgu?",
            "5. Ko iesaka tirgotāji un vēsturnieki par tirgus apmeklējumu?"
        ]
    },
    {
        "id": "iepirksanas_interneta",
        "title_lv": "IEPIRKŠANĀS INTERNETĀ",
        "topic": "iepirksanas",
        "body": "Mūsdienās arvien vairāk Latvijas iedzīvotāju izvēlas iepirkšanos internetā. Tas ir ērti aizņemtajiem cilvēkiem Rīgā un citās lielpilsētās, kuri vēlas taupīt laiku un izvairīties no rindām fiziskajos veikalos. Pandēmijas laikā šī iepirkšanās veids kļuva īpaši aktuāls, jo ļāva saglabāt veselību un pavadīt vairāk laika ar ģimeni.\n\nPēdējos piecos gados tiešsaistes iepirkšanās Latvijā ir pieaugusi par aptuveni 60 procentiem. 2023. gadā ap 45 procentiem iedzīvotāju veica pirkumus portālos kā 1a.lv vai niivas.lv. Populāras ir preces no ārzemju platformām, piemēram, Amazon, bet piegādes Rīgā ilgst tikai dažas dienas.\n\nIepirkšanās internetā notiek, izvēloties preci mājaslapā, reģistrējoties un apmaksājot ar bankas karti. Pircēji saņem sūtījumu ar kurjeru vai pašizņemšanas punktā. Speciālisti iesaka pārbaudīt pārdevēja atsauksmes un nedot personas datus aizdomīgām vietnēm, lai izvairītos no krāpniecības.\n\nPatērētāju aizstāvji uzskata, ka iepirkšanās internetā ir droša, ja izmanto pazīstamus veikalus un lasa pirkuma noteikumus. Tas ļauj salīdzināt cenas un atrast labākos piedāvājumus, taupot naudu ikdienas vajadzībām.",
        "questions": [
            "Cik procentus iedzīvotāju 2023. gadā veica pirkumus internetā?",
            "Kāpēc pandēmijas laikā iepirkšanās internetā kļuva aktuāla?",
            "Kā apmaksā preces internetā?",
            "Ko iesaka darīt, lai izvairītos no krāpniecības?",
            "Ko uzskata patērētāju aizstāvji par iepirkšanos internetā?"
        ]
    },
    {
        "id": "lauku_tirdzini",
        "title_lv": "LAUKU TIRDZĪŅI",
        "topic": "iepirksanas",
        "body": "Latvijā lauku zemnieku tirdziņi kļūst arvien populārāki starp iedzīvotājiem. Cilvēki tur iegādājas svaigus produktus tieši no ražotājiem, bauda lauku noskaņu un atbalsta vietējos zemniekus. Šie tirdziņi stiprina saikni starp pilsētu un laukiem, saglabā tradīcijas un rosina veselīgu ēšanas paradumu ievērošanu. Katru gadu tos apmeklē desmitiem tūkstošu cilvēku.\n\nPēdējos desmit gados Latvijā notiek vairāk nekā 300 lauku tirdziņu gadā. Rīgā slavens ir Kalnciema ielas tirdziņš, kas darbojas katru sestdienu no maija līdz oktobrim. Cēsīs un Jelgavā tie pulcē aptuveni 200 ražotāju, piedāvājot vietējos dārzeņus, sierus un medu. Pilsētās šie pasākumi bieži sakrīt ar svētkiem.\n\nUz tirdziņiem zemnieki paši stāsta par saviem produktiem un ražošanas metodēm. Apmeklētāji izvēlas svaigus dārzeņus, mājas sierus, maizi un amatniecības izstrādājumus. Iesaka nākt agri no rīta, ņemt līdzi auduma maisiņu vai grozu un maksāt skaidrā naudā. Nedrīkst mest atkritumus turpat, bet gan iznest līdzi.\n\nUztura speciālisti iesaka regulāri apmeklēt lauku tirdziņus, jo produkti tur ir svaigāki un bez liekiem konservantiem. Tas ne tikai uzlabo veselību, bet arī atbalsta vietējo ekonomiku un saglabā kultūras mantojumu.",
        "questions": [
            "1. Kur Rīgā notiek viens no slavenākajiem lauku tirdziņiem?",
            "2. Kāpēc iedzīvotāji apmeklē lauku zemnieku tirdziņus?",
            "3. Kā zemnieki uz tirdziņiem stāsta par saviem produktiem?",
            "4. Kādus produktus var iegādāties uz lauku tirdziņiem?",
            "5. Ko iesaka uztura speciālisti par pirkumiem uz tirdziņiem?"
        ]
    },
    {
        "id": "lietotu_preču_veikali",
        "title_lv": "LIETOTU PREČU VEIKALI",
        "topic": "iepirksanas",
        "body": "Latvijā arvien vairāk cilvēku izvēlas iepirkties lietotu preču veikalos. Tas palīdz ietaupīt naudu grūtos laikos, atrast unikālas un stilīgas lietas, kā arī saudzēt vidi, jo samazinās jaunu preču ražošana. Īpaši populāri šie veikali starp jauniešiem un ģimenēm Rīgā, kur retro un vintage stils kļūst par modi.\n\nPēdējos desmit gados Rīgā atvērti vairāk nekā 25 jauni lietotu preču veikali, galvenokārt Pārdaugavā, centrā un Uzvaras prospektā. Aptuveni 45 procenti iedzīvotāju vismaz reizi gadā tur pērk apģērbus, grāmatas vai sadzīves priekšmetus. Populārākais ir Centrāltirgus sektors ar lietotām precēm.\n\nVeikalos preces sakārtotas pa plauktiem ar norādītām cenām, pircēji var tās izmēģināt un tirgoties. Iesaka rūpīgi pārbaudīt šuves, pogas un audumu kvalitāti, īpaši apģērbam. Nedrīkst pirkt bojātas elektronikas ierīces bez pārbaudes, labāk ņemt līdzi skaidru naudu.\n\nEkonomisti un vides speciālisti iesaka regulāri iepirkties šādos veikalos, jo tas veicina aprites ekonomiku. Tādējādi cilvēki ietaupa līdzekļus un mazina atkritumu apjomu Latvijā.",
        "questions": [
            "1. Kur Rīgā ir atvērti jauni lietotu preču veikali?",
            "2. Kāpēc cilvēki izvēlas iepirkties lietotu preču veikalos?",
            "3. Kā pircēji pārbauda apģērbu kvalitāti veikalos?",
            "4. Ko nedrīkst pirkt bez pārbaudes?",
            "5. Ko iesaka ekonomisti un vides speciālisti?"
        ]
    },
    {
        "id": "latvijas_mazes_veikals",
        "title_lv": "MAIZES VEIKALI",
        "topic": "iepirksanas",
        "body": "Latvijā maizes veikali ir svarīgas ikdienas dzīves sastāvdaļas, jo maize tur ilgi bijusi galvenais ēdiens. Cilvēki tur meklē svaigu, aromātisku maizi, kas saistās ar ģimenes tradīcijām un valsts kultūru. Pēdējos gados pieaugusi interese par vietējiem produktiem, jo daudzi atsakās no lielveikalu rūpnieciskās maizes.\n\nLatvijā darbojas aptuveni 450 maizes veikalu, no kuriem Rīgā ir vairāk nekā 150. Populāri ir veikali Centrāltirgū un Vecrīgā, piemēram, \"Lācis\" un \"Rīgas maiznīca\". Kopš 2015. gada veikalu skaits pieaudzis par 25 procentiem, pateicoties tūristu un vietējo iedzīvotāju pieprasījumam.\n\nIepērkoties maizes veikalā, klienti rūpīgi pārbauda maizes svaigumu pēc smaržas, garozes kraukšķīguma un svara. Iesaka pirkt tikai tajā pašā dienā ceptu maizi un glabāt kokvilnas maisiņā. Nedrīkst izvēlēties maizi ar mākslīgām piedevām, lai saglabātu dabisku garšu un vērtību.\n\nUztura speciālisti iesaka izvēlēties rupjmaizi un pilngraudu klaipus, jo tie satur vairāk šķiedrvielu un vitamīnu. Tādējādi regulāra apmeklēšana maizes veikalos palīdz uzturēt veselīgu ēdienkarti un atbalstīt vietējos maizniekus.",
        "questions": [
            "1. Cik daudz maizes veikalu ir Rīgā?",
            "2. Kāpēc pēdējos gados pieaugusi interese par vietējiem produktiem?",
            "3. Kā noteikt maizes svaigumu veikalā?",
            "4. Kādu maizi nedrīkst izvēlēties iepērkoties?",
            "5. Ko iesaka uztura speciālisti izvēlēties maizes veikalā?"
        ]
    },
    {
        "id": "ziemassvetku-galds",
        "title_lv": "ZIEMASSVĒTKU GALDS",
        "topic": "edieni",
        "body": "Ziemassvētku laikā Latvijā ģimenes pulcējas pie bagātīga svētku galda. Tas ir laiks, kad kopā baudīt tradicionālos ēdienus un stiprināt saites starp radiem. Katru gadu decembrī cilvēki sagādā produktus no tirgiem, lai maltīte sagādātu prieku un siltumu visiem ģimenes locekļiem.\n\nTradicionāli uz Ziemassvētku galda novieto deviņus ēdienus, piemēram, zirņus ar speķi, piparkūkas un ceptu karpu. Rīgas Centrāltirgū decembrī pārdod aptuveni 50 tonnas speķa un zirņu. Pēdējos 10 gados 80 procentu latviešu ģimeņu sagatavo vismaz septiņus no šiem ēdieniem.\n\nĢimenes bieži kopā gatavo maltīti: vāra zirņus ar speķi, cep pīrāgus un rotā piparkūkas ar glazūru. Ieteicams izmantot svaigus produktus no vietējiem tirgiem un izvairīties no pārēšanās ar treknu ēdienu. Bērni ar prieku palīdz mīklas mīcīšanā un cepšanā.\n\nUztura speciālisti iesaka papildināt galdu ar dārzeņiem un augļiem, lai nodrošinātu līdzsvarotu uzturu. Vēsturnieki uzsver, ka šādas tradīcijas palīdz saglabāt latviešu kultūru arī mūsdienās.",
        "questions": [
            "Cik tonnas speķa un zirņu pārdod Rīgas Centrāltirgū decembrī?",
            "Kāpēc cilvēki sagādā produktus no tirgiem?",
            "Kā sagatavo zirņus ar speķi?",
            "Kāds ir tradicionālais ēdienu skaits uz Ziemassvētku galda?",
            "Ko iesaka uztura speciālisti papildināt uz galda?"
        ]
    },
    {
        "id": "skabi-kaposti-ziema",
        "title_lv": "SKĀBI KĀPOSTI",
        "topic": "edieni",
        "body": "Ziemā latviešu virtuvē skābi kāposti kļūst īpaši aktuāli, jo nodrošina vitamīnus aukstajā laikā, kad svaigi dārzeņi ir reti un dārgi. Daudzas ģimenes sagatavo tos rudenī, lai baudītu veselīgu ēdienu ikdienā un svētkos. Šis ēdiens saista paaudzes, atgādinot par senajām saglabāšanas tradīcijām Latvijā.\n\nPēdējos 10 gados Latvijā ražo aptuveni 5000 tonnu skābo kāpostu gadā. Rudenī, oktobrī un novembrī, Centrāltirgū Rīgā un citos tirgos tie ir vispieprasītākais rudens produkts. Tradicionāli kāpostus fermentē lauku sētās vai mājas pagrabos, sagatavojot lielus daudzumus ziemai.\n\nSkābos kāpostus gatavo, sagriežot balto kāpostu galviņas un saberzējot ar rupjo sāli, pēc tam sabāžot mucās vai stikla burkās. Fermentācija ilgst 2–4 nedēļas vēsā vietā. Iesaka izmantot bioloģiskus kāpostus, nedrīkst pievienot etiķi vai mākslīgās garšvielas, lai saglabātu dabisko garšu.\n\nUztura speciālisti iesaka ziemā ēst skābos kāpostus katru dienu, jo tie satur daudz vitamīna C un palīdz pret saaukstēšanos. Šis ēdiens uzlabo gremošanu un saglabā latviešu ēšanas kultūru.",
        "questions": [
            "Kur Latvijā ir vispieprasītākie skābie kāposti rudenī?",
            "Kāpēc ziemā ēd skābos kāpostus?",
            "Kā sagatavo skābos kāpostus?",
            "Ko nedrīkst pievienot skājiem kāpostiem?",
            "Ko iesaka uztura speciālisti ziemā ēst katru dienu?"
        ]
    },
    {
        "id": "dzervenes_izmantosana",
        "title_lv": "DZĒRVENES",
        "topic": "edieni",
        "body": "Dzērvenes ir vienas no iecienītākajām ogām Latvijā, īpaši rudenī. Tās aug mitros purvos un mežmalās, un latvieši tās novāc jau gadsimtiem ilgi. Šodien dzērvenes izmanto gan ikdienas ēdienos, gan veselības stiprināšanai, saglabājot senās tradīcijas. Rudenī ogu lasīšana kļūst par ģimenes pasākumu, kas stiprina saites.\n\nLatvijā dzērvenes novāc no oktobra līdz decembrim, galvenokārt Latgales un Vidzemes purvos. Pēdējos 10 gados vidējā gada raža sasniedz aptuveni 1500 tonnu. Rīgā Centrāltirgū svaigas dzērvenes maksā ap 3 eiro kilogramā, un 70 % pircēju tās iegādājas mājas sagatavošanai.\n\nDzērvenes ēd svaigas, gatavo sulas un ievārījumus, pievieno tējai un putraimiem. Pirms uzglabāšanas tās nedrīkst mazgāt, lai nesāktu pelēt – labāk to darīt pirms lietošanas. Iesaka novākt tikai pilnīgi sarkanas, nobriedušas ogas. Tās parasti pievieno gaļas ēdieniem garšai.\n\nUztura speciālisti iesaka lietot dzērvenes katru dienu nelielos daudzumos, jo tās satur daudz C vitamīna un antioksidantu. Tādējādi stiprina imunitāti un palīdz pret saaukstēšanos visa gada garumā.",
        "questions": [
            "1. Kur Latvijā galvenokārt novāc dzērvenes?",
            "2. Kāpēc rudenī dzērveņu lasīšana kļūst par ģimenes pasākumu?",
            "3. Kā saglabāt dzērvenes pirms lietošanas?",
            "4. Kādas dzērvenes iesaka novākt?",
            "5. Ko iesaka uztura speciālisti par dzērveņu lietošanu?"
        ]
    },
    {
        "id": "latviesu_rudzu_maize",
        "title_lv": "RUDZU MAIZE",
        "topic": "edieni",
        "body": "Latviešu rudzu maize ir pamatelements daudzu ģimeņu ikdienas ēdienreizēs. Tā saistās ar senām lauku tradīcijām un svētku galdiem Latvijā. Mūsdienās pieaug interese par šo produktu, jo tas ir veselīgs, lēts un sātīgs. Rudzu maize palīdz saglabāt nacionālo identitāti un stiprina saikni ar senčiem maltītēs.\n\nLatvijā rudzu maizi cep no rudziem jau vairāk nekā simts gadus. Pēdējos desmit gados tās patēriņš pieaudzis par aptuveni 25 procentiem. Rīgā Centrāltirgū var nopirkt dažādas šķirnes, piemēram, rupjmaizi no Vidzemes vai smalkāku no Kurzemes. Katru gadu ražo vairāk nekā 50 tūkstošus tonnu.\n\nRudzu maizi cep ar raugu, pievienojot ūdeni, sāli un reizēm sēklas. Cilvēki to pērk tirgū vai cep mājās cepeškrāsnī. Iesaka uzglabāt veselu klaipu vēsā, sausā vietā. Nedrīkst likt ledusskapī, jo tā ātri mitrinās un pelē. Tipiski ēd ar sieru vai speķi brokastīs.\n\nUztura speciālisti iesaka rudzu maizi, jo tā satur daudz šķiedrvielu un B grupas vitamīnu. Vēsturnieki uzsver, ka tā ir latviešu kultūras neatņemama daļa. Tādējādi rudzu maize veicina veselīgu uzturu un saglabā tradīcijas.",
        "questions": [
            "1. Kur Rīgā var nopirkt rudzu maizi?",
            "2. Kāpēc mūsdienās pieaug interese par rudzu maizi?",
            "3. Kā cep rudzu maizi?",
            "4. Ko nedrīkst darīt ar rudzu maizi uzglabāšanas laikā?",
            "5. Ko iesaka uztura speciālisti par rudzu maizi?"
        ]
    },
    {
        "id": "darza-zalites-teja",
        "title_lv": "DĀRZA TĒJAS",
        "topic": "edieni",
        "body": "Latvijā arvien vairāk cilvēku interesējas par tējām no dārza zālītēm. Tas saistās ar vēlmi pēc veselīga un dabiska uztura, kā arī ar tradīcijām izmantot savus dārzus. Vasarā un rudenī daudzi lasa zālītes, lai sagatavotu krājumus ziemai. Šāda tēja ir lēta, garšīga un tuvu dabai.\n\nPēdējos desmit gados Latvijā mājas audzēto zāļu patēriņš pieaudzis par aptuveni 40 procentiem. Populārākās ir piparmētra, kumelītes un pelašķi. Rīgā, Centrāltirgū pārdod gan svaigas, gan žāvētas zālītes. Lasa galvenokārt no aprīļa beigām līdz septembrim.\n\nZālītes vāc sausā laikā, prom no ceļiem un lauksaimniecības laukiem. Pēc savākšanas tās rūpīgi nomazgā aukstā ūdenī un izklāj žāvēšanai ēnainā, labi vēdināmā vietā. Tēju sagatavo, uzliējot verdošu ūdeni uz vienu tējkaroti zāļu uz glāzi un uzlienot 5–10 minūtes. Nedrīkst lasīt piesārņotās vietās.\n\nĀrsti un fitoterapeiti iesaka dzert šādas tējas katru dienu imunitātes stiprināšanai un gremošanas uzlabošanai. Pareizi sagatavotas tās ir drošas visai ģimenei un veselīga alternatīva pirktajām tējām.",
        "questions": [
            "1. No kura mēneša beigām līdz kuram mēnesim Latvijā lasa dārza zālītes?",
            "2. Kāpēc Latvijā cilvēki gatavo tējas no dārza zālītēm?",
            "3. Kā sagatavo tēju no dārza zālītēm?",
            "4. No kurienes nedrīkst vākt zālītes?",
            "5. Ko iesaka ārsti un fitoterapeiti par dārza zālīšu tējām?"
        ]
    },
    {
        "id": "brauksana_uz_lietuvu_un_igauniju",
        "title_lv": "BRAUKŠANA UZ KAIMIŅVALSTĪM",
        "topic": "celosana",
        "body": "NOSAUKUMS: BRAUKŠANA UZ KAIMIŅVALSTĪM\n\nLatvijā daudzi iedzīvotāji izvēlas ceļot uz Lietuvu un Igauniju īsām brīvdienām vai iepirkšanās reizēm. Tas ir ērti, jo ceļš no Rīgas aizņem tikai dažas stundas, un izmaksas ir zemākas nekā lidojumi tālāk. Šie ceļojumi stiprina Baltijas valstu saites un ļauj baudīt atpūtu tuvumā. Ik gadu tas kļūst arvien populārāks pēc pandēmijas.\n\nPēdējos piecos gados ceļotāju skaits no Rīgas uz Tallinu ir palielinājies par 25 procentiem. Autobusi kursē katru stundu, un brauciens uz Viļņu ilgst aptuveni 3,5 stundas pa A1 šoseju. Populāras vietas ir Viļņas vecpilsēta un Tallinas vecpilsēta. 2023. gadā reģistrēti vairāk nekā 500 tūkstoši šādu braucienu.\n\nPraksē cilvēki izmanto autobusu kompānijas kā Lux Express vai brauc ar savu auto. Ieteicams pārbaudīt ceļa nodokļus un laika apstākļus, īpaši ziemā. Nedrīkst aizmirst pasi vai ID karti un nomainīt riepas sniegam. Maršrutu labāk plānot ar mobilajām aplikācijām.\n\nTūrisma speciālisti iesaka apvienot braukšanu ar naktsmītņu rezervēšanu iepriekš. Tas ne tikai ietaupa laiku, bet arī bagātina izpratni par kaimiņu kultūrām un veicina ilgtspējīgu tūrismu reģionā.",
        "questions": [
            "Cik ilgi ilgst brauciens no Rīgas uz Viļņu?",
            "Kāpēc latvieši izvēlas ceļot uz Lietuvu un Igauniju?",
            "Kādas transportlīdzekļus izmanto ceļošanai uz kaimiņvalstīm?",
            "Ko nedrīkst aizmirst paņemt līdzi braucienā?",
            "Ko iesaka tūrisma speciālisti ceļojuma plānošanā?"
        ]
    },
    {
        "id": "jurmal_a_vasar_a",
        "title_lv": "JŪRMALA VASARĀ",
        "topic": "celosana",
        "body": "Vasarā daudzi Latvijas iedzīvotāji un viesi izvēlas atpūsties Jūrmalā. Pilsētās kļūst karsti, un cilvēki meklē svaigu jūras gaisu, smilšu pludmales un atpūtu pie Baltijas jūras. Tas ir populārs ģimenes izbrauciens, kur var baudīt dabu, pastaigāties un apmeklēt kultūras pasākumus Dzintaru koncertzālē.\n\nJūrmalas pludmale ir 24 kilometrus gara, un vasarā, īpaši jūlijā un augustā, to apmeklē vairāk nekā pusmiljons cilvēku. No Rīgas uz Jūrmalu kursē vilcieni ik pēc 30 minūtēm, ceļojums ilgst apmēram 30 minūtes. Pēdējos 10 gados tūristu skaits šeit pieaudzis par 25 procentiem.\n\nCilvēki Jūrmalā peldās jūrā, sauļojas uz smiltīm, staigā pa koka laipām un apmeklē kafejnīcas. Iesaka lietot aizsargkrēmu pret sauli, paņemt līdzi dzeramo ūdeni un atkritumu maisiņus. Pludmalē nedrīkst smēķēt, dedzināt ugunskurus vai traucēt citas atpūtnieces. Labāk izmantot sabiedrisko transportu.\n\nTūrisma speciālisti iesaka apmeklēt Jūrmalu darba dienu rītos, kad ir mazāk cilvēku un vairāk vietas. Tā ir lieliska iespēja atpūsties netālu no mājām, baudot Latvijas dabu un atjaunojot spēkus ikdienas steigai.",
        "questions": [
            "1. Cik gara ir Jūrmalas pludmale?",
            "2. Kāpēc cilvēki vasarā dodas uz Jūrmalu?",
            "3. Kā nokļūt uz Jūrmalu no Rīgas?",
            "4. Ko nedrīkst darīt Jūrmalas pludmalē?",
            "5. Ko iesaka tūrisma speciālisti, apmeklējot Jūrmalu?"
        ]
    },
    {
        "id": "celosana_velosipeds",
        "title_lv": "VELOSIPĒDU CEĻOJUMI",
        "topic": "celosana",
        "body": "Latvijā arvien vairāk cilvēku izvēlas ceļot ar velosipēdu, lai baudītu skaisto dabu un mazpazīstamas vietas. Tas ir veselīgs atpūtas veids ģimenēm un jauniešiem, īpaši vasarā. Riteņbraucieni veicina ekoloģisku dzīvesveidu un stiprina kopīgu piedzīvojumu sajūtu starp draugiem. Ceļošana pa Latviju šādā veidā kļūst par populāru alternatīvu automašīnām.\n\nPēdējos desmit gados Latvijā izveidoti vairāk nekā 3000 kilometru apzīmēti velomaršruti. Populārākie ir Rīgas apkārtnē, Siguldā un Jūrmalā. Piemēram, Jūrmalas velotrase ir 20 kilometrus gara. 2022. gadā pa tiem ceļoja aptuveni 50 tūkstoši riteņbraucēju no visas valsts.\n\nPraksē riteņbraucēji ņem līdzi remonta komplektu, ūdens pudeli un karti. Iesaka izmantot grants ceļus un meža takas, izvairoties no šosejām ar intensīvu satiksmi. Grupās drošāk apstāties pie pilīm un ezeriem. Nedrīkst aizmirst apdrošināšanu un ķiveri.\n\nRiteņbraukšanas kluba speciālisti iesaka iesācējiem sākt ar dienas braucieniem 30 kilometru garumā. Tādējādi velosipēdu ceļošana kļūst par pieejamu veidu, kā pilnvērtīgi iepazīt Latvijas dabas bagātības un kultūras mantojumu.",
        "questions": [
            "Cik kilometru apzīmēto velomaršrutu ir izveidoti Latvijā pēdējos desmit gados?",
            "Kāpēc cilvēki Latvijā izvēlas ceļot ar velosipēdu?",
            "Kādas lietas jāņem līdzi velosipēdu ceļojumā?",
            "Kura vieta minēta kā piemērs populāram velomaršrutam?",
            "Ko iesaka riteņbraukšanas kluba speciālisti iesācējiem?"
        ]
    },
    {
        "id": "lidojumi_riga",
        "title_lv": "LIDOJUMI NO RĪGAS",
        "topic": "celosana",
        "body": "Ceļošana ar lidmašīnām no Rīgas lidostas kļūst arvien populārāka starp latviešiem. Tā ļauj ātri nokļūt uz Eiropas galvaspilsētām, piemēram, Londonu, Parīzi vai Berlīni. Daudzi izmanto lidojumus atpūtai siltākos kurortos vai darījumu braucieniem. Latvijā tas saistās ar vēlmi redzēt pasauli un apmeklēt radus ārzemēs.\n\nPēdējos desmit gados Rīgas lidostas pasažieru skaits pieaudzis vairāk nekā divas reizes. 2023. gadā šeit apkalpoja aptuveni 7,1 miljonu pasažieru. Populārākie galamērķi ir Londra, Oslo un Frankfurte. No Rīgas katru dienu izlido vairāk nekā piecdesmit reisu.\n\nPasažieriem jāierodas lidostā vismaz divas stundas pirms izlidošanas. Reģistrēšanos var veikt tiešsaistē savā telefonā vai pie letes. Rokas bagāžā nedrīkst vest šķidrumus lielākos nekā 100 mililitru traukos. Ģimenes bieži izvēlas agros rīta reisus, lai bērni ceļotu labāk.\n\nCeļojumu speciālisti iesaka laicīgi pirkt biļetes un izmantot zemas cenas aviokompānijas. Tādējādi var ietaupīt līdz pat 50 procentiem. Labi plānots lidojums nodrošina patīkamu ceļojumu bez steigas un problēmām.",
        "questions": [
            "1. Cik daudz pasažieru apkalpoja Rīgas lidosta 2023. gadā?",
            "2. Kāpēc latvieši izmanto lidojumus no Rīgas lidostas?",
            "3. Kā var veikt reģistrēšanos lidojumam?",
            "4. Ko nedrīkst vest rokas bagāžā?",
            "5. Ko iesaka ceļojumu speciālisti, lai ietaupītu naudu?"
        ]
    },
    {
        "id": "atpusa_kurzeme_piekraste",
        "title_lv": "KURZEMES PIEKRASTE",
        "topic": "celosana",
        "body": "Kurzemes piekraste piesaista daudzus latviešus vasaras atpūtai. No Rīgas un citām pilsētām šeit brauc ģimenes un jaunieši, lai baudītu baltas smilšu pludmales, svaigu jūras gaisu un mierīgu dabu. Šāda atpūta palīdz atjaunot spēkus ikdienas steigā, stiprina saikni ar jūru un dabu. Populāritāte pieaug dēļ tuvinājuma un pieejamām cenām.\n\nPēdējos desmit gados Kurzemes piekrastē apmeklētāju skaits palielinājies par 30 procentiem. Populārākās vietas ir Ventspils ar tās plašo pludmali, Liepāja ar koncertzāli un Kuldīga ar Ventas rumbu. Vasarā jūlijā un augustā šeit pulcējas simtiem tūkstošu atpūtnieku no visas Latvijas.\n\nCilvēki ceļo ar autobusu no Rīgas autoostas vai personīgo auto pa šoseju. Viņi peldās jūrā, staigā pa takām, kempingo pludmalēs. Iesaka rezervēt viesnīcas iepriekš un lietot sauļošanās krēmu. Nedrīkst kurināt ugunskurus mežos un traucēt putnus ligzdošanas laikā.\n\nTūrisma speciālisti iesaka izmantot vietējos velomaršrutus un sabiedrisko transportu, lai mazinātu satiksmes aizsprostojumus. Šāda atpūta ne tikai atpūstina ķermeni, bet arī iepazīst Latvijas dabu un kultūru.",
        "questions": [
            "Kurās vietās Kurzemes piekrastē ir populāra atpūta?",
            "Kāpēc Kurzemes piekrastei pieaug popularitāte?",
            "Kā no Rīgas nokļūt Kurzemes piekrastē?",
            "Ko nedrīkst darīt atpūtas laikā Kurzemes piekrastē?",
            "Ko iesaka tūrisma speciālisti, apmeklējot Kurzemes piekrasti?"
        ]
    },
    {
        "id": "latviesu_rudens",
        "title_lv": "LATVIEŠU RUDENS",
        "topic": "laiks",
        "body": "Latvijā rudens sākas septembra vidū un ilgst līdz novembra beigām. Tas ir gadalaiks, kad koki krāsojas dzeltenās, oranžās un sarkanās krāsās, cilvēki vāc ražu un bauda kluso dabu. Daudziem šis periods asociējas ar mieru, atpūtu laukā un sagatavošanos aukstākam laikam. Rudens Latvijā ir populārs pastaigām mežos un parkos, kur var sajust īsto latviešu noskaņu.\n\nPēdējos desmit gados Latvijā rudens kļuvis siltāks, vidējā gaisa temperatūra oktobrī Rīgā ir aptuveni septiņi grādi. Septembrī un oktobrī kopā nokrīt ap 150 milimetru lietus. Vidzemē, piemēram, Gaujas nacionālajā parkā, lapas maina krāsu jau septembra otrajā pusē, bet Kurzemē vēju stiprina jūras ietekme.\n\nCilvēki rudens laikā bieži dodas sēņu un ogu vācēšanā mežos, valkājot siltas jakas un gumijas zābākus. Iesaka sekot laika prognozēm un izvairīties no garām pastaigām stiprā lietū, lai nesaslimtu. Rīgas parkos, piemēram, Mežaparkā, notiek rudens pasākumi ar lapu krāsu baudīšanu un tējas dzeršanu.\n\nMeteorologi uzskata, ka rudeni jāizmanto veselīgām pastaigām svaigā gaisā, kas stiprina imunitāti. Nedrīkst aizmirst par siltu apģērbu un lietussargu. Tādējādi šis gadalaiks palīdz sagatavoties ziemai ar labu garastāvību.",
        "questions": [
            "Kad Latvijā sākas rudens?",
            "Kāda ir vidējā gaisa temperatūra oktobrī Rīgā?",
            "Kāpēc cilvēki rudens laikā valkā gumijas zābākus?",
            "Ko meteorologi iesaka darīt rudenī, lai stiprinātu imunitāti?",
            "No kurienes Kurzemē rudens vēji iegūst stiprumu?"
        ]
    },
    {
        "id": "sniegotas_ziemass",
        "title_lv": "SNIEGOTAS ZIEMAS",
        "topic": "laiks",
        "body": "Latvijā sniegotas ziemas sagādā prieku daudziem iedzīvotājiem. Bērni būvē sniega vīrus un met sniega bumbas, pieaugušie bauda slēpošanu un slidotavu. Tomēr biezs sniegs rada problēmas satiksmei un ikdienas gaitām. Klimata izmaiņu dēļ šādas ziemas kļūst retākas, tāpēc tās ir īpaši gaidītas un novērtētas.\n\nPēdējos 20 gados Latvijā sniegs nokritis vidēji 60 dienās gadā. Rīgā 2023. gada janvārī uzkrājās līdz 50 centimetriem sniega, savukārt Vidzemē, piemēram, Siguldā, temperatūra noslīdēja līdz mīnus 25 grādiem. Centrāltirgū pārdevēji ziņo par lielāku pirkumu pieaugumu siltam apģērbam un apaviem.\n\nSniegotā laikā iedzīvotāji valkā siltas jakas, cepures, šalles un gumijzābaku virsvilkas. Ceļus un ietves tīra ar lāpstu vai sniega pūtējiem. Nedrīkst atstāt auto nesatīrītu no sniega, jo tas apgrūtina satiksmi. Bērni parkos būvē sniega pilis, pieaugušie dodas ziemas pastaigās.\n\nMeteorologi iesaka sekot laika prognozēm un laikus sagatavot ziemas aprīkojumu. Viņi uzsver, ka sniegotas ziemas stiprina veselību svaigā gaisā, ja ievēro drošību un neriskē ar atdzišanu. Tādas ziemas veido patīkamu kopienas garu Latvijā.",
        "questions": [
            "Cik dienas gadā vidēji Latvijā nokritis sniegs pēdējos 20 gados?",
            "Kāpēc sniegotas ziemas Latvijā ir īpaši gaidītas?",
            "Kā tīra ceļus un ietves sniegotā laikā?",
            "Kādu apģērbu valkā iedzīvotāji sniegotā laikā?",
            "Ko meteorologi iesaka darīt pirms sniegotas ziemas?"
        ]
    },
    {
        "id": "baltajas_naktis",
        "title_lv": "BALTAJĀS NAKTIS",
        "topic": "laiks",
        "body": "Jūnija beigās Latvijā iestājas baltās naktis, kad saule nenoriet pilnībā un nakts paliek gaiša. Šis periods ir īpaši gaidīts, jo sakrīt ar Jāņu svinībām un piedāvā baudīt dabu veselu diennakti. Daudzi latvieši jūtas enerģiskāki, rīko pastaigas un pulcējas pie ugunskuriem, stiprinot kopības sajūtu.\n\nBaltās naktis Latvijā ilgst no 21. jūnija līdz aptuveni 25. jūnijam. Rīgā un Vidzemē saule zem horizonta atrodas tikai apmēram vienu stundu, nodrošinot 20–30 procentus dienas gaismas. Pēdējos desmit gados tūristu skaits šajā laikā Rīgā palielinājies par 15 procentiem.\n\nCilvēki dodas nakts pastaigās pa Daugavas krastiem, rīko piknikus parkos un fotografē ziedošus laukus. Ieteicams valkāt saulesbrilles pat naktī, lai acis ne nogurtu no pastāvīgās gaismas. Nedrīkst aizmirst par miegu, aizvelkot aizkarus guļamistabā.\n\nDabas pētnieki iesaka izmantot baltās naktis augu un putnu novērošanai. Tas palīdz izprast dabisko ritmu un stiprina saikni ar apkārtējo vidi.",
        "questions": [
            "1. Cik ilgi Latvijā ilgst baltās naktis?",
            "2. Kāpēc baltās naktis ir īpaši gaidītas Latvijā?",
            "3. Ko cilvēki dara baltās naktīs?",
            "4. Kādu aizsardzību ieteicams valkāt pat naktī?",
            "5. Ko iesaka dabas pētnieki darīt baltās naktīs?"
        ]
    },
    {
        "id": "rudens_veni_un_lietus",
        "title_lv": "RUDENS VĒJI UN LIETUS",
        "topic": "laiks",
        "body": "Latvijā rudens, īpaši no septembra beigām līdz decembrim, raksturojas ar stipriem vējiem un bagātīgu lietu. Šie laika apstākļi ietekmē ikdienas dzīvi, ceļu satiksmi un iedzīvotāju garastāvokli. Daudzi jau rudenī gatavojas mitrumam, iegādājoties lietusmēteļus un gumijas zābakus. Tas kļūst aktuāls, jo vēji un lietus atgādina par gaidāmo ziemu un mainīgajiem laikapstākļiem.\n\nPēdējos desmit gados Latvijā reģistrētas vidēji 6 stipras vētras sezonā no oktobra līdz decembrim. Rīgā oktobrī vidējais nokrišņu daudzums sasniedz 70 milimetru, bet vēja ātrums bieži pārsniedz 15 metrus sekundē. Piemēram, 2023. gadā Kurzemē vētra radīja postījumus mežos, ceļos un piejūras rajonos.\n\nPraksē iedzīvotāji valkā ūdensnecaurlaidīgas jakas, ņem līdzi izturīgus lietussargus un gumijas apavus. Nedrīkst atstāt ārā vieglas mēbeles vai puķu podus, jo vējš tos aizpūš prom. Iesaka sekot Latvijas Vides, ģeoloģijas un meteoroloģijas centra brīdinājumiem un plānot braucienus. Tipiska situācija ir aizkavēšanās darbā vai skolā lietus dēļ.\n\nMeteorologi uzskata, ka rudens vēji un lietus ir normāli Latvijas klimatam un palīdz sagatavoties aukstākam laikam. Viņi iesaka būt gataviem, stiprināt imunitāti ar siltām zupām un izmantot šo periodu veselīgu paradumu veidošanai.",
        "questions": [
            "Kad Latvijā biežāk novērojami stipri vēji un lietus?",
            "Cik daudz nokrišņu vidēji oktobrī Rīgā?",
            "Kā iedzīvotāji aizsargājas pret rudens vējiem un lietu?",
            "Ko nedrīkst atstāt ārā vēja laikā?",
            "Ko meteorologi iesaka darīt rudens laikā?"
        ]
    },
    {
        "id": "pavasara_atmoda",
        "title_lv": "PAVASARA ATMODA",
        "topic": "laiks",
        "body": "Latvijā pavasaris ir gaidīts gadalaiks, kad daba mostas pēc aukstās ziemas. Cilvēki jūtas priecīgi, redzot pirmos zaļos dzinumus un dzirdot putnu dziesmas. Šis periods saistās ar atjaunināšanos un jaunu sākumu ikdienas dzīvē. Daudzi dodas garās pastaigās mežos un parkos, lai baudītu svaigo gaisu un siltumu.\n\nPavasara atmoda parasti sākas marta otrajā pusē, kad dienas kļūst garākas. Vidējā gaisa temperatūra paaugstinās līdz 5–10 grādiem. Piemēram, Rīgas Gaiziņa parkā marta beigās zied sniegpulkstenītes un krokusi. Pēdējos desmit gados atmoda notiek par aptuveni divām nedēļām agrāk nekā iepriekš.\n\nDabā notiek straujas izmaiņas: sniegs kūst, upes un ezeri applūst, koki sāk pumpurēties. Putni atgriežas no siltajām zemēm un sāk ligzdot. Cilvēkiem iesaka novērot šīs izmaiņas no attāluma, lai nedraudētu dzīvniekiem. Piemēram, Jūrmalā daudzi fotografē pirmos ziedus, bet nedrīkst tos plūkt.\n\nBiologi uzsver, ka pavasara atmodu jāizmanto izglītošanai. Bērniem jāstāsta par dabas cikliem un jāaudzina rūpes pret vidi. Tādējādi mēs stiprinām saikni ar dabu un veicinām tās saglabāšanu nākamajām paaudzēm.",
        "questions": [
            "1. Kad Latvijā parasti sākas pavasara atmoda?",
            "2. Kāpēc cilvēki jūtas priecīgi pavasarī?",
            "3. Kādas izmaiņas notiek dabā pavasara laikā?",
            "4. Kādi ziedi zied Rīgas Gaiziņa parkā marta beigās?",
            "5. Ko iesaka biologi darīt pavasara atmodas laikā?"
        ]
    }
]
