"""Lasīšana text catalog.

Generated by scripts/generate_reading_texts.py. Two seed texts
(PUTNI ZIEMĀ and CITRONS) are official PMLP paraugi for the
«Latvieši un līvi» category; the rest are Grok-generated in the same
mold (~130 words, 3-4 paragraphs, informative-publicistic style)
across the 11 official PMLP topics.

Format per entry:
- id: short slug
- title_lv: uppercase heading
- topic: one of READING_TOPICS keys
- source: "PMLP paraugs …" for seed, otherwise absent/synthetic
- body: 3-4 paragraphs separated by "\n\n"
- questions: exactly 5 Latvian questions of varying types
"""

from __future__ import annotations

READING_TOPICS: dict[str, str] = {
    "gimene": "es un mani tuvinieki (ģimene, radi, draugi)",
    "dzivesvieta": "dzīves apstākļi un vide (māja, dzīvoklis, lauki, pilsēta)",
    "darbs": "izglītība, darbs, intereses",
    "attiecibas": "attiecības ar citiem cilvēkiem, pieklājība, kaimiņi",
    "kultura": "kultūra un sociālās lietas (tradīcijas, mūzika, teātris, kino)",
    "brivais_laiks": "brīvais laiks un sabiedriskā dzīve",
    "sports": "sports, vaļasprieks",
    "iepirksanas": "iepirkšanās, veikali, tirgus",
    "edieni": "ēdieni un dzērieni",
    "celosana": "ceļošana, Latvijas vietas, transports",
    "laiks": "laika apstākļi, gadalaiki, daba"
}

READING_TEXTS: list[dict] = [
    {
        "id": "putni_ziema",
        "title_lv": "PUTNI ZIEMĀ",
        "topic": "laiks",
        "source": "PMLP paraugs (Latvieši un līvi)",
        "body": "Kad pienāk ziema un kļūst auksti, cilvēki sāk barot putnus. Vieniem liekas, ka putniem nav ko ēst, citiem patīk tos vērot, vēl citi grib saviem bērniem parādīt dažādus putnus. Ja tos baro ziemā, putni labprāt pie mājām dzīvos arī vasarā, kad gaisā būs daudz mušu un kukaiņu.\n\nMūsdienās var nopirkt gatavas barotavas, barības maisījumus, dažādus interjera priekšmetus putniem. Latvijā “modē” ir paštaisītās barotavas: no koka, piena pakām, plastmasas un stikla pudelēm, pat no konservu kārbām.\n\nPutnus barot ir jāsāk jau oktobrī, jo tad viņi sāk meklēt vietas, kur ziemā būs ēdiens. Cilvēkam jāatceras: ja viņš sāk barot putnus, tas ir jādara regulāri katru dienu. Putniem nedrīkst dot sālītu ēdienu un baltmaizi, vislabāk – dažādas sēklas, graudus, speķi.\n\nOrnitologi uzskata, ka nav pareizi barot putnus citos gadalaikos. Labāk ir radīt vidi, lai putni gribētu uzturēties tuvāk cilvēku mājām, piemēram, stādīt augļu kokus un ogu krūmus, būvēt putnu būrus.",
        "questions": [
            "Kāpēc cilvēki ziemā baro putnus?",
            "No kāda materiāla izgatavo barotavas putniem Latvijā?",
            "Cik bieži ir jābaro putni ziemā?",
            "Kurš ēdiens ziemā ir vislabākais putniem?",
            "Ko vēl vajadzētu darīt, lai putni gribētu dzīvot tuvāk cilvēku mājām?"
        ]
    },
    {
        "id": "citrons",
        "title_lv": "CITRONS",
        "topic": "edieni",
        "source": "PMLP paraugs (Latvieši un līvi)",
        "body": "Citrons vienlīdz labi iederas atspirdzinošā limonādē ar ledu un karstā tējā ar medu. Īstā limonāde: izspiež vienu ēdamkaroti citronu sulas, pievieno ēdamkaroti cukura, glāzi ūdens un sajauc.\n\nPar citronkoku dzimteni pētnieki vienbalsīgi atzīst Āziju. Reģionos, kur citroni aug, tos plaši lieto gan tautas medicīnā, gan pārtikā. Iespējams, ka pirmie svešzemnieki, kas novērtēja citronu labās īpašības, bija jūrasbraucēji – viņi ievēroja, ka citronu sula glābj no cingas, kas rodas ilgā kuģojumā, kad jāiztiek ar stipri vienveidīgu pārtiku.\n\nCitrons joprojām ir tāds kā etalons, ar kuru salīdzina citus C vitamīna avotus. Lai kur citroni nonāca, tie tika novērtēti un iecienīti. Tropu un subtropu zemēs cilvēki tos sāka audzēt dārzos, bet vēsākā klimatā centās padarīt par telpaugiem.",
        "questions": [
            "Kā citronus izmanto vietas, kur tie aug?",
            "Kas jāpievieno ūdenim, lai pagatavotu īstu limonādi?",
            "Kādiem dzērieniem var pievienot citronu?",
            "No kurienes citrons izplatījās visā pasaulē?",
            "Kur cilvēki audzē citronkokus?"
        ]
    },
    {
        "id": "janu_svinosana_gimene",
        "title_lv": "JĀŅU SVINĪBAS",
        "topic": "gimene",
        "body": "Latvijā Jāņu svētkus ģimenes svin kopā ar radiem un draugiem. Parasti jūnijā sanāk Līgo vakarā, auž vainagus no ziediem, dzied līgo dziesmas un kurina ugunskuru. Ģimenēm tas ir laiks, kad atpūsties no ikdienas darbiem un stiprināt saites.\n\nTradicionāli cep sieru, gatavo pīrāgus ar zaļumiem un ēd svaigus zirnīšus. Bērni priecājas par rotaļām pie ugunskura, bet pieaugušie stāsta vecas teikas. Eksperti iesaka sagatavot vismaz desmit dažādus ēdienus, lai visi būtu paēduši.\n\nFolkloristi uzsver, ka Jāņi palīdz saglabāt latviešu kultūru. Ģimenēs, kas dzīvo pilsētā, svin vairākas dienas, salīdzinot ar lauku tradīcijām, kur viss notiek ātrāk.\n\nLai svētki izdotos, jādomā par drošību – ugunskuru nedrīkst dedzināt tuvu mājām.",
        "questions": [
            "Kad ģimenes Latvijā svin Jāņus?",
            "Kāpēc Jāņu svētkus svin kopā ar radiem?",
            "Kā ģimenēs gatavo ēdienus Jāņiem?",
            "Ko bērni dara Jāņu vakarā?",
            "Ko folkloristi saka par Jāņu nozīmi?"
        ]
    },
    {
        "id": "vecvecaku_loma",
        "title_lv": "VECVECĀKI",
        "topic": "gimene",
        "body": "Latvijas ģimenēs vecvecāki spēlē svarīgu lomu bērnu audzināšanā. Viņi auklē mazbērnus, kamēr vecāki strādā, un māca vecas tradīcijas. Aptuveni 40 procenti ģimeņu paļaujas uz vecvecāku palīdzību.\n\nVecvecāki stāsta pasakas, cep gardas pankūkas un ved uz mežu ogām. Tas stiprina saikni starp paaudzēm un dod bērniem drošības sajūtu.\n\nSociologi norāda, ka vecvecāku klātbūtne samazina stresu vecākiem un uzlabo bērnu emocionālo attīstību. Piemēram, Rīgā daudzas ģimenes dzīvo vienā mājā ar vecvecākiem.\n\nEksperti iesaka vecākiem regulāri apspriest pienākumus, lai visi justos labi.",
        "questions": [
            "Cik procenti Latvijas ģimeņu izmanto vecvecāku palīdzību?",
            "Kāpēc vecvecāki auklē mazbērnus?",
            "Kā vecvecāki māca tradīcijas bērniem?",
            "Kur dzīvo daudzas Rīgas ģimenes ar vecvecākiem?",
            "Ko iesaka sociologi par vecvecāku iesaisti?"
        ]
    },
    {
        "id": "bernu_dzimšanas_dienas",
        "title_lv": "DZIMŠANAS DIENAS",
        "topic": "gimene",
        "body": "Bērnu dzimšanas dienas Latvijā svin ar ģimeni un draugiem. Parasti cep kūku ar svecītēm, dāvā dāvanas un rīko spēles. Tas ir prieka pilns notikums, kas stiprina draudzību.\n\nVecāki gatavo ēdienus, piemēram, desmit porcijas desiņu un sulu. Bērni priecājas par baloniem un rotaļām, piemēram, slēpņiem.\n\nPedagogi iesaka izvēlēties drošas spēles un ne vairāk kā desmit viesus, lai visi justos ērti. Salīdzinot ar skolas svinībām, mājās ir siltāka atmosfēra.\n\nĢimenēm svarīgi atcerēties bērna intereses, piemēram, zēnam – futbolu, meitenei – lelles.",
        "questions": [
            "Ko dara bērni dzimšanas dienā?",
            "Kāpēc dzimšanas dienas svin ar draugiem?",
            "Kā vecāki gatavo ēdienus svinībām?",
            "Cik viesu iesaka pedagogi?",
            "Ko svarīgi atcerēties par bērna interesēm?"
        ]
    },
    {
        "id": "gimenes_vakarinas",
        "title_lv": "VAKARIŅAS",
        "topic": "gimene",
        "body": "Nedēļas nogalēs daudzas Latvijas ģimenes ēd vakariņas kopā. Sēž pie galda, bauda mājas ēdienu un runā par nedēļas notikumiem. Tas palīdz uzturēt ģimenes vienotību.\n\nParasti gatavo zupu, kotletes un salātus – pietiek četriem cilvēkiem. Bērni stāsta par skolu, vecāki dalās ar darbu.\n\nUztura speciālisti uzsver, ka kopīgas vakariņas ir veselīgākas nekā ātrā ēdiena ēšana. Piemēram, Vidzemē ģimenes ēd trīs reizes nedēļā kopā.\n\nLai vakariņas izdotos, iesaka izslēgt televizoru un klausīties citam.",
        "questions": [
            "Ko ģimenes dara nedēļas nogalēs?",
            "Kāpēc kopīgas vakariņas stiprina ģimeni?",
            "Kādas maltītes gatavo vakariņām?",
            "Cik reizes nedēļā Vidzemes ģimenes ēd kopā?",
            "Ko iesaka uztura speciālisti?"
        ]
    },
    {
        "id": "kazu_tradicijas",
        "title_lv": "KĀZAS",
        "topic": "gimene",
        "body": "Latvijā kāzas svin ar tradīcijām, kas apvieno senos rituālus un mūsdienu modes. Pāris reģistrē laulību, svin ar balli un viesiem.\n\nTradicionāli lauž maizi, meta ziedus un dejo. Visi ēd desmit dažādus ēdienus, tostarp kūku.\n\nEtnografi norāda, ka kāzas stiprina kopienu, īpaši lauku apvidos. Rīgā bieži svin divas dienas, salīdzinot ar īsākām lauku kāzām.\n\nSpeciālisti iesaka plānot budžetu un iesaistīt ģimeni.",
        "questions": [
            "Ko dara kāzās Latvijā?",
            "Kāpēc kāzas stiprina kopienu?",
            "Kā lauž maizi kāzās?",
            "Cik dienas svin kāzas Rīgā?",
            "Ko iesaka etnografi?"
        ]
    },
    {
        "id": "dzive_daudzdzivoklu_nama",
        "title_lv": "DAUDZĪVOKĻU NAMS",
        "topic": "dzivesvieta",
        "body": "Daudzdzīvokļu namos Latvijā dzīvo daudzi iedzīvotāji, īpaši pilsētās. Tur ir koplietošanas telpas, lifts un bērnu laukumi.\n\nKaimiņi sadarbojas, piemēram, tīra kāpnes reizi nedēļā. Tas veicina draudzīgas attiecības.\n\nNamu pārvaldnieki iesaka ievērot klusuma stundas un neizmet atkritumus pagalmā. Salīdzinot ar lauku mājām, šeit ir vieglāk satikt cilvēkus.\n\nRīgā aptuveni 60 procenti dzīvo daudzdzīvokļu namos.",
        "questions": [
            "Kas ir daudzdzīvokļu namos?",
            "Kāpēc kaimiņi sadarbojas?",
            "Kā tīra kāpnes?",
            "Cik procenti rīdzinieku dzīvo daudzdzīvokļu namos?",
            "Ko iesaka namu pārvaldnieki?"
        ]
    },
    {
        "id": "lauku_maja_darzs",
        "title_lv": "LAUKU MĀJA",
        "topic": "dzivesvieta",
        "body": "Lauku mājās Latvijā ir piemājas dārzi ar dārzeņiem un augļiem. Ģimenes audzē kartupeļus, burkānus un ogas.\n\nVasaras vakaros ravē zemi un lasa ražu – pietiek desmit ģimenēm. Tas dod svaigus produktus.\n\nLauksaimniecības speciālisti uzsver, ka dārzi uzlabo veselību un samazina izdevumus. Piemēram, Zemgalē dārzi ir lielāki nekā Kurzemē.\n\nIedzīvotāji iesaka stādīt daudzveidīgus augus.",
        "questions": [
            "Ko audzē lauku māju dārzos?",
            "Kāpēc dārzi uzlabo veselību?",
            "Kā ravē zemi?",
            "Kā atšķiras dārzi Zemgalē?",
            "Ko iesaka iedzīvotāji?"
        ]
    },
    {
        "id": "dzivokla_ire_riga",
        "title_lv": "ĪRE RĪGĀ",
        "topic": "dzivesvieta",
        "body": "Rīgā dzīvokļa īre ir populāra jauniešiem un ģimenēm. Vidēji divistabu dzīvoklis maksā 400 eiro mēnesī.\n\nPirms īres noslēdz līgumu, pārbauda remonta stāvokli un mēraparātus. Īrnieki maksā par ūdeni un elektrību.\n\nNekustamo īpašumu eksperti iesaka meklēt caur aģentūrām un apskatīt vismaz piecus variantus.\n\nSalīdzinot ar pirkšanu, īre ir lētāka īstermiņā.",
        "questions": [
            "Cik maksā divistabu dzīvoklis Rīgā?",
            "Kāpēc slēdz īres līgumu?",
            "Kā meklē dzīvokli?",
            "Ko maksā īrnieki papildus?",
            "Ko iesaka eksperti?"
        ]
    },
    {
        "id": "vasarnicas",
        "title_lv": "VASARNĪCAS",
        "topic": "dzivesvieta",
        "body": "Vasarnīcas Latvijā ir populāras atpūtai pie ezera vai jūras. Ģimenes turp dodas vasarās, lai atpūstos dabā.\n\nParasti ir dārzs, grils un laiva. Svin svētkus ar desmit cilvēkiem.\n\nTūrisma speciālisti norāda, ka vasarnīcas stiprina ģimenes saites. Piemēram, Jūrmalā ir vairākas simti vasarnīcu.\n\nIedzīvotāji iesaka uzturēt kārtību un neizmantot uguni iekštelpās.",
        "questions": [
            "Kur novietotas vasarnīcas Latvijā?",
            "Kāpēc brauc uz vasarnīcām?",
            "Kas ir vasarnīcās?",
            "Cik vasarnīcu ir Jūrmalā?",
            "Ko nedrīkst darīt vasarnīcā?"
        ]
    },
    {
        "id": "dzivosana_mikrorajona",
        "title_lv": "MIKRORAJONS",
        "topic": "dzivesvieta",
        "body": "Mikrorajonos Latvijā, piemēram, Rīgā, ir skolas, veikali un parki blakus mājām. Tas atvieglo ikdienu.\n\nIedzīvotāji staigā kājām uz darbu vai skolu, tērē mazāk laika transportam.\n\nPilsētplānotāji uzsver, ka mikrorajoni veicina aktīvu dzīvesveidu. Aptuveni 30 procenti rīdzinieku dzīvo mikrorajonos.\n\nEksperti iesaka izmantot kopīgās telpas sportam.",
        "questions": [
            "Kas ir mikrorajonos Rīgā?",
            "Kāpēc mikrorajoni atvieglo ikdienu?",
            "Kā iedzīvotāji pārvietojas?",
            "Cik procenti dzīvo mikrorajonos?",
            "Ko iesaka pilsētplānotāji?"
        ]
    },
    {
        "id": "atalinais_darbs",
        "title_lv": "ATĀLINĀTAIS DARBS",
        "topic": "darbs",
        "body": "Latvijā attālinātais darbs kļuva plaši izplatīts pandēmijas laikā. 2023. gadā aptuveni 25 procenti darbinieku strādā no mājām vismaz daļu laika. Tas ļauj ietaupīt laiku un naudu ceļošanai uz darbu, kā arī elastīgi plānot dienu.\n\nLai veiksmīgi strādātu attālināti, jāizveido atsevišķa darba vieta mājās ar labu apgaismojumu un ergonomisku krēslu. Darba devēji iesaka ik dienu sākt ar plānu un beigt ar atskaiti.\n\nPersonāla vadītāji uzsver, ka attālinātais darbs uzlabo līdzsvaru starp darbu un ģimeni, bet prasa pašdisciplīnu. Latvijā tas palīdz risināt reģionu attīstības problēmas, jo cilvēki var dzīvot ārpus Rīgas.\n\nSpeciālisti iesaka regulāri komunicēt ar kolēģiem caur videozvanu, lai saglabātu komandas saikni.",
        "questions": [
            "Cik procenti darbinieku Latvijā 2023. gadā strādā attālināti vismaz daļu laika?",
            "Kāpēc attālinātais darbs ļauj ietaupīt laiku un naudu?",
            "Kā izveidot veiksmīgu darba vietu mājās?",
            "Ko iesaka darba devēji attālinātā darba plānošanai?",
            "Kā saglabāt komandas saikni attālinātā darbā?"
        ]
    },
    {
        "id": "skolen_u_vasaras_darbi",
        "title_lv": "SKOLĒNU VASARAS DARBI",
        "topic": "darbs",
        "body": "Vasaras brīvlaikā daudzi skolēni Latvijā meklē darba iespējas. Populārākie darbi ir ogu lasīšana, sēņu vāku vai palīdzība tirgotājiem. 2024. gadā vairāk nekā 10 tūkstoši jauniešu piedalījās šādos darbos.\n\nLai atrastu darbu, skolēni var vērsties NVA filiālēs vai sludinājumos internetā. Vecākiem jāpārbauda darba vietas drošība un jāslēdz līgums.\n\nDarba eksperti saka, ka vasaras darbs māca atbildību un naudas vērtību. Tas palīdz skolēniem saprast darba vidi un uzkrāt kabatas naudu.\n\nSociāli tas veicina jauniešu neatkarību un pieredzi, bet nedrīkst traucēt atpūtu un mācībām.",
        "questions": [
            "Cik daudz skolēnu 2024. gadā piedalījās vasaras darbos Latvijā?",
            "Kāpēc skolēni meklē vasaras darbus?",
            "Kā skolēni var atrast vasaras darbu?",
            "Ko vecākiem jāizdara, lai bērns strādātu?",
            "Kāpēc vasaras darbs ir labs jauniešiem?"
        ]
    },
    {
        "id": "parkvalifikacija",
        "title_lv": "PĀRKVALIFIKĀCIJA",
        "topic": "darbs",
        "body": "Pieaugušie Latvijā bieži izvēlas pārkvalifikāciju, lai mainītu profesiju. Piemēram, pēc rūpnīcas slēgšanas Daugavpilī daudzi apgūst IT prasmes. Kursi ilgst no 3 līdz 6 mēnešiem.\n\nValsts piedāvā bezmaksas kursus caur Nodarbinātības valsts aģentūru. Jāizvēlas tāda nozare, kur ir darba vietas.\n\nKarjeras konsultanti iesaka sākt ar interešu testiem un prakses mēnesi. Pārkvalifikācija uzlabo algas potenciālu par 20–30 procentiem.\n\nTas palīdz sabiedrībai, jo samazina bezdarbu un veicina reģionu attīstību.",
        "questions": [
            "Cik ilgi ilgst pārkvalifikācijas kursi Latvijā?",
            "Kāpēc pieaugušie izvēlas pārkvalifikāciju?",
            "Kā pieteikties bezmaksas kursiem?",
            "Ko iesaka karjeras konsultanti pirms kursiem?",
            "Kā pārkvalifikācija ietekmē algu?"
        ]
    },
    {
        "id": "popularas_profesijas",
        "title_lv": "POPULĀRAS PROFESIJAS",
        "topic": "darbs",
        "body": "Jauniešu vidū Latvijā populāras ir IT speciālista, mārketinga un medicīnas profesijas. Aptaujā Rīgā 40 procenti jauniešu izvēlējās IT.\n\nŠīs profesijas piesaista ar labām algām un elastīgu grafiku. Mācības notiek koledžās un universitātēs.\n\nDarba tirgus eksperti prognozē, ka līdz 2030. gadam IT darba vietu skaits dubultosies. Jāapgūst svešvalodas un digitālās prasmes.\n\nIzvēle ietekmē ne tikai personīgo dzīvi, bet arī valsts ekonomiku.",
        "questions": [
            "Kura profesija ir populārākā jauniešu vidū Rīgā?",
            "Kāpēc jaunieši izvēlas IT profesiju?",
            "Kur mācās uz populārajām profesijām?",
            "Ko prognozē darba tirgus eksperti par IT?",
            "Ko vēl jāapgūst populāru profesiju speciālistiem?"
        ]
    },
    {
        "id": "rokdarbi_hobijs",
        "title_lv": "ROKDARBI",
        "topic": "darbs",
        "body": "Rokdarbi kā hobijs kļūst arvien populārāki Latvijā, īpaši sievietēm un pensionāriem. Tie ietver adīšanu, aušanu un keramiku.\n\nVar sākt ar vienkāršiem materiāliem no mājām vai iegādāties komplektus par 5–10 eiro. Darbnīcas notiek kultūras centros.\n\nPsihologi saka, ka rokdarbi mazina stresu un uzlabo koncentrēšanos, salīdzinot ar datorspēlēm.\n\nTie veicina sociālās saites, jo cilvēki dalās ar darbiem sociālajos tīklos un bāzēs.",
        "questions": [
            "Kas ietver rokdarbus kā hobiju Latvijā?",
            "Kā sākt nodarboties ar rokdarbiem?",
            "Kāpēc rokdarbi uzlabo labsajūtu?",
            "Kur notiek rokdarbu darbnīcas?",
            "Kā rokdarbi veicina sociālās saites?"
        ]
    },
    {
        "id": "kaiminattiecibas",
        "title_lv": "KAIMIŅATTIECĪBAS",
        "topic": "attiecibas",
        "body": "Daudzdzīvokļu mājās Latvijā labas kaimiņattiecības veido drošu vidi. Rīgā aptuveni 70 procenti iedzīvotāju pazīst savus kaimiņus.\n\nPieklājība nozīmē sveicināties, neklusēt skaļu mūziku pēc 23.00 un palīdzēt ar pasta saņemšanu.\n\nNamu apsaimniekotāji iesaka rīkot kopējas sapulces reizi ceturksnī, lai risinātu kopējās problēmas.\n\nTas stiprina kopienu un samazina konfliktus.",
        "questions": [
            "Cik procenti rīdzinieku pazīst savus kaimiņus?",
            "Kāpēc labas kaimiņattiecības veido drošu vidi?",
            "Kā izturēties pieklājīgi pret kaimiņiem?",
            "Ko iesaka namu apsaimniekotāji?",
            "Ko nodrošina labas kaimiņattiecības?"
        ]
    },
    {
        "id": "iepažinanas",
        "title_lv": "IEPAZĪŠANĀS",
        "topic": "attiecibas",
        "body": "Latvieši iepazīstas caur darba kolēģiem, draugiem vai interneta lietotnēm. Populāras ir kopīgas nodarbes, piemēram, sporta nodarbības.\n\nPirmais solis ir smaids un īss kompliments. Vīrieši biežāk uzsāk sarunu.\n\nSociologi norāda, ka tiešā iepazīšanās ir veiksmīgāka nekā tikai čatos.\n\nTas palīdz veidot ģimenes un stiprināt sabiedrību.",
        "questions": [
            "Caur ko latvieši visbiežāk iepazīstas?",
            "Kāds ir pirmais solis iepazīšanā?",
            "Kāpēc tiešā iepazīšanās ir veiksmīgāka?",
            "Kas uzsāk sarunu?",
            "Kā iepazīšanās ietekmē sabiedrību?"
        ]
    },
    {
        "id": "davanu_pasniesanas",
        "title_lv": "DĀVANAS",
        "topic": "attiecibas",
        "body": "Latvijā dāvanu pasniegšanas tradīcijas ir svarīgas svētkos un jubilejās. Dāvanai jābūt praktiskai, piemēram, grāmata vai šalle.\n\nTo pasniedz ar abām rokām un pateicības vārdiem. Nedrīkst dot pulksteni vai nazi.\n\nEtiķetes speciālisti iesaka aptīt dāvanu papīrā un pievienot kartīti.\n\nTas stiprina attiecības un parāda cieņu.",
        "questions": [
            "Kādas dāvanas izvēlas Latvijā?",
            "Kāpēc nedrīkst dot pulksteni?",
            "Kā pareizi pasniegt dāvanu?",
            "Ko iesaka etiķetes speciālisti?",
            "Kāpēc dāvanas stiprina attiecības?"
        ]
    },
    {
        "id": "palidziba_draugiem",
        "title_lv": "PALĪDZĪBA DRAUGIEM",
        "topic": "attiecibas",
        "body": "Grūtā brīdī latvieši palīdz draugiem ar padomu, naudu vai laiku. Piemēram, slimības laikā ved uz ārstu.\n\nJāzvana un jājautā, ko tieši vajag, nevis jādomā pats.\n\nPsihologi saka, ka palīdzība mazina stresu abām pusēm un stiprina uzticēšanos.\n\nTas veido atbalsta tīklu sabiedrībā.",
        "questions": [
            "Ko darīt draugam slimības laikā?",
            "Kāpēc jāzvana draugam pirms palīdzības?",
            "Kā palīdzība ietekmē stresu?",
            "Kas stiprinās no palīdzības?",
            "Ko nodrošina draugu palīdzība sabiedrībā?"
        ]
    },
    {
        "id": "pieklajibas_frazes",
        "title_lv": "PIEKLĀJĪBAS FRĀZES",
        "topic": "attiecibas",
        "body": "Ikdienā latvieši lieto pieklājības frāzes kā \"lūdzu\", \"paldies\" un \"atvainojiet\". Tās izmanto veikalā vai transportā.\n\nPareizais veids ir teikt skaidri un sirsnīgi, skatoties acīs.\n\nValodas skolotāji uzsver, ka frāzes uzlabo komunikāciju un rada labu iespaidu.\n\nTās veicina harmoniskas attiecības sabiedrībā.",
        "questions": [
            "Kādas frāzes lieto ikdienā Latvijā?",
            "Kā pareizi teikt pieklājības frāzes?",
            "Kāpēc frāzes uzlabo komunikāciju?",
            "Kur lieto pieklājības frāzes?",
            "Ko nodrošina pieklājības frāzes?"
        ]
    },
    {
        "id": "dziesmu_deju_svetki",
        "title_lv": "DZIESMU SVĒTKI",
        "topic": "kultura",
        "body": "Dziesmu un deju svētki Latvijā notiek reizi piecos gados un pulcē tūkstošiem dalībnieku. Pirmie svētki bija 1873. gadā, un kopš tā laika tā ir kļuvusi par latviešu nācijas vienošanās simbolu. Rīgā uz Daugavas krastiem savācas kori, deju kolektīvi un skatītāji no visas valsts.\n\nDalībnieki gatavojas mēnešiem ilgi, mācās dziesmas un dejus no repertuāra, kas apstiprināts īpašā konkursa kārtā. Skatītājiem iesaka iegādāties biļetes laikus, jo vietas tribīnās ātri izpārdodas. Svētki ilgst vairākas dienas ar lieliem koncertiem un gājieniem.\n\nMūzikas eksperti uzskata, ka Dziesmu svētki stiprina kultūras identitāti un veicina sabiedrības saliedētību. Tie ir iekļauti UNESCO nemateriālā kultūras mantojuma sarakstā. Arī ārzemju viesiem tie šķiet unikāls notikums, salīdzinot ar citu valstu festivāliem.",
        "questions": [
            "Kad Latvijā notiek Dziesmu un deju svētki?",
            "Kāpēc Dziesmu svētki ir latviešu nācijas simbols?",
            "Kā dalībnieki gatavojas svētkiem?",
            "Kas repertuāru apstiprina konkursa kārtā?",
            "Ko iesaka skatītājiem, lai redzētu koncertus?"
        ]
    },
    {
        "id": "latvijas_muzikas_skatuve",
        "title_lv": "MŪZIKAS SKATUVE",
        "topic": "kultura",
        "body": "Latvijas mūzikas skatuve ir dzīvīga un daudzveidīga, ar koncertiem Rīgas Arēnā un citos zāles. Populāri ir roka, popmūzikas un folkloras grupas, kas uzstājas gan lielos festivālos, gan mazos klubos. Katru gadu Rīgā notiek aptuveni 500 koncertu.\n\nMūziķi bieži apvieno tradicionālās melodijas ar moderniem ritmiem, radot unikālu skanējumu. Jaunās grupas debitē festivālos kā Positivus. Sekot līdzi var sociālajos tīklos un vietnēs kā bezmaksasbilletes.lv.\n\nMūzikas žurnālisti saka, ka vietējā skatuve ir salīdzinājumā ar kaimiņvalstīm ļoti aktīva un talantīga. Tā veicina jauniešu interesi par kultūru un rada darba iespējas māksliniekiem. Apmeklējot koncertus, cilvēki atpūšas un iepazīst jaunus draugus.",
        "questions": [
            "Cik daudz koncertu gadā notiek Rīgā?",
            "Kā mūziķi apvieno mūzikas stilus?",
            "Kur debitē jaunas grupas?",
            "Ko saka mūzikas žurnālisti par Latvijas skatuvi?",
            "Ko iegūst cilvēki, apmeklējot koncertus?"
        ]
    },
    {
        "id": "teatra_apmeklesana",
        "title_lv": "TEĀTRA APMEKLĒŠANA",
        "topic": "kultura",
        "body": "Teātra apmeklēšana Latvijā ir populāra brīvā laika pavadīšana. Rīgas teātros kā Nacionālajā operā un Dailes teātrī katru mēnesi notiek vairāki desmiti izrāžu. Cilvēki tur meklē emocijas un izklaidi pēc smagas darba nedēļas.\n\nLai iegūtu labākās vietas, biļetes jāpērk vismaz nedēļu iepriekš tiešsaistē. Ģimenēm iesaka izrādes bērniem ar īsu garumu. Pēc izrādes var apmeklēt bufeti un satikt aktierus.\n\nTeātra kritiķi uzskata, ka regulāra apmeklēšana paplašina redzesloku un uzlabo komunikācijas prasmes. Latvijā teātris ir pieejams ikvienam, jo biļešu cenas ir zemākas nekā Eiropas lielpilsētās. Tas stiprina sabiedrības kultūras dzīvi.",
        "questions": [
            "Kur notiek izrādes Rīgā?",
            "Kāpēc cilvēki iet teātrī?",
            "Kā iegūt labākās vietas izrādēm?",
            "Ko iesaka ģimenēm ar bērniem?",
            "Kā teātris ietekmē cilvēkus pēc teātra kritiķu domām?"
        ]
    },
    {
        "id": "latvijas_muzeji",
        "title_lv": "LATVIJAS MUZEJI",
        "topic": "kultura",
        "body": "Latvijas muzeji piedāvā bagātīgu informāciju par valsts vēsturi un kultūru. Populārākais ir Latvijas Nacionālais mākslas muzejs Rīgā, kur ik gadu apmeklē vairāk nekā 100 tūkstoši cilvēku. Tur var redzēt gleznas no 19. gadsimta līdz mūsdienām.\n\nMuzejos bieži rīko izstādes un darbnīcas bērniem. Ieeja ir bezmaksas pirmdienās daudzos no tiem. Apmeklētājiem iesaka izmantot audiovadus, lai labāk izprastu ekspozīcijas.\n\nMuzeju speciālisti saka, ka muzeji saglabā nācijas atmiņu un veicina patriotismu. Salīdzinot ar citām valstīm, Latvijas muzeji ir moderni un interaktīvi. Tie ir svarīgi tūristiem un pašiem iedzīvotājiem.",
        "questions": [
            "Kurš muzejs ir populārākais Rīgā?",
            "Cik daudz cilvēku apmeklē Nacionālo mākslas muzeju gadā?",
            "Kad muzejos ieeja ir bezmaksas?",
            "Kā labāk izprast ekspozīcijas?",
            "Kāpēc muzeji ir svarīgi pēc speciālistu domām?"
        ]
    },
    {
        "id": "latviesu_kino_musdienas",
        "title_lv": "LATVIEŠU KINO",
        "topic": "kultura",
        "body": "Latviešu kino mūsdienās attīstās strauji, ar jaunām filmām uz festivāliem un kinoekrāniem. Populāras ir drāmas un komēdijas par ikdienas dzīvi, piemēram, filma \"Svētais grāls\" guva starptautisku atzinību. Rīgā kinoteātros demonstrē aptuveni 20 vietējas filmas gadā.\n\nRežisori bieži izmanto dabiskas lokācijas Latvijā, filmējot mežos un pie jūras. Skatītājiem iesaka sekot līdzi Rīgas Starptautiskā kino festivāla programmai. Biļetes var pirkt tiešsaistē.\n\nKino eksperti uzskata, ka vietējās filmas stiprina nacionālo identitāti un konkurē ar ārzemju produkciju. Tās māca saprast sabiedrības problēmas un veicina diskusijas. Latvijā kino ir pieejams visiem vecumiem.",
        "questions": [
            "Cik daudz vietējo filmu gadā demonstrē Rīgas kinoteātros?",
            "Kā režisori filmē filmas?",
            "Kādu filmu piemēru min tekstā?",
            "Ko iesaka skatītājiem?",
            "Kāpēc vietējās filmas ir svarīgas pēc ekspertu domām?"
        ]
    },
    {
        "id": "pirts_tradicija",
        "title_lv": "PIRTS TRADĪCIJA",
        "topic": "brivais_laiks",
        "body": "Pirts tradīcija Latvijā ir sena un populāra atpūtas veids. Cilvēki iet pirtī, lai atslābinātos pēc darba un uzlabotu veselību. Vidēji latvietis apmeklē pirti reizi mēnesī, īpaši ziemā.\n\nLabākā pirts ir no koka, ar slotām no bērza vai ozola. Procedūra ilgst stundu: karstums, vēdināšana un atpūta. Nedrīkst dzert alkoholu un ilgi palikt karstumā.\n\nĀrsti iesaka pērties ar mēru, jo tas stiprina imunitāti un uzlabo miegu. Pirts veicina draudzību, jo tur pulcējas ģimenes un draugi. Tā ir daļa no latviešu dzīvesveida, salīdzinot ar somu saunu.",
        "questions": [
            "Cik bieži latvieši apmeklē pirti?",
            "No kādiem materiāliem gatavo labāko pirti?",
            "Kā norit pirts procedūra?",
            "Ko nedrīkst darīt pirtī?",
            "Ko saka ārsti par pēršanos?"
        ]
    },
    {
        "id": "makskeresana_vasa",
        "title_lv": "MAKŠĶERĒŠANA",
        "topic": "brivais_laiks",
        "body": "Makšķerēšana vasarā ir mīļākais nodarbošanās ezuros un upēs Latvijā. Populāras vietas ir Lubāns un Engure, kur noķer līdakas un karūsus. Sezonā izsniedz vairāk nekā 50 tūkstošus atļauju.\n\nLai sāktu, jāiegūst licence un jāzina zivju nēru laiki. Izmanto spieķus ar mānekli vai mākslīgiem ēderiem. Makšķernieki iesaka rīta stundas.\n\nZivsaimniecības speciālisti uzskata, ka hobijs saglabā dabu, ja ievēro noteikumus. Tas atslābina prātu un savieno ar dabu. Ģimenēm tas ir labs kopīga laika pavadīšanas veids.",
        "questions": [
            "Kurās vietās Latvijā makšķerē?",
            "Kas jāiegūst pirms makšķerēšanas?",
            "Kādā dienas laikā iesaka makšķerēt?",
            "Cik daudz atļauju izsniedz sezonā?",
            "Kāpēc makšķerēšana ir labs hobijs pēc speciālistu domām?"
        ]
    },
    {
        "id": "pastagas_mezā",
        "title_lv": "PASTĀGAS MEŽĀ",
        "topic": "brivais_laiks",
        "body": "Pastaigas mežā Latvijā ir veselīgs brīvā laika pavadīšanas veids. Siguldas takās un Gaujas nacionālajā parkā iet tūkstošiem cilvēku katru nedēļu. Tās stiprina sirdi un uzlabo garastāvokli.\n\nIeteicams valkāt ērtus apavus un ņemt līdzi ūdeni. Vasarā var lasīt ogas, rudenī – sēnes. Nedrīkst novirzīties no maršrutiem.\n\nDabas eksperti saka, ka pastaigas ir labākas nekā sporta zāle, jo mežā gaiss ir tīrs. Tās veicina ģimenes tuvumu un māca cienīt vidi. Latvijā ir vairāk nekā 5000 km atpūtas taku.",
        "questions": [
            "Kur Latvijā iet pastaigas mežā?",
            "Ko jāņem līdzi pastaigās?",
            "Kāpēc pastaigas mežā ir veselīgas?",
            "Ko var darīt mežā vasarā un rudenī?",
            "Cik kilometru taku ir Latvijā?"
        ]
    },
    {
        "id": "brivpratigais_darbs",
        "title_lv": "BRĪVPRĀTĪGAIS DARBS",
        "topic": "brivais_laiks",
        "body": "Brīvprātīgais darbs Latvijā palīdz sabiedrībai un sniedz personisku gandarījumu. Organizācijas kā Sarkanais Krusts Rīgā meklē palīgos dzīvnieku patversmēs un senioru aprūpē. Katru gadu piedalās aptuveni 20 tūkstoši brīvprātīgo.\n\nLai sāktu, jāreģistrējas portālā brivpratigais.lv un jāizvēlas projekts. Apmācības notiek bez maksas. Tas aizņem dažas stundas nedēļā.\n\nSociālie darbinieki uzskata, ka brīvprātīgais darbs attīsta prasmes un rada tīklus. Tas stiprina kopienu un mazina vientulību. Salīdzinot ar algotu darbu, tas dod vairāk prieka.",
        "questions": [
            "Kur meklē brīvprātīgos Rīgā?",
            "Kā sākt brīvprātīgo darbu?",
            "Cik daudz brīvprātīgo piedalās gadā?",
            "Ko dod brīvprātīgais darbs pēc sociālo darbinieku domām?",
            "Kāds ir darba apjoms nedēļā?"
        ]
    },
    {
        "id": "gramatu_lasisana_vakos",
        "title_lv": "GRĀMATU LASĪŠANA",
        "topic": "brivais_laiks",
        "body": "Grāmatu lasīšana vakaros ir labs veids, kā atpūsties un iegūt zināšanas. Latvijā iedzīvotāji vidēji izlasa 5 grāmatas gadā, biežāk fantastiku un detektīvus. Bibliotēkās Rīgā ir plašs klāsts.\n\nLai pieradtu, iesaka sākt ar īsām nodaļām pirms miega. E-grāmatas lasa planšetēs. Nedrīkst lasīt spilgtā apgaismojumā.\n\nPsihologi saka, ka lasīšana uzlabo atmiņu un mazina stresu labāk nekā sociālie tīkli. Tā veicina iztēli un ģimenes sarunas. Vakara rituāls palīdz labāk gulēt.",
        "questions": [
            "Cik grāmatu gadā izlasa vidēji latvietis?",
            "Kā pierast pie vakara lasīšanas?",
            "Ko lasa visbiežāk?",
            "Kāpēc lasīšana ir laba pirms miega?",
            "Ko nedrīkst darīt lasot vakarā?"
        ]
    },
    {
        "id": "hokejs_latvija",
        "title_lv": "HOKEJS LATVIJĀ",
        "topic": "sports",
        "body": "Hokejs ir viens no populārākajiem sporta veidiem Latvijā. Ziemā uz ledus laukumiem pulcējas tūkstošiem jauniešu un pieaugušo. Daudzi sāka nodarboties ar hokeju bērnībā, jo tas attīsta ātrumu, izturību un komandas garu. Latvijā ir vairāk nekā 500 kluba, kas trenē spēlētājus.\n\nIk gadu notiek Latvijas čempionāts, kurā piedalās komandas no visas valsts. Rīgā populārākā ir “Dinamo” komanda, kas spēlē Kontinentālajā hokeja līgā. Pamatnoteikums iesācējiem – valkāt aizsargapģērbu, jo spēle ir ātra un fiziska.\n\nHokeja treneri iesaka sākt ar bērnu grupām, kur māca pamata iemaņas. Speciālisti uzsver, ka hokejs stiprina veselību un māca disciplīnu. Turklāt tas veicina draudzību starp dažādu vecumu un reģionu iedzīvotājiem.\n\nSabiedrībā hokejs kļūst par tradīciju, kas vieno ģimenes ledus hallēs ziemas vakaros.",
        "questions": [
            "Kur Latvijā ir vairāk nekā 500 hokeja klubu?",
            "Kāpēc daudzi bērni sāka nodarboties ar hokeju?",
            "Kā iesācējiem jāapsargā sevi hokejā?",
            "Kura Rīgas komanda spēlē Kontinentālajā hokeja līgā?",
            "Ko hokeja treneri iesaka iesācējiem?"
        ]
    },
    {
        "id": "skriejiena_valasprieks",
        "title_lv": "SKRIEŠANA",
        "topic": "sports",
        "body": "Skriešana ir vienkāršs vaļasprieks, ko var baudīt ikviens. Tā neprasa dārgu aprīkojumu – pietiek ar ērtām kurpēm un sporta apģērbu. Latvijā skrējēji mēdz pulcēties parkos vai trasēs, īpaši rudenī un pavasarī.\n\nSkriešana uzlabo sirds veselību, samazina stresu un palīdz noturēt labu figūru. Piemēram, 30 minūšu skrējiens trīs reizes nedēļā dod redzamus rezultātus. Speciālisti iesaka sākt lēnām, lai izvairītos no traumām.\n\nTreneri pamāca: izvēlēties līdzenumu, elpot ritmiski un dzert ūdeni pirms un pēc treniņa. Daudzi pievienojas skriešanas klubiem, kur kopā gatavojas maratoniem, piemēram, Rīgas maratonam.\n\nŠis vaļasprieks veicina aktīvu dzīvesveidu un labas attiecības ar draugiem dabā.",
        "questions": [
            "Ko vajag skriešanai kā vaļaspriekam?",
            "Kāpēc skriešana uzlabo veselību?",
            "Kā elpot skriejot?",
            "Cik ilgi ieteicams skriet nedēļā?",
            "Ko iesaka treneri pirms skrējiena?"
        ]
    },
    {
        "id": "senu_lasisana_rudeni",
        "title_lv": "SĒŅU LASEŠANA",
        "topic": "sports",
        "body": "Rudenī Latvijā daudzi dodas sēņu lasīšanai mežos. Tas ir veselīgs vaļasprieks, kas ļauj pabūt svaigā gaisā un savākt gardus ēdienus. Populārākās sēnes ir baravikas, gailenes un eversēnes, ko lasa no septembra līdz oktobrim.\n\nLai lasītu pareizi, jāzina atšķirība starp ēdajām un indīgajām sēnēm. Eksperti iesaka ņemt grozu un nazi, nearrāut sēnes ar roku. Mežsaimnieki brīdina: nedrīkst lasīt aizsargājamās vietās.\n\nPēc lasīšanas sēnes var kaltēt, marinēt vai cept. Vidēji viens cilvēks oktobrī savāc 5 kilogramus sēņu. Šī nodarbe stiprina saikni ar dabu un māca atpazīt meža veltes.\n\nSēņu lasīšana kļūst par ģimenes tradīciju, kas popularizē veselīgu uzturu.",
        "questions": [
            "Kādas sēnes lasa rudenī Latvijā?",
            "Kāpēc sēnes nedrīkst arrāut ar roku?",
            "Kad lasa lielāko daļu sēņu?",
            "Cik kilogramus sēņu savāc viens cilvēks oktobrī?",
            "Ko darīt ar savāktajām sēnēm?"
        ]
    },
    {
        "id": "darzkopiba_atpusta",
        "title_lv": "DĀRZKOPEIBA",
        "topic": "sports",
        "body": "Dārzkopība ir relaksējošs vaļasprieks daudziem Latvijas iedzīvotājiem. Vasarā un rudenī dārzi piepildās ar dārzeņiem, augļiem un ziediem. Tā prasa pacietību un zināšanas par augsni un laiku.\n\nSāciet ar vienkāršiem kultūraugiem kā redīsi, salāti un tomāti. Katru gadu Latvijā audzē vairāk nekā 100 tūkstošus tonnu dārzeņu mājas dārzos. Padoms: mēslojot ar kūtsmēslu, novāc lielāku ražu.\n\nDārzkopji iesaka stādīt augus rindās un laistīt no rīta. Speciālisti uzsver, ka tas uzlabo garīgo veselību un sniedz svaigus produktus.\n\nŠī nodarbe veicina pašpietiekamību un saikni ar dabu ģimenē.",
        "questions": [
            "Kādi augi piemēroti iesācējiem dārzkopībā?",
            "Kāpēc dārzkopība uzlabo garīgo veselību?",
            "Kā laistīt dārza augus?",
            "Cik tonnu dārzeņu audzē Latvijā gadā?",
            "Ko iesaka dārzkopji mēslošanai?"
        ]
    },
    {
        "id": "dabas_fotografesana",
        "title_lv": "DABAS FOTOGRAFĒŠANA",
        "topic": "sports",
        "body": "Dabas fotografēšana ir populārs vaļasprieks Latvijā. Ar vienkāršu fotoaparātu vai tālruni var iemūžināt mežus, upes un dzīvniekus. Labākais laiks ir rīts vai vakars, kad gaisma ir mīksta.\n\nFotogrāfi iesaka izmantot statīvu un zooma objektīvu. Piemēram, Gaujas nacionālajā parkā redzami reti putni un ziedi. Praktisks padoms: nekustināt dzīvniekus un neiznīcināt vidi.\n\nEksperti saka, ka šī nodarbe attīsta novērošanas prasmes un mieru. Katru gadu notiek izstādes ar dabasskatiem no Latvijas reģioniem.\n\nTā popularizē dabas aizsardzību un iedvesmo citus izzināt valsti.",
        "questions": [
            "Kad vislabāk fotografēt dabu?",
            "Kāpēc Gaujas parkā fotografē retus putnus?",
            "Kādu aprīkojumu iesaka fotogrāfi?",
            "Ko nedrīkst darīt fotografējot dabu?",
            "Ko dabas fotografēšana attīsta?"
        ]
    },
    {
        "id": "centraltirgus_riga",
        "title_lv": "CENTRĀLTIRGUS",
        "topic": "iepirksanas",
        "body": "Rīgas Centrāltirgus ir lielākais tirgus Baltijā. Katru dienu šeit tirgo svaigus dārzeņus, gaļu, zivis un amatnieku preces. Pārdod vairāk nekā 100 tonnu produktu dienā.\n\nIepirkšanās tirgū ir lētāka nekā veikalos, jo preces tieši no ražotājiem. Padoms: izvēlēties svaigas preces un tirgoties cenā. Tirgus piesaista tūristus no visas Eiropas.\n\nTirgotāji iesaka apmeklēt no rīta, kad viss ir svaigs. Speciālisti uzsver, ka tas atbalsta vietējos ražotājus un saglabā tradīcijas.\n\nTirgus veicina sociālos kontaktus un veselīgu uzturu rīdziniekiem.",
        "questions": [
            "Kur ir lielākais tirgus Baltijā?",
            "Kāpēc iepirkšanās tirgū ir lētāka?",
            "Kad apmeklēt tirgu svaigām precēm?",
            "Cik tonnu produktu pārdod dienā?",
            "Ko iesaka tirgotāji apmeklētājiem?"
        ]
    },
    {
        "id": "iepirksanas_interneta",
        "title_lv": "IEPIRKŠANĀS INTERNETĀ",
        "topic": "iepirksanas",
        "body": "Iepirkšanās internetā kļūst arvien populārāka Latvijā. Var pasūtīt apģērbus, grāmatas un sadzīves preces no mājām. Vidēji pasūtījums nonāk 2–3 dienās.\n\nPriekšrocība – plaša izvēle un cenas salīdzinājums. Tomēr jāpārbauda pārdevēja uzticamība un preces atsauksmes. Padoms: izmantot drošas maksājuma metodes.\n\nEksperti brīdina par krāpniecību un iesaka pirkumus no pazīstamiem veikaliem kā “1a.lv”. Tas ietaupa laiku, īpaši vecākiem un strādājošajiem.\n\nŠī metode maina iepirkšanās ieradumus un veicina konkurenci.",
        "questions": [
            "Cik ātri nonāk pasūtījums internetā?",
            "Kāpēc pārbaudīt pārdevēju internetā?",
            "Kādu maksājumu izmantot drošībai?",
            "Kurš veikals piemērots pirkumiem?",
            "Ko interneta iepirkšanās ietaupa?"
        ]
    },
    {
        "id": "lauku_tirdzini",
        "title_lv": "LAUKU TIRDZIŅI",
        "topic": "iepirksanas",
        "body": "Lauku zemnieku tirdziņi notiek Latvijas ciemos sestdienās. Tur pārdod mājas sieru, medu, ogas un amatniecību. Tie ir mazāki nekā Rīgas tirgi, bet svaigāki.\n\nCenu nosaka pats ražotājs, tāpēc tās ir zemākas. Padoms: paņemt grozu un izmēģināt produktus uz vietas. Tirdziņi pulcē iedzīvotājus no apkārtnes.\n\nZemnieki iesaka apmeklēt vasarā, kad ir bagātīga raža. Speciālisti saka, ka tas atbalsta vietējo ekonomiku.\n\nŠie tirdziņi saglabā lauku tradīcijas un veicina veselīgu ēšanu.",
        "questions": [
            "Kad notiek lauku tirdziņi?",
            "Kāpēc preces lauku tirdziņos svaigākas?",
            "Ko paņemt uz tirdziņu?",
            "Kad vislabāk apmeklēt tirdziņus?",
            "Ko saka speciālisti par tirdziņiem?"
        ]
    },
    {
        "id": "lietotas_preces",
        "title_lv": "LIETOTĀS PRECES",
        "topic": "iepirksanas",
        "body": "Lietoto preču veikalos Latvijā var nopirkt apģērbus, mēbeles un tehniku par zemām cenām. Rīgā ir vairāki tādi veikali, piemēram, “ZZZ”. Preces ir kā jaunas pēc tīrīšanas.\n\nPriekšrocība – videi draudzīgi, jo mazāk atkritumu. Padoms: pārbaudīt kvalitāti un lūgt čeku. Cenas līdz 70% zemākas nekā jaunām.\n\nPārdevēji iesaka regulāri apmeklēt, jo preces ātri mainās. Eksperti uzsver, ka tas palīdz ģimenēm ekonomēt.\n\nŠāda iepirkšanās popularizē ilgtspējīgu dzīvi un atjauno tradīcijas.",
        "questions": [
            "Kādas preces pārdod lietoto preču veikalos?",
            "Kāpēc pārbaudīt preču kvalitāti?",
            "Cik procentus zemākas cenas veikalos?",
            "Ko lūgt veikalā?",
            "Ko lietotās preces palīdz videi?"
        ]
    },
    {
        "id": "latvijas_mazes_veikals",
        "title_lv": "MAIZES VEIKALS",
        "topic": "iepirksanas",
        "body": "Latvijas maizes veikalos pārdod tradicionālo rupjmaizi, klaipieti un saldskābo maizi. Tie ir visā valstī, bet populārākie Rīgā un reģionos. Katru dienu cep svaigu maizi no vietējiem miltiem.\n\nMaize ir lētāka nekā importētā, un tā garšo kā mājas. Padoms: izvēlēties rupjmaizi veselībai. Veikali piedāvā arī pīrāgus un konditorejas izstrādājumus.\n\nPiektdienās cep īpašās rudzu maizes. Maiznieki saka, ka tas saglabā latviešu garšas tradīcijas.\n\nŠie veikali veicina vietējo ražošanu un ģimenes maltītes.",
        "questions": [
            "Kādu maizi cep Latvijas maizes veikalos?",
            "Kāpēc izvēlēties rupjmaizi?",
            "Kad cep īpašās rudzu maizes?",
            "No kā gatavo maizi veikalos?",
            "Ko maiznieki saka par maizi?"
        ]
    },
    {
        "id": "ziemassvetku_galds",
        "title_lv": "ZIEMASSVĒTKU GALDS",
        "topic": "edieni",
        "body": "Ziemassvētkos latviešu galdā ir tradicionāli ēdieni kā cepts cūkgaļas cepetis, zirņi ar speķi un piparkūkas. Ģimenes papildina galdu ar kūpinātām zivīm, svaigiem salātiem un kompoti. Šie ēdieni rada svētku noskaņu un apvieno radus.\n\nLai sagatavotu galdu, plānojiet iepirkšanos oktobrī vai novembrī. Izmantojiet vietējos produktus no tirgiem, piemēram, Rīgas Centrāltirgus. Uztura speciālisti iesaka cept gaļu cepeškrāsnī zemākā temperatūrā, lai saglabātu sulīgumu.\n\nEksperti uzsver, ka svētku maltītes satur vairāk kaloriju nekā ikdienas ēdieni – vidēji par 25% vairāk. Pēc svētkiem ēdiet vieglus ēdienus un dzeriet daudz ūdens.\n\nŠāda galdsēšana stiprina ģimenes saites un atbalsta vietējos lauksaimniekus, veicinot ilgtspējīgu saimniecību.",
        "questions": [
            "Kādi ir galvenie tradicionālie ēdieni Ziemassvētku galdā?",
            "Kāpēc jāplāno iepirkšanās oktobrī vai novembrī?",
            "Kā cep gaļu, lai tā saglabā sulīgumu?",
            "No kurienes iegādāties vietējos produktus?",
            "Ko iesaka darīt pēc svētkiem, lai kompensētu vairāk kaloriju?"
        ]
    },
    {
        "id": "skabi_kaposti",
        "title_lv": "SKĀBI KĀPOSTI",
        "topic": "edieni",
        "body": "Skābi kāposti ir populārs ziemas ēdiens Latvijā, ko gatavo no svaigiem kāpostiem ar sāli un ķimenēm. Tos ievāc rudenī un fermentē mucās vai burkās, lai saglabātu uz ziemu.\n\nGatavošana ir vienkārša: sagrieziet kāpostus, saberzējiet ar sāli un saspiestiet traukā. Pēc nedēļas tie ir gatavi ēšanai. Uztura speciālisti iesaka tos ēst ikdienā, jo tajos ir daudz C vitamīna.\n\nSalīdzinājumā ar svaigiem dārzeņiem, skābie kāposti ziemā ir lētāki un ilgāk uzglabājas – līdz pavasarim. Vietējie iedzīvotāji Kurzemē tos lieto zupās un kā garnīru.\n\nŠī tradīcija palīdz izmantot rudens ražu un samazina pārtikas atkritumus, veicinot veselīgu uzturu.",
        "questions": [
            "No kā gatavo skābos kāpostus?",
            "Kāpēc skābos kāpostus ēd ziemā?",
            "Kā notiek skābo kāpostu fermentācija?",
            "Kādu garšvielu pievieno kāpostiem?",
            "Kā skābos kāpostus izmanto ēdienos Kurzemē?"
        ]
    },
    {
        "id": "dzervenenes",
        "title_lv": "DZĒRVENES",
        "topic": "edieni",
        "body": "Dzērvenes ir skābas ogas, ko vāc rudenī purvos, piemēram, Vidzemē. Tās izmanto sulām, ievārījumiem un svaigā veidā, bagātinot uzturu ar antioksidantiem.\n\nLai pagatavotu dzērveņu sulu, nomazgājiet ogas, saberzējiet un izsijājiet. Pievienojiet medu garšai. Ārsti iesaka dzert sulu saaukstēšanās sezonā, jo tā stiprina imunitāti.\n\nVienā glāzē dzērveņu sulas ir tikpat daudz C vitamīna kā divos apelsīnos. Latvijā dzērvenes ir populāras, jo aug mežos un purvos bez lielas kopšanas.\n\nŠo ogu izmantošana veicina veselīgu dzīvesveidu un saglabā vietējās tradīcijas, samazinot importēto augļu patēriņu.",
        "questions": [
            "Kur vāc dzērvenes Latvijā?",
            "Kāpēc dzērveņu sulu iesaka saaukstēšanās sezonā?",
            "Kā pagatavo dzērveņu sulu?",
            "Ar ko salīdzina dzērveņu C vitamīna saturu?",
            "Kā dzērvenes ietekmē importēto augļu patēriņu?"
        ]
    },
    {
        "id": "rudzu_maize",
        "title_lv": "RUDZU MAIZE",
        "topic": "edieni",
        "body": "Latviešu rudzu maize ir ikdienas ēdiens, cepta no rupjmaizes miltiem ar raugu un sāls. Tā ir blīvāka nekā kviešu maize un ilgāk uzglabājas.\n\nMaizes cepšana mājās prasa 2 dienas: mīklu raudzē un cep krāsnī 200 grādos pusstundu. Maizes cepēji iesaka pievienot sezama sēklas garšai.\n\nVienā rīvī rudzu maizes ir divreiz vairāk šķiedrvielu nekā baltmaizē. Vidzemē to ēd ar sieru vai speķi, saglabājot tradīcijas.\n\nRudzu maize stiprina veselību un atbalsta vietējos zemniekus, veicinot ilgtspējīgu lauksaimniecību.",
        "questions": [
            "No kā cep latviešu rudzu maizi?",
            "Kāpēc rudzu maize ilgāk uzglabājas?",
            "Kādas temperatūras un laika cep maizi mājās?",
            "Kas jāpievieno mīklai garšai?",
            "Kā rudzu maize ietekmē vietējos zemniekus?"
        ]
    },
    {
        "id": "darza_teja",
        "title_lv": "DĀRZA TĒJA",
        "topic": "edieni",
        "body": "Dārza zālītes kā pelašķi, kumelītes un nātre ir pamats mājas tējai. Tās vāc vasarā un žāvē ēnā, lai saglabātu aromātu.\n\nLai uzlietu tēju, karstu ūdeni (ne vārītu) pārlej zālītēm un tur 5 minūtes. Ārstniecības augu speciālisti iesaka to pret kuņģa kaitēm.\n\nŠāda tēja ir veselīgāka nekā pirkta, jo bez piedevām. Latvijā dārzos aug desmitiem zālīšu, piemēram, Rīgas apkārtnē.\n\nPaštaisīta tēja samazina atkritumus no maisiņiem un veicina zināšanas par dabu.",
        "questions": [
            "Kādas zālītes izmanto dārza tējai?",
            "Kāpēc tējas uzlietošanai ņem karstu, ne vārītu ūdeni?",
            "Kā sagatavo zālītes tējai?",
            "Pret ko iesaka dārza tēju?",
            "Kā dārza tēja ietekmē atkritumus?"
        ]
    },
    {
        "id": "uz_lietuvu_igauniju",
        "title_lv": "BALTIC CEĻOJUMI",
        "topic": "celosana",
        "body": "No Latvijas viegli ceļot uz Lietuvu un Igauniju ar autobusu vai auto. Piemēram, no Rīgas uz Viļņu brauc 4 stundas pa šoseju E67.\n\nAutobusi kursē katru dienu, biļetes maksā ap 10 eiro. Ceļojumu organizatori iesaka ņemt līdzi pasi un plānot maršrutu iepriekš.\n\nŠie kaimiņvalstis piedāvā līdzīgu kultūru, bet ar atšķirībām – Lietuvā vairāk pilis, Igaunijā modernākas pilsētas. Salīdzinājumā ar tālākām valstīm, tas ir lētāk.\n\nTādas braucieni stiprina Baltijas sadarbību un ļauj iepazīt brāļu tautas.",
        "questions": [
            "Cik ilgi brauc no Rīgas uz Viļņu?",
            "Kāpēc jāņem līdzi pase ceļojot?",
            "Kādu transportu iesaka uz Lietuvu un Igauniju?",
            "Kādas atšķirības ir kaimiņvalstīs?",
            "Ko gūst no šādiem ceļojumiem sociāli?"
        ]
    },
    {
        "id": "jurmalas_vasara",
        "title_lv": "JŪRMALA VASARĀ",
        "topic": "celosana",
        "body": "Jūrmala vasarā piesaista tūkstošiem atpūtnieku ar pludmalēm un priežu mežiem. No Rīgas turp brauc ar električkāju 30 minūtēs.\n\nVasaras sezonā strādā kafejnīcas un noma burām. Vietējie iedzīvotāji iesaka apmeklēt Dzintaru koncertzāli un staigāt pa koka ietvaru.\n\nPludmalē ir 20 kilometrus gara smilšu josla, kas ir tīrāka nekā pilsētā. Tas ir ideāli ģimenēm ar bērniem.\n\nAtpūta Jūrmalā veicina veselību un tūrismu Latvijā.",
        "questions": [
            "Kā nokļūt Jūrmalā no Rīgas?",
            "Kāpēc Jūrmala piesaista atpūtniekus vasarā?",
            "Ko iesaka darīt Jūrmalā?",
            "Cik gara ir Jūrmalas pludmale?",
            "Kāpēc Jūrmala piemērota ģimenēm?"
        ]
    },
    {
        "id": "velosipeds_latvija",
        "title_lv": "VELOCEĻOJUMI",
        "topic": "celosana",
        "body": "Ceļošana pa Latviju ar velosipēdu kļūst populāra, jo ir attīstīti maršruti gar jūru un mežiem. Piemēram, no Rīgas uz Ventspili 200 kilometri.\n\nLai sāktu, nomājiet velosipēdu un paņemiet līdzi ūdeni, remontdarbarīkus. Tūrisma eksperti iesaka braukt maijā, kad laika apstākļi ir labi.\n\nAr velosipēdu redz vairāk nekā ar auto un tas ir videi draudzīgāk. Salīdzinājumā ar sabiedrisko transportu, tas ir lētāk ilgtermiņā.\n\nŠie ceļojumi popularizē aktīvo atpūtu un saglabā dabu.",
        "questions": [
            "Kāds ir attālums no Rīgas uz Ventspili ar velosipēdu?",
            "Kāpēc braukt ar velosipēdu maijā?",
            "Ko paņemt līdzi velotūrē?",
            "Ar ko velosipēds ir labāks par auto?",
            "Ko veicina veloceļojumi?"
        ]
    },
    {
        "id": "rigas_lidosta",
        "title_lv": "RĪGAS LIDOJUMI",
        "topic": "celosana",
        "body": "No Rīgas lidostas lido uz 100 galamērķiem Eiropā un Āzijā. Gada laikā to apkalpo 7 miljonus pasažieru.\n\nLai ceļotu, ierodieties 2 stundas pirms reisa, izietiet kontroli. Aviokompāniju speciālisti iesaka reģistrēties tiešsaistē.\n\nLidosta ir moderna ar veikaliem un kafejnīcām. Tā savieno Latviju ar pasauli ātrāk nekā citi transportlīdzekļi.\n\nLidojumi veicina ekonomiku un kultūru apmaiņu.",
        "questions": [
            "Cik daudz pasažieru apkalpo Rīgas lidosta gadā?",
            "Kāpēc ierasties lidostā 2 stundas pirms reisa?",
            "Kā reģistrēties lidojumam?",
            "Ko piedāvā Rīgas lidosta?",
            "Ko gūst Latvija no lidojumiem?"
        ]
    },
    {
        "id": "kurzemes_piekraste",
        "title_lv": "KURZEMES PIEKRASTE",
        "topic": "celosana",
        "body": "Kurzemes piekrastē atpūta piedāvā smilšu pludmales un bākas, piemēram, Kolku kapos. Vasarā turp brauc ar autobusu no Rīgas 3 stundas.\n\nIeteicams nakšņot viesu namos un baudīt svaigu zivi. Vietējie iedzīvotāji rāda takas gar jūru un stāsta leģendas.\n\nPiekraste ir mierīgāka nekā Jūrmala, ar mazāk tūristiem. Salīdzinājumā ar pilsētu, šeit gaisa ir tīrāks.\n\nAtpūta stiprina vietējo ekonomiku un saglabā kultūru.",
        "questions": [
            "Kā nokļūt Kurzemes piekrastē no Rīgas?",
            "Kāpēc Kurzemes piekraste ir mierīgāka nekā Jūrmala?",
            "Ko iesaka darīt piekrastē?",
            "Kas ir Kolkas kaps?",
            "Kā atpūta ietekmē vietējo ekonomiku?"
        ]
    },
    {
        "id": "latviesu_rudens",
        "title_lv": "LATVIEŠU RUDENS",
        "topic": "laiks",
        "body": "Latviešu rudens sākas septembrī ar dzidru sauli un krāsainām lapām kokos. Tad gaisa temperatūra pazeminās līdz desmit grādiem, un daba iegūst zeltainas un sarkanas krāsas. Cilvēki vāc ābolus, ogas un sēnes mežos, jo tas ir ražas laiks.\n\nLai baudītu rudeni, ieteicams staigāt parkos vai pie upēm. Rīgā, piemēram, Antaļos vai Mežaparkā, lapu kritums rada skaistu skatu. Valkājiet siltu apģērbu, jo naktīs kļūst auksts.\n\nMeteorologi saka, ka rudens Latvijā ir mitrāks nekā vasara, tāpēc bieži līst. Tas palīdz sagatavot zemi nākamajai pavasarim.\n\nDabassargi uzsver, ka jāaizsargā meži no atkritumiem, lai rudens prieki saglabātos nākamajām paaudzēm.",
        "questions": [
            "Kad latviešu rudens sākas?",
            "Kāpēc cilvēki rudenī vāc ābolus un ogas?",
            "Kā baudīt rudeni parkos?",
            "Kāds ir rudens laiks Rīgā?",
            "Ko iesaka dabassargi rudenī mežos?"
        ]
    },
    {
        "id": "sniegotas_ziemas",
        "title_lv": "SNIEGOTAS ZIEMAS",
        "topic": "laiks",
        "body": "Latvijā sniegotas ziemas notiek vidēji katru otro gadu, kad janvārī uzsniedz līdz 30 centimetriem sniega. Tad ceļi kļūst slideni, bet bērni priecājas par sniega bungām un slēpošanu.\n\nLai droši pārvietotos, autovadītājiem jālieto ziemas riepas un jābrauc uzmanīgi. Gājējiem ieteicams valkāt apavus ar labu saķeri.\n\nHidrometeorologi skaidro, ka sniegs nāk no aukstiem gaisa masām no ziemeļiem. Tas baro upes un ezrus pavasarī.\n\nŠādas ziemas veicina tūrismu kalnos Siguldā, kur slēpo gan vietējie, gan viesi.",
        "questions": [
            "Cik bieži Latvijā ir sniegotas ziemas?",
            "Kāpēc autovadītājiem jālieto ziemas riepas?",
            "Kā pārvietoties slidenos ceļos?",
            "No kurienes nāk sniegs Latvijā?",
            "Ko veicina sniegotas ziemas Siguldā?"
        ]
    },
    {
        "id": "baltas_naktis_junija",
        "title_lv": "BALTĀS NAKTIS JŪNIJĀ",
        "topic": "laiks",
        "body": "Jūnijā Latvijā pienāk baltās naktis, kad saule nenoriet visu nakti. No 21. jūnija līdz 10. jūlijam debesīs valda gaišums, un miegs kļūst īsāks.\n\nCilvēki izmanto laiku pastaigām pie jūras vai nometnēs. Jūrmalā baudīt saulrietu un saullēktu var vienā stundā.\n\nAstronomi saka, ka tas notiek zemas saules parādības dēļ. Baltās naktis ir īsākas nekā Somijā, bet garākas nekā Lietuvā.\n\nSpeciālisti iesaka aizvērt logus un izmantot tumšus aizkarus, lai labāk gulētu.",
        "questions": [
            "Kad Latvijā ir baltās naktis?",
            "Kāpēc baltās naktis jūnijā?",
            "Kā cilvēki izmanto baltās naktis Jūrmalā?",
            "Ar ko salīdzina baltās naktis Latvijā?",
            "Ko iesaka speciālisti miega dēļ?"
        ]
    },
    {
        "id": "rudens_veli_un_lietuss",
        "title_lv": "RUDENS VĒJI UN LIETUS",
        "topic": "laiks",
        "body": "Rudens Latvijā atnes stiprus vējus un lietu, kas oktobrī sasniedz 15 dienas mēnesī. Vēji no rietumiem paceļ lapas un viļņo Baltijas jūru.\n\nLai pasargātos, valkājiet ūdensnecaurlaidīgus mēteļus un gumijas zābaku. Neaizmirstiet aizvērt logus mājās.\n\nMeteorologi brīdina, ka vēji var sasniegt 20 metrus sekundē, tāpēc jāseko prognozēm.\n\nŠie laika apstākļi attīra gaisu un sagatavo zemi ziemai, bet iedzīvotāji Vidzemē bieži cieš no plūdiem.",
        "questions": [
            "Cik dienas oktobrī Latvijā līst?",
            "Kāpēc jāvalkā ūdensnecaurlaidīgi mēteļi?",
            "Kā pasargāt mājas no vējiem?",
            "Cik stipri var būt rudens vēji?",
            "Ko rada rudens vēji un lietus Vidzemē?"
        ]
    },
    {
        "id": "pavasara_atmoda_daba",
        "title_lv": "PAVASARA ATMODA DABĀ",
        "topic": "laiks",
        "body": "Pavasarī Latvijā daba mostas aprīlī, kad sniegs nokūst un upes applūst. Putni sāk ligzdot, un kokos parādās pirmie pumpuri.\n\nCilvēki dārzos stāda ziedus un dārzeņus, jo augsne sasilst līdz 10 grādiem. Daugavā Rīgā ūdens līmenis paaugstinās par metru.\n\nBiologi saka, ka pavasaris ir īss, salīdzinot ar vasaru, tāpēc jāstāda ātri.\n\nVides eksperti iesaka nebrukt atkritumus, lai atmodas prieks saglabātos visiem.",
        "questions": [
            "Kad Latvijā daba mostas pavasarī?",
            "Kāpēc pavasarī stāda dārzā?",
            "Kā mainās Daugava Rīgā pavasarī?",
            "Ar ko salīdzina pavasari Latvijā?",
            "Ko iesaka vides eksperti pavasarī?"
        ]
    }
]
