"""Curated catalog of the most-used everyday Latvian phrases and words.

~290 items across 11 thematic categories (greetings, questions, reactions,
feelings, verbs, home nouns, food, numbers/time, transport/directions,
adjectives/descriptions, useful conversational phrases).

Translations are in Russian since the app targets a Russian speaker.
"""

from dataclasses import dataclass


@dataclass
class Phrase:
    lv: str
    ru: str
    hint_ru: str | None = None


CATEGORIES: dict[str, list[Phrase]] = {
    # --------------------------------------------------------------- 1. Greetings
    "sveicieni": [
        Phrase("Sveiki!", "Привет / Здравствуйте"),
        Phrase("Čau!", "Привет (неформально)"),
        Phrase("Labrīt!", "Доброе утро"),
        Phrase("Labdien!", "Добрый день"),
        Phrase("Labvakar!", "Добрый вечер"),
        Phrase("Ar labunakti!", "Спокойной ночи"),
        Phrase("Uz redzēšanos!", "До свидания"),
        Phrase("Uz drīzu!", "До скорого"),
        Phrase("Atā!", "Пока! (неформ.)"),
        Phrase("Tiekamies rīt.", "Увидимся завтра"),
        Phrase("Tiekamies vēlāk.", "Увидимся позже"),
        Phrase("Visu labu!", "Всего хорошего!"),
        Phrase("Veiksmi!", "Удачи!"),
        Phrase("Labu dienu!", "Хорошего дня!"),
        Phrase("Laipni lūdzam!", "Добро пожаловать!"),
        Phrase("Kā iet?", "Как дела? (неформ.)"),
        Phrase("Kā jums klājas?", "Как у вас дела?", "Формальное обращение"),
        Phrase("Kā tev iet?", "Как у тебя дела?"),
        Phrase("Viss labi, paldies.", "Всё хорошо, спасибо"),
        Phrase("Nekas jauns.", "Ничего нового"),
        Phrase("Paldies!", "Спасибо"),
        Phrase("Liels paldies!", "Большое спасибо"),
        Phrase("Lūdzu!", "Пожалуйста", "Ответ на спасибо / вежливая подача"),
        Phrase("Nav par ko.", "Не за что"),
        Phrase("Atvainojiet!", "Извините! (формально)"),
        Phrase("Piedodiet!", "Простите! (формально)"),
        Phrase("Piedod!", "Прости! (неформ.)"),
        Phrase("Priekā!", "За здоровье! (тост)"),
        Phrase("Priecājos iepazīties.", "Рад познакомиться"),
        Phrase("Vai drīkstu?", "Можно? / Разрешите?"),
    ],

    # ------------------------------------------------------------- 2. Questions
    "jautajumi": [
        Phrase("Kas tas ir?", "Что это?"),
        Phrase("Kas tu esi?", "Кто ты?"),
        Phrase("Kā tevi sauc?", "Как тебя зовут?"),
        Phrase("Kā Jūs saucas?", "Как вас зовут?", "Формально"),
        Phrase("Cik tev gadu?", "Сколько тебе лет?"),
        Phrase("No kurienes tu esi?", "Откуда ты?"),
        Phrase("Kur tu dzīvo?", "Где ты живёшь?"),
        Phrase("Kur ir...?", "Где находится...?"),
        Phrase("Kas notiek?", "Что происходит?"),
        Phrase("Kas jauns?", "Что нового?"),
        Phrase("Kāpēc?", "Почему?"),
        Phrase("Kad?", "Когда?"),
        Phrase("Kā?", "Как?"),
        Phrase("Cik?", "Сколько?"),
        Phrase("Cik tas maksā?", "Сколько это стоит?"),
        Phrase("Cik pulkstenis?", "Который час?"),
        Phrase("Kurš?", "Который?"),
        Phrase("Vai jūs runājat krieviski?", "Вы говорите по-русски?"),
        Phrase("Vai jūs runājat angliski?", "Вы говорите по-английски?"),
        Phrase("Vai varat atkārtot?", "Можете повторить?"),
        Phrase("Vai varat palīdzēt?", "Можете помочь?"),
        Phrase("Ko tu dari?", "Что ты делаешь?"),
        Phrase("Ko tu domā?", "Что ты думаешь?"),
        Phrase("Kāpēc ne?", "Почему нет?"),
        Phrase("Ar ko jūs strādājat?", "Кем вы работаете?"),
    ],

    # --------------------------------------------------------- 3. Answers & reactions
    "atbildes": [
        Phrase("Jā.", "Да"),
        Phrase("Nē.", "Нет"),
        Phrase("Varbūt.", "Может быть"),
        Phrase("Protams!", "Конечно!"),
        Phrase("Noteikti.", "Точно / Обязательно"),
        Phrase("Nez vai.", "Вряд ли"),
        Phrase("Pareizi.", "Правильно"),
        Phrase("Nepareizi.", "Неправильно"),
        Phrase("Piekrītu.", "Согласен/согласна"),
        Phrase("Nepiekrītu.", "Не согласен"),
        Phrase("Es nezinu.", "Я не знаю"),
        Phrase("Es nesaprotu.", "Я не понимаю"),
        Phrase("Skaidrs.", "Ясно / Понятно"),
        Phrase("Žēl.", "Жаль"),
        Phrase("Super!", "Супер!"),
        Phrase("Lieliski!", "Отлично!"),
        Phrase("Nav problēmu.", "Нет проблем"),
        Phrase("Viss kārtībā.", "Всё в порядке"),
        Phrase("Droši vien.", "Скорее всего"),
        Phrase("Tieši tā!", "Именно так!"),
        Phrase("Tas ir interesanti.", "Это интересно"),
        Phrase("Tev/Jums taisnība.", "Ты прав / Вы правы"),
        Phrase("Neticu!", "Не верю!"),
        Phrase("Tiešām?", "Правда?"),
        Phrase("Ne visai.", "Не совсем"),
    ],

    # -------------------------------------------------------- 4. Feelings & states
    "jutas": [
        Phrase("Man ir prieks.", "Я рад/рада"),
        Phrase("Esmu noguris.", "Я устал"),
        Phrase("Esmu slims.", "Я болен"),
        Phrase("Man ir karsti.", "Мне жарко"),
        Phrase("Man ir auksti.", "Мне холодно"),
        Phrase("Esmu izsalcis.", "Я проголодался"),
        Phrase("Man slāpst.", "Хочется пить"),
        Phrase("Man ir miegains.", "Хочется спать"),
        Phrase("Man garlaicīgi.", "Мне скучно"),
        Phrase("Man patīk.", "Мне нравится"),
        Phrase("Man nepatīk.", "Мне не нравится"),
        Phrase("Es gribu.", "Я хочу"),
        Phrase("Es negribu.", "Я не хочу"),
        Phrase("Man vajag.", "Мне нужно"),
        Phrase("Man ir bail.", "Мне страшно"),
        Phrase("Esmu aizņemts.", "Я занят"),
        Phrase("Esmu brīvs.", "Я свободен"),
        Phrase("Es priecājos.", "Я радуюсь"),
        Phrase("Esmu sajūsmā.", "Я в восторге"),
        Phrase("Man nepaveicās.", "Мне не повезло"),
        Phrase("Esmu dusmīgs.", "Я сержусь"),
        Phrase("Jūtos labi.", "Чувствую себя хорошо"),
        Phrase("Jūtos slikti.", "Чувствую себя плохо"),
        Phrase("Man ir interesanti.", "Мне интересно"),
        Phrase("Man trūkst...", "Мне не хватает..."),
    ],

    # ----------------------------------------------------------------- 5. Verbs
    "darbibas": [
        Phrase("iet", "идти"),
        Phrase("nākt", "приходить"),
        Phrase("dzīvot", "жить"),
        Phrase("strādāt", "работать"),
        Phrase("mācīties", "учиться"),
        Phrase("ēst", "есть (кушать)"),
        Phrase("dzert", "пить"),
        Phrase("gulēt", "спать"),
        Phrase("runāt", "говорить"),
        Phrase("saprast", "понимать"),
        Phrase("redzēt", "видеть"),
        Phrase("dzirdēt", "слышать"),
        Phrase("mīlēt", "любить"),
        Phrase("zināt", "знать"),
        Phrase("domāt", "думать"),
        Phrase("palīdzēt", "помогать"),
        Phrase("pirkt", "покупать"),
        Phrase("pārdot", "продавать"),
        Phrase("maksāt", "платить"),
        Phrase("gaidīt", "ждать"),
        Phrase("lasīt", "читать"),
        Phrase("rakstīt", "писать"),
        Phrase("spēlēt", "играть"),
        Phrase("dziedāt", "петь"),
        Phrase("dejot", "танцевать"),
        Phrase("klausīties", "слушать"),
        Phrase("skatīties", "смотреть"),
        Phrase("atvērt", "открывать"),
        Phrase("aizvērt", "закрывать"),
        Phrase("atnest", "приносить"),
    ],

    # --------------------------------------------------------- 6. Home / people / body
    "lietvardi_majas": [
        Phrase("māja", "дом"),
        Phrase("dzīvoklis", "квартира"),
        Phrase("istaba", "комната"),
        Phrase("virtuve", "кухня"),
        Phrase("gulta", "кровать"),
        Phrase("galds", "стол"),
        Phrase("krēsls", "стул"),
        Phrase("durvis", "дверь"),
        Phrase("logs", "окно"),
        Phrase("ģimene", "семья"),
        Phrase("māte", "мать"),
        Phrase("tēvs", "отец"),
        Phrase("brālis", "брат"),
        Phrase("māsa", "сестра"),
        Phrase("bērns", "ребёнок"),
        Phrase("draugs", "друг"),
        Phrase("kaimiņš", "сосед"),
        Phrase("kolēģis", "коллега"),
        Phrase("roka", "рука"),
        Phrase("kāja", "нога"),
        Phrase("galva", "голова"),
        Phrase("acs", "глаз"),
        Phrase("ausis", "уши"),
        Phrase("mute", "рот"),
        Phrase("sirds", "сердце"),
    ],

    # ------------------------------------------------------------- 7. Food & drink
    "edins": [
        Phrase("maize", "хлеб"),
        Phrase("ūdens", "вода"),
        Phrase("piens", "молоко"),
        Phrase("kafija", "кофе"),
        Phrase("tēja", "чай"),
        Phrase("sula", "сок"),
        Phrase("alus", "пиво"),
        Phrase("vīns", "вино"),
        Phrase("zupa", "суп"),
        Phrase("salāti", "салат"),
        Phrase("gaļa", "мясо"),
        Phrase("vista", "курица"),
        Phrase("zivs", "рыба"),
        Phrase("dārzeņi", "овощи"),
        Phrase("augļi", "фрукты"),
        Phrase("ābols", "яблоко"),
        Phrase("banāns", "банан"),
        Phrase("kartupeļi", "картошка"),
        Phrase("tomāts", "помидор"),
        Phrase("siers", "сыр"),
        Phrase("sviests", "масло"),
        Phrase("cukurs", "сахар"),
        Phrase("sāls", "соль"),
        Phrase("saldējums", "мороженое"),
        Phrase("brokastis", "завтрак"),
    ],

    # -------------------------------------------------------- 8. Numbers & time
    "skaitli_laiks": [
        Phrase("viens", "один"),
        Phrase("divi", "два"),
        Phrase("trīs", "три"),
        Phrase("četri", "четыре"),
        Phrase("pieci", "пять"),
        Phrase("seši", "шесть"),
        Phrase("septiņi", "семь"),
        Phrase("astoņi", "восемь"),
        Phrase("deviņi", "девять"),
        Phrase("desmit", "десять"),
        Phrase("simts", "сто"),
        Phrase("tūkstotis", "тысяча"),
        Phrase("šodien", "сегодня"),
        Phrase("vakar", "вчера"),
        Phrase("rīt", "завтра"),
        Phrase("rīts", "утро"),
        Phrase("diena", "день"),
        Phrase("vakars", "вечер"),
        Phrase("nakts", "ночь"),
        Phrase("nedēļa", "неделя"),
        Phrase("mēnesis", "месяц"),
        Phrase("gads", "год"),
        Phrase("stunda", "час"),
        Phrase("minūte", "минута"),
        Phrase("tagad", "сейчас"),
    ],

    # ---------------------------------------------------- 9. Transport & directions
    "transports_virzieni": [
        Phrase("mašīna", "машина"),
        Phrase("autobuss", "автобус"),
        Phrase("trolejbuss", "троллейбус"),
        Phrase("vilciens", "поезд"),
        Phrase("lidmašīna", "самолёт"),
        Phrase("velosipēds", "велосипед"),
        Phrase("taksometrs", "такси"),
        Phrase("pietura", "остановка"),
        Phrase("stacija", "станция / вокзал"),
        Phrase("biļete", "билет"),
        Phrase("ceļš", "дорога"),
        Phrase("iela", "улица"),
        Phrase("pa labi", "направо"),
        Phrase("pa kreisi", "налево"),
        Phrase("taisni", "прямо"),
        Phrase("tālu", "далеко"),
        Phrase("tuvu", "близко"),
        Phrase("augšā", "наверху / вверх"),
        Phrase("apakšā", "внизу"),
        Phrase("šeit", "здесь"),
        Phrase("tur", "там"),
        Phrase("Kur ir tuvākā pietura?", "Где ближайшая остановка?"),
        Phrase("Cik minūtes līdz...?", "Сколько минут до...?"),
        Phrase("Es apmaldījos.", "Я заблудился"),
        Phrase("Vai šī ir pareizā pietura?", "Это правильная остановка?"),
    ],

    # ------------------------------------------------- 10. Adjectives & descriptions
    "apraksti": [
        Phrase("liels", "большой"),
        Phrase("mazs", "маленький"),
        Phrase("garš", "длинный / высокий"),
        Phrase("īss", "короткий / низкий"),
        Phrase("ātrs", "быстрый"),
        Phrase("lēns", "медленный"),
        Phrase("labs", "хороший"),
        Phrase("slikts", "плохой"),
        Phrase("jauns", "молодой / новый"),
        Phrase("vecs", "старый"),
        Phrase("karsts", "горячий"),
        Phrase("auksts", "холодный"),
        Phrase("silts", "тёплый"),
        Phrase("vēss", "прохладный"),
        Phrase("smuka māja", "красивый дом"),
        Phrase("jauns draugs", "новый друг"),
        Phrase("vecs kaimiņš", "старый сосед"),
        Phrase("skaists parks", "красивый парк"),
        Phrase("dārgs restorāns", "дорогой ресторан"),
        Phrase("lēts veikals", "дешёвый магазин"),
        Phrase("tukša iela", "пустая улица"),
        Phrase("pilna zāle", "полный зал"),
        Phrase("interesanta grāmata", "интересная книга"),
        Phrase("garlaicīga filma", "скучный фильм"),
        Phrase("patīkams vakars", "приятный вечер"),
    ],

    # ----------------------------------------------- 11. Useful conversational
    "noderigi": [
        Phrase("Kā to sauc latviski?", "Как это называется по-латышски?"),
        Phrase("Lēnāk, lūdzu.", "Медленнее, пожалуйста"),
        Phrase("Ātrāk, lūdzu.", "Быстрее, пожалуйста"),
        Phrase("Pagaidiet, lūdzu.", "Подождите, пожалуйста"),
        Phrase("Vienu minūti.", "Одну минуту"),
        Phrase("Vai šeit ir brīvs?", "Здесь свободно?"),
        Phrase("Aizņemts.", "Занято"),
        Phrase("Labi, piekrītu.", "Хорошо, согласен"),
        Phrase("Piedod, mani sauc...", "Извини, меня зовут..."),
        Phrase("Es runāju mazliet latviski.", "Я немного говорю по-латышски"),
        Phrase("Es mācos latviešu valodu.", "Я учу латышский"),
        Phrase("Uzrakstiet, lūdzu.", "Напишите, пожалуйста"),
        Phrase("Kā jūs teiktu...?", "Как вы скажете...?"),
        Phrase("Kur ir tualete?", "Где туалет?"),
        Phrase("Palīgā!", "Помогите!"),
        Phrase("Es gribētu...", "Я бы хотел..."),
        Phrase("Man šķiet, ka...", "Мне кажется, что..."),
        Phrase("Pēc manām domām...", "По моему мнению..."),
        Phrase("Es zvanu vēlāk.", "Я позвоню позже"),
        Phrase("Sazvanīsimies!", "Созвонимся!"),
        Phrase("Līdz vakaram!", "До вечера!"),
        Phrase("Vai es varu...?", "Могу я...?"),
        Phrase("Bez problēmām.", "Без проблем"),
        Phrase("Piedod par kavēšanos.", "Прости за опоздание"),
        Phrase("Vai esi drošs?", "Ты уверен?"),
        Phrase("Man jāiet.", "Мне нужно идти"),
        Phrase("Tas nav iespējams.", "Это невозможно"),
        Phrase("Tas ir patiešām svarīgi.", "Это действительно важно"),
        Phrase("Kur tu šodien biji?", "Где ты сегодня был?"),
        Phrase("Viss kārtībā!", "Всё в порядке!"),
    ],
}


CATEGORY_TITLES = {
    "sveicieni": {"lv": "Sveicieni un pieklājība", "ru": "Приветствия и вежливость"},
    "jautajumi": {"lv": "Jautājumi", "ru": "Вопросы"},
    "atbildes": {"lv": "Atbildes un reakcijas", "ru": "Ответы и реакции"},
    "jutas": {"lv": "Jūtas un stāvokļi", "ru": "Чувства и состояния"},
    "darbibas": {"lv": "Darbības vārdi", "ru": "Глаголы"},
    "lietvardi_majas": {"lv": "Mājas un cilvēki", "ru": "Дом и люди"},
    "edins": {"lv": "Ēdiens un dzērieni", "ru": "Еда и напитки"},
    "skaitli_laiks": {"lv": "Skaitļi un laiks", "ru": "Числа и время"},
    "transports_virzieni": {
        "lv": "Transports un virzieni",
        "ru": "Транспорт и направления",
    },
    "apraksti": {"lv": "Apraksti un īpašības", "ru": "Описания и прилагательные"},
    "noderigi": {"lv": "Noderīgas frāzes", "ru": "Полезные фразы"},
}


def all_categories() -> list[dict]:
    return [
        {
            "key": k,
            "title_lv": CATEGORY_TITLES[k]["lv"],
            "title_ru": CATEGORY_TITLES[k]["ru"],
            "count": len(items),
        }
        for k, items in CATEGORIES.items()
    ]


def phrases_in(category: str) -> list[dict]:
    items = CATEGORIES.get(category, [])
    return [{"lv": p.lv, "ru": p.ru, "hint_ru": p.hint_ru} for p in items]
