"""Shared load/save helpers for the Lasīšana catalog."""

from __future__ import annotations

import json
import os
import pathlib
import sys
import textwrap
from typing import Any

CATALOG_PATH = (
    pathlib.Path(__file__).resolve().parents[1] / "backend/app/assets/reading_texts.py"
)


HEADER = textwrap.dedent(
    '''
    """Lasīšana text catalog.

    Generated by scripts/generate_reading_texts.py and later polished by
    scripts/expand_reading_texts.py (+10-15% length) and
    scripts/review_reading_texts.py (native-editor pass). Two seed texts
    (PUTNI ZIEMĀ and CITRONS) are official PMLP paraugi for the
    «Latvieši un līvi» category; the rest are Grok-authored in the same
    mold (~140 words, 3-4 paragraphs, informative-publicistic style)
    across the 11 official PMLP topics.

    Format per entry:
    - id: short slug
    - title_lv: uppercase heading
    - topic: one of READING_TOPICS keys
    - source: "PMLP paraugs …" for seeds, otherwise absent
    - body: 3-4 paragraphs separated by "\\n\\n"
    - questions: exactly 5 Latvian questions of varying types
    """
    '''
).lstrip()


def load_env() -> None:
    env_path = pathlib.Path(__file__).resolve().parents[1] / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k, v)


def load_catalog() -> tuple[dict[str, str], list[dict[str, Any]]]:
    backend_root = CATALOG_PATH.parent.parent.parent  # .../backend
    if str(backend_root) not in sys.path:
        sys.path.insert(0, str(backend_root))
    # Fresh import each time — clear cached module so multiple loads in one
    # interpreter see changes on disk.
    for mod_name in list(sys.modules):
        if mod_name.startswith("app.assets.reading_texts"):
            del sys.modules[mod_name]
    from app.assets.reading_texts import READING_TEXTS, READING_TOPICS

    return dict(READING_TOPICS), [dict(t) for t in READING_TEXTS]


def save_catalog(topics: dict[str, str], texts: list[dict[str, Any]]) -> None:
    content = (
        HEADER
        + "\nfrom __future__ import annotations\n\n"
        + "READING_TOPICS: dict[str, str] = "
        + json.dumps(topics, ensure_ascii=False, indent=4)
        + "\n\nREADING_TEXTS: list[dict] = "
        + json.dumps(texts, ensure_ascii=False, indent=4)
        + "\n"
    )
    CATALOG_PATH.write_text(content, encoding="utf-8")


def count_words(s: str) -> int:
    return len([w for w in s.split() if w])


def is_seed(t: dict[str, Any]) -> bool:
    return bool(t.get("source"))
